# Notebook 04: Full End-to-End Fine-Tuning

In this notebook, we perform true end-to-end training. **All weights of the Moirai encoder and the classification heads are updated**.

In [4]:
import torch
import pandas as pd
from IPython.display import display

from heads import (
    MeanPoolingClassifier,
    SingleScaleAttentionClassifier,
    SingleScaleMultiHeadClassifier,
    HierarchicalMultiHeadClassifier,
)
from models import FullMaskOnlyWrapper, FullHeadWrapper
from utils import get_lsst_dataloaders, universal_grid_search

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
NUM_VARS = 6
SIZE = "small"
PATCH_SIZES = [8, 16, 32, 64]

lr_grid = [5*1e-5]
wd_grid = [0.01, 0.05]

BATCH_SIZE = 256

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
from utils import set_seed
set_seed(42)
print("Seed 42 — experiments are reproducible.")

Seed 42 — experiments are reproducible.

In [6]:
tr_loader, va_loader, te_loader, num_classes = get_lsst_dataloaders(BATCH_SIZE, DEVICE)

In [7]:
METRICS_COLS = ["Accuracy", "Macro Precision", "Macro Recall", "Macro F1", "Weighted Precision", "Weighted Recall", "Weighted F1"]
df_patch_8_metrics = pd.DataFrame(columns=METRICS_COLS)
df_patch_8_metrics.index.name = "Model"

## 1. Baseline: Linear Model on Mask Embedding Only (Full FT)

In [8]:
df_mask_only = pd.DataFrame(index=["Mask Only"], columns=PATCH_SIZES)
df_mask_only.columns.name = "Patch Size"

for patch in PATCH_SIZES:
    _, metrics = universal_grid_search(
        model_class=FullMaskOnlyWrapper,
        model_kwargs={"patch_size": patch, "num_vars": NUM_VARS, "num_classes": num_classes, "size": SIZE},
        train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
        wd_grid=wd_grid, lr_grid=lr_grid, verbose=True
    )
    df_mask_only.loc["Mask Only", patch] = metrics["Accuracy"]
    if patch == 8:
        df_patch_8_metrics.loc["Mask Only"] = metrics

LR=5e-05| WD=0.01

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

1.9557560740447626
1.6724274410464899
1.5020063902304424
1.397839158531127
1.3534049687346792
1.2937771682816792
1.2678925080028007
1.2569621985520774
1.2420395796861106
1.2532262850583085
1.2223279098185098
1.2354646514101726
1.276772572742245
1.2705284037241122
1.277150048473017
1.3410246197770281
 Early stopping : 15
Val Loss: 1.2223
LR=5e-05| WD=0.05
1.923425577520355
1.6905082890657874
1.5212360727108591
1.416074535711025
1.3438226895603707
1.289501541029147
1.2668763457275019
1.2690761254085758
1.2555510619791543
1.252039344330144
1.2369243400852854
1.2455453882372476
1.2628619069975566
1.2656653169693985
1.2729210417445114
1.2732638430789234
 Early stopping : 15
Val Loss: 1.2369
LR=5e-05| WD=0.01
1.9833258865325432
1.703437368075053
1.5352505600549342
1.4189283450444539
1.3415294895327188
1.3018071767760486
1.2889735621165455
1.2838413977041476
1.2710853437098062
1.2903875190068066
1.3072209435749829
1.3466109270002784
1.4167458012821228
1.4168044474066757
 Early stopping : 13
Val Loss: 1.2711
LR=5e-05| WD=0.05
1.90781622107436
1.6501677763171312
1.4855053182539901
1.390963476847827
1.322416066154232
1.2856607611586408
1.2588424091416646
1.2469019977057851
1.2431503514933393
1.2562202253961952
1.2687215368922165
1.2709487066036318
1.3169551932714818
1.3066795550710786
 Early stopping : 13
Val Loss: 1.2432
LR=5e-05| WD=0.01
2.0147265767663476
1.7360098691490609
1.5516925536520112
1.4271353279672019
1.34301782526621
1.2990260414960908
1.2809028964701707
1.2710298600235606
1.2794563440772575
1.2912911670963938
1.3254988765328881
1.3271010658605311
1.3793872023016456
 Early stopping : 12
Val Loss: 1.2710
LR=5e-05| WD=0.05
1.9158096827142608
1.6660593486413724
1.5005308253978327
1.3867691881288358
1.313923832846851
1.27176662576877
1.2423670640805873
1.2568144575367128
1.2399120912319277
1.2499995183169357
1.253067992567047
1.258340839448014
1.2858611471284696
1.3058407888179873
 Early stopping : 13
Val Loss: 1.2399
LR=5e-05| WD=0.01
1.8879031001067743
1.6177414655685425
1.4365272715808899
1.3326760220333813
1.2740263299244206
1.2483935569360005
1.2228893584352198
1.2193327686650965
1.2149734555221186
1.221767203594611
1.2464100771803197
1.2604135720710443
1.2907229429338036
1.3096460956868117
 Early stopping : 13
Val Loss: 1.2150
LR=5e-05| WD=0.05
1.8803555267613108
1.6274520284761258
1.4509429592427199
1.3607018362215864
1.3043703170326668
1.2675769513215476
1.260663632454911
1.2764896299780868
1.2825539490071738
1.2743418449308814
1.3007825079972182
1.3564060945821002
 Early stopping : 11
Val Loss: 1.2607

In [9]:
print("Mask Only - Accuracy")
display(df_mask_only.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

Mask Only - Accuracy

Patch Size      8       16      32      64
Mask Only   0.6172  0.6042  0.6127  0.6148

Patch = 8 — All metrics

,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted Precision,Weighted Recall,Weighted F1
Model,,,,,,,
Mask Only,0.6172,0.4982,0.3511,0.3603,0.5867,0.6172,0.5682

## 2. Baseline: Mean Pooling

In [10]:
df_mean_pool = pd.DataFrame(index=["Mean Pooling"], columns=PATCH_SIZES)
df_mean_pool.columns.name = "Patch Size"

for patch in PATCH_SIZES:
    _, metrics = universal_grid_search(
        model_class=FullHeadWrapper,
        model_kwargs={
            "head_class": MeanPoolingClassifier,
            "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes},
            "patch_size": patch, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
        },
        train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
        wd_grid=wd_grid, lr_grid=lr_grid, verbose=True
    )
    df_mean_pool.loc["Mean Pooling", patch] = metrics["Accuracy"]
    if patch == 8:
        df_patch_8_metrics.loc["Mean Pooling"] = metrics

LR=5e-05| WD=0.01
1.8771864272714631
1.6595724414034587
1.4909877534804306
1.370907456894231
1.2913283477953779
1.2314876695958579
1.211476974371003
1.159789517643006
1.1221631736290165
1.1024565192742077
1.0910511986026918
1.0821167492285007
1.0943050869112092
1.1005079629944592
1.1106700577386996
1.1310124465120517
1.1902915423478537
 Early stopping : 16
Val Loss: 1.0821
LR=5e-05| WD=0.05
1.9292028396110223
1.61991264761948
1.4430696566899617
1.340724391665885
1.2822382062431272
1.2346756603659652
1.1910737655996306
1.202671972716727
1.1357636286960384
1.1259828195339296
1.1360633819083856
1.124668512887102
1.1814975622223645
1.1483718253732698
1.1550882134011122
1.1783677010032219
1.209700835429556
 Early stopping : 16
Val Loss: 1.1247
LR=5e-05| WD=0.01
2.1007137453652978
1.8027606553178492
1.598025477998625
1.4486483035048818
1.329054060021067
1.258341961759862
1.20005109833508
1.1736103344738968
1.1579992790532305
1.1534899473190308
1.1481977623652637
1.1469894812359074
1.1605845486245505
1.2243087882918071
1.2317617802115959
1.2559310672728996
1.3154012333086835
 Early stopping : 16
Val Loss: 1.1470
LR=5e-05| WD=0.05
2.0045330485677333
1.7309423510621234
1.5426566135592577
1.4001619631681985
1.3077687364283617
1.243934423942876
1.1969623158617717
1.177863219889199
1.1673451332541984
1.1562886916524995
1.144697334708237
1.1440945698962948
1.167456286709483
1.163736198975788
1.1986596157880334
1.2195648110009791
1.2264182606363685
 Early stopping : 16
Val Loss: 1.1441
LR=5e-05| WD=0.01
1.9704231052863888
1.7255779834297615
1.5714759991420963
1.418986151858074
1.32207804772912
1.2590550882060354
1.233941571499274
1.1864144385345583
1.1746927034564134
1.1501370910706559
1.2022563606742922
1.2201874168907725
1.2668414125597574
1.3276025405744227
1.3064589529502681
 Early stopping : 14
Val Loss: 1.1501
LR=5e-05| WD=0.05
1.8969431708498699
1.6353066180779683
1.4593761994586727
1.3531622479601604
1.2867847496901101
1.2181166739967781
1.1679637490249262
1.150027408832457
1.148941913271338
1.1279047572515843
1.1330620874234332
1.1730051990447006
1.1840995307860336
1.2140374551943647
1.259924849843591
 Early stopping : 14
Val Loss: 1.1279
LR=5e-05| WD=0.01
1.8814536100480614
1.617670864593692
1.4686731817276497
1.3581188868700973
1.2894431255697234
1.2406042659185765
1.2142780059721412
1.2163490144217886
1.2005012549035918
1.189119084094598
1.1989478560967175
1.2555031456598422
1.2859244685832079
1.3044872535922662
1.3321110921177437
 Early stopping : 14
Val Loss: 1.1891
LR=5e-05| WD=0.05
1.849035036273119
1.596506113928508
1.422242266375844
1.325610328495987
1.2721492216839054
1.2139728379443409
1.1923323026517543
1.1987608361050366
1.1991230404473903
1.1683273935705665
1.2059774224351092
1.216681633538347
1.2574774327316904
1.2222242723635541
1.2533545949594762
 Early stopping : 14
Val Loss: 1.1683

In [11]:
print("Mean Pooling - Accuracy")
display(df_mean_pool.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

Mean Pooling - Accuracy

Patch Size        8       16      32     64
Mean Pooling  0.6456  0.6375  0.6127  0.635

Patch = 8 — All metrics

,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted Precision,Weighted Recall,Weighted F1
Model,,,,,,,
Mask Only,0.6172,0.4982,0.3511,0.3603,0.5867,0.6172,0.5682
Mean Pooling,0.6456,0.4804,0.3776,0.3842,0.5968,0.6456,0.6006

## 3. Advanced Pooling: Attention & MHA (Full FT)

In [12]:
PATCH_SIZES_TO_TEST = [8, 16, 32, 64]
MODES = ["shared_context", "independent_context"]
NUM_HEADS = 64

model_names_single = ["Attention (Base)", f"MHA (Heads={NUM_HEADS})"]
index_single = pd.MultiIndex.from_product([model_names_single, MODES], names=["Model", "Mode"])
df_adv_single = pd.DataFrame(index=index_single, columns=PATCH_SIZES_TO_TEST)
df_adv_single.columns.name = "Patch Size"

for patch in PATCH_SIZES_TO_TEST:
    for mode in MODES:
        # 1. Basic Attention
        _, metrics_attn = universal_grid_search(
            model_class=FullHeadWrapper,
            model_kwargs={
                "head_class": SingleScaleAttentionClassifier,
                "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes, "mode": mode},
                "patch_size": patch, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
            },
            train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
            wd_grid=wd_grid, lr_grid=lr_grid
        )
        df_adv_single.loc[("Attention (Base)", mode), patch] = metrics_attn["Accuracy"]
        if patch == 8:
            df_patch_8_metrics.loc[f"Attention ({mode})"] = metrics_attn

        # 2. Multi-Head Attention
        _, metrics_mha = universal_grid_search(
            model_class=FullHeadWrapper,
            model_kwargs={
                "head_class": SingleScaleMultiHeadClassifier,
                "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes, "patch_mode": mode, "num_heads": NUM_HEADS},
                "patch_size": patch, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
            },
            train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
            wd_grid=wd_grid, lr_grid=lr_grid
        )
        df_adv_single.loc[(f"MHA (Heads={NUM_HEADS})", mode), patch] = metrics_mha["Accuracy"]

print("Attention & MHA - Accuracy")
display(df_adv_single.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

LR=5e-05| WD=0.01
 Early stopping : 15
Val Loss: 1.1249
LR=5e-05| WD=0.05
 Early stopping : 17
Val Loss: 1.1389
LR=5e-05| WD=0.01
 Early stopping : 16
Val Loss: 1.1072
LR=5e-05| WD=0.05
 Early stopping : 16
Val Loss: 1.0940
LR=5e-05| WD=0.01
 Early stopping : 17
Val Loss: 1.1312
LR=5e-05| WD=0.05
 Early stopping : 16
Val Loss: 1.1301
LR=5e-05| WD=0.01
 Early stopping : 14
Val Loss: 1.1138
LR=5e-05| WD=0.05
 Early stopping : 14
Val Loss: 1.0927
LR=5e-05| WD=0.01
 Early stopping : 15
Val Loss: 1.2008
LR=5e-05| WD=0.05
 Early stopping : 12
Val Loss: 1.1777
LR=5e-05| WD=0.01
 Early stopping : 14
Val Loss: 1.1015
LR=5e-05| WD=0.05
 Early stopping : 13
Val Loss: 1.1541
LR=5e-05| WD=0.01
 Early stopping : 13
Val Loss: 1.1913
LR=5e-05| WD=0.05
 Early stopping : 14
Val Loss: 1.2453
LR=5e-05| WD=0.01
 Early stopping : 12
Val Loss: 1.1906
LR=5e-05| WD=0.05
 Early stopping : 15
Val Loss: 1.1446
LR=5e-05| WD=0.01
 Early stopping : 14
Val Loss: 1.2103
LR=5e-05| WD=0.05
 Early stopping : 14
Val Loss: 1.2176
LR=5e-05| WD=0.01
 Early stopping : 13
Val Loss: 1.2301
LR=5e-05| WD=0.05
 Early stopping : 14
Val Loss: 1.1761
LR=5e-05| WD=0.01
 Early stopping : 14
Val Loss: 1.2016
LR=5e-05| WD=0.05
 Early stopping : 15
Val Loss: 1.2056
LR=5e-05| WD=0.01
 Early stopping : 14
Val Loss: 1.1184
LR=5e-05| WD=0.05
 Early stopping : 13
Val Loss: 1.1364
LR=5e-05| WD=0.01
 Early stopping : 13
Val Loss: 1.1900
LR=5e-05| WD=0.05
 Early stopping : 13
Val Loss: 1.1660
LR=5e-05| WD=0.01
 Early stopping : 12
Val Loss: 1.2145
LR=5e-05| WD=0.05
 Early stopping : 12
Val Loss: 1.1510
LR=5e-05| WD=0.01
 Early stopping : 13
Val Loss: 1.1856
LR=5e-05| WD=0.05
 Early stopping : 11
Val Loss: 1.1856
LR=5e-05| WD=0.01
 Early stopping : 13
Val Loss: 1.1613
LR=5e-05| WD=0.05
 Early stopping : 12
Val Loss: 1.2125
Attention & MHA - Accuracy

Patch Size                                8       16      32      64
Model            Mode
Attention (Base) shared_context       0.6342  0.6265  0.6115  0.6379
                 independent_context  0.6436  0.6200  0.6221  0.6237
MHA (Heads=64)   shared_context       0.6419  0.6265  0.6022  0.6212
                 independent_context  0.6452  0.6180  0.6196  0.6200

Patch = 8 — All metrics

,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted Precision,Weighted Recall,Weighted F1
Model,,,,,,,
Mask Only,0.6172,0.4982,0.3511,0.3603,0.5867,0.6172,0.5682
Mean Pooling,0.6456,0.4804,0.3776,0.3842,0.5968,0.6456,0.6006
Attention (shared_context),0.6342,0.4110,0.3668,0.3657,0.5673,0.6342,0.5802
Attention (independent_context),0.6436,0.4878,0.3712,0.3767,0.5938,0.6436,0.5886

## 4. Ablation Study: Number of Attention Heads

In [ ]:
HEADS_TO_TEST = [4, 8, 16, 32, 64, 128, 384]

df_heads_ablation8 = pd.DataFrame(index=MODES, columns=HEADS_TO_TEST)
df_heads_ablation8.index.name = "Mode"
df_heads_ablation8.columns.name = "Num Heads (Patch 8)"
df_heads_ablation16 = pd.DataFrame(index=MODES, columns=HEADS_TO_TEST)
df_heads_ablation16.index.name = "Mode"
df_heads_ablation16.columns.name = "Num Heads (Patch 16)"

for PATCH in [8]:
    for mode in MODES:
        for heads in HEADS_TO_TEST:
            _, metrics = universal_grid_search(
                model_class=FullHeadWrapper,
                model_kwargs={
                    "head_class": SingleScaleMultiHeadClassifier,
                    "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes, "patch_mode": mode, "num_heads": heads},
                    "patch_size": PATCH, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
                },
                train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
                wd_grid=wd_grid, lr_grid=lr_grid, verbose=True
            )
            if PATCH == 8:
                df_heads_ablation8.loc[mode, heads] = metrics["Accuracy"]
                df_patch_8_metrics.loc[f"MHA-{heads} ({mode})"] = metrics
            else:
                df_heads_ablation16.loc[mode, heads] = metrics["Accuracy"]

LR=5e-05| WD=0.01
2.12088098370932
1.845229807907973
1.611679833109786
1.4406581341735716
1.323679369639575
1.2591128872662056
1.1866150357858922
1.2201556665141409
1.1637994322350356
1.1130645226656906
1.105252109892
1.0764240423838298
1.1461550336543138
1.110879964944793
1.1327197590494544
1.2263570452124122
1.307886018016474
 Early stopping : 16
Val Loss: 1.0764
LR=5e-05| WD=0.05
2.1203194614348373
1.9178879968519134
1.7125776288955192
1.5719773381706175
1.4035615009990166
1.3156019623686628
1.2389395963854906
1.2363874728117532
1.202962916071822
1.1805909067634646
1.191416535920244
1.1307379831143511
1.16977503823071
1.2549357830993528
1.2986834824569826
1.328151975220781
1.4507200165492733
 Early stopping : 16
Val Loss: 1.1307
LR=5e-05| WD=0.01
2.1162129727805534
1.85354199351334
1.6266274403750411
1.4618353843688965
1.3613802785795879
1.2996986435680855
1.2525347306476375
1.208372115119686
1.195849155022846
1.1832443369113332
1.1439820663715765
1.1893991512980888
1.1621118328435633
1.1662352569704133
1.202695571310152
1.2088468695074561
 Early stopping : 15
Val Loss: 1.1440
LR=5e-05| WD=0.05
2.0050650088767696
1.752077404076491
1.56384071683496
1.4444431803090785
1.342183941748084
1.2833529914297708
1.212821234532488
1.190247462047794
1.224085368761202
1.171056866645813
1.1302472789113114
1.1363230071416714
1.1434549975201367
1.15360501045134
1.1756609959330986
1.2143976979139375
 Early stopping : 15
Val Loss: 1.1302
LR=5e-05| WD=0.01
2.050025951571581
1.7949868159565499
1.5793315191579058
1.4245614569361618
1.3205589443687502
1.2182184486854366
1.1659029363616695
1.134954064842162
1.1097881173699853
1.0679395925707933
1.1340326652294253
1.0661721781986515
1.150395087110318
1.1410157864655905
1.181151378445509
1.2027357206112002
1.259941645754062
 Early stopping : 16
Val Loss: 1.0662
LR=5e-05| WD=0.05
2.054717366288348
1.7234490954779027
1.5631918277197736
1.42832198472527
1.3350938044912446
1.2686843271177959
1.2442094756335746
1.2305684971615551
1.1701704447831565
1.186783355426013
1.199554578075564
1.1152457609409239
1.1278466577452373
1.1426077053798893
1.1190923258541077
1.2353100999584044
1.1692555948970764
 Early stopping : 16
Val Loss: 1.1152
LR=5e-05| WD=0.01
2.098815154253952
1.8754280863738642
1.6623390428419036
1.4910511534388473
1.3615107468473233
1.282467389494423
1.2336977836562366
1.1566389547130926
1.1599065491823646
1.1386371637747539
1.065987197364249
1.0679691157689908
1.0870051054450554
1.1104145835085613
1.2233838850889749
1.233203815250862
 Early stopping : 15
Val Loss: 1.0660
LR=5e-05| WD=0.05
2.0864611137204054
1.8309676734412588
1.5909163525434045
1.4386974892965176
1.3415523244113456
1.2426353208417815
1.1985996641763828
1.160539607691571
1.1484690982151806
1.1672140408337601
1.1302516169664336
1.1113248985957325
1.1527617491357696
1.2573066998303422
1.3047536000972841
1.3479891259495804
1.39225371484834
 Early stopping : 16
Val Loss: 1.1113
LR=5e-05| WD=0.01
2.1758790093708815
1.8057640393575032
1.5556681136774824
1.4153579434728234
1.3216764897834965
1.2929279833305172
1.250874054141161
1.2188823281264887
1.1713552882031697
1.1778105303523987
1.123097951819257
1.167337726771347
1.1094596182427756
1.1167962076218148
1.1067872115267001
1.1915549253060567
1.1695764898284664
1.2598843962196413
1.341474243295871
1.4004475391977202
 Early stopping : 19
Val Loss: 1.1068
LR=5e-05| WD=0.05
2.068404129850186
1.782940836456733
1.5779324556753886
1.418511915013073
1.3090807625917884
1.2490295414032975
1.1762353656737785
1.1533409202001927
1.1260620743278567
1.1035208440408475
1.1272720805997771
1.0926518866686317
1.144157451342761
1.1754297347572762
1.2592247269017909
1.283103503832003
1.4080975898882238
 Early stopping : 16
Val Loss: 1.0927
LR=5e-05| WD=0.01
2.1665057321874106
1.8467485148732254
1.5745597438114445
1.4588816854042737
1.3152547541672621
1.2335360147119538
1.202453016265621
1.1593999504073849
1.1137571218537121
1.1157225312256231
1.1297886032399123
1.1427590827631757
1.1694373435121241
1.1738204810677506
 Early stopping : 13
Val Loss: 1.1138
LR=5e-05| WD=0.05
2.0889284591364667
1.8114812170586936
1.5805194048377555
1.4377841920387455
1.3552705107665644
1.2593705440924419
1.194553766793352
1.179489519537949
1.1626050995617379
1.152178020981269
1.123209218668744
1.1211522294253837
1.1219796019841015
1.1281879142047913
1.187601492656925
1.2430140972137451
1.3213102197259423
 Early stopping : 16
Val Loss: 1.1212
LR=5e-05| WD=0.01
2.018061393644752
1.7072075111110037
1.5708689854397038
1.4400775849334593
1.3475509077552859
1.283681223062965
1.2487857283615484
1.1789875166202948
1.1851309712340192
1.1730920502809974
1.0842539924916212
1.074854343887267
1.0912182020947216
1.0961466969513312
1.142992830857998
1.1496014943936976
1.2592798306689998
 Early stopping : 16
Val Loss: 1.0749
LR=5e-05| WD=0.05
2.079324695152965
1.7239085164496568
1.5409465291635778
1.4144799612401946
1.3191896948387953
1.246096838780535
1.2057289912448665
1.2075887007441948
1.1531361632230805
1.1198079149897506
1.1094846037345203
1.102291396962918
1.0961450677577074
1.1132280322594372
1.169307118508874
1.2850705482126252
1.2483308654490526
1.4466086209304934
 Early stopping : 17
Val Loss: 1.0961
LR=5e-05| WD=0.01
2.0451995900006796
1.7490055657983796
1.5803294065521984
1.460730615670119
1.3662562118313177
1.2621813508553235
1.2084984973194153
1.1598647067217323
1.1421588853122742
1.1189122674911003
1.119202549864606
1.1416675443571758
1.1407234426436386
1.230575856154527
1.2873411857015717
 Early stopping : 14
Val Loss: 1.1189
LR=5e-05| WD=0.05
2.0978362773492085
1.774073075472824
1.5647547787767115
1.4153314799797245
1.3022324253873128
1.2398758050872059
1.2204683922170623
1.1494745907744741
1.134614271846244
1.0922987596775457
1.0911961125164498
1.0936389919218978
1.0915342036301527
1.1266094746628428
1.209694850735548
1.1995545586919396
 Early stopping : 15
Val Loss: 1.0912
LR=5e-05| WD=0.01
2.063606921250258
1.7492450223705633
1.639688631383384
1.4725702312903675
1.3634599941532786
1.2951674635817365
1.2545078915309131
1.2269482283088249
1.165059568436165
1.144376484359183
1.160180234327549
1.110224153937363
1.10370486829339
1.0953529220286424
1.1062072399185925
1.2013099997993406
1.1910638721977793
1.2402108597561596
1.365039335033758
 Early stopping : 18
Val Loss: 1.0954
LR=5e-05| WD=0.05
2.097951745599266
1.874397401887227
1.6636904410230435
1.4871877286492325
1.3670319183085993
1.28141525799666
1.2499156337443407
1.1968246029644478
1.194072526644885
1.178092827641867
1.1051294948996566
1.1369194083097505
1.1361371269071006
1.202858768827547
1.1834856853252504
1.2037861511959294
 Early stopping : 15
Val Loss: 1.1051
LR=5e-05| WD=0.01
2.0969754602850936
1.7940360414303416
1.6284110245665884
1.4891621048857526
1.3886171501826465
1.3061674290556249
1.2201207343155775
1.1766740878423054
1.1677763442683027
1.1413498351244422
1.1334524930008059
1.1034556869568863
1.1617665358675204
1.1359898772666124
1.1624812827846869
1.1491931066280459
1.2141155896148061
 Early stopping : 16
Val Loss: 1.1035
LR=5e-05| WD=0.05
2.0713077696358284
1.730987795969335
1.5307916509426707
1.368454394301748
1.2743532725465976
1.247381508834963
1.1722014657850188
1.1286281085595853
1.0934022480879373
1.093519871797019
1.074160422736067
1.0846887594316064
1.164063716322426
1.19404552428703
1.3054703454661176
1.393255788136304
 Early stopping : 15
Val Loss: 1.0742
LR=5e-05| WD=0.01
2.1024033306090812
1.7470282723263997
1.5675369966320876
1.4387465124207783
1.3506062932130767
1.2780915973632316
1.2170286711638536
1.1853137772257736
1.1728518241789283
1.141169534466131
1.149975528561972
1.1135443710699313
1.1536795647163702
1.1585076582141038
1.2157867604154882
1.2962039621864878
1.3510328841403247
 Early stopping : 16
Val Loss: 1.1135
LR=5e-05| WD=0.05
2.0783152289506868
1.8270367539025905
1.6417654142147158
1.4860676071508143
1.3853473779631824
1.3289730500399581
1.247299425001067
1.1899039212281142
1.1536781933249496
1.175846833523696
1.1488892130735444
1.1416321934723273
1.1166775653032752
1.1563845960105337
1.2729523201298907
1.291607155063288
1.3216616109134705
1.4143541586108324
 Early stopping : 17
Val Loss: 1.1167
LR=5e-05| WD=0.01
2.007347089488332
1.678731788464678
1.50039910785551
1.377048750233844
1.2806764269262794
1.2359486265880306
1.2041620161475204
1.1340828096963527
1.123373615063303
1.0945625411785715
1.102071923938224
1.1137234137310246
1.141392047812299
1.1791096295767682
1.2345775569357522
 Early stopping : 14
Val Loss: 1.0946
LR=5e-05| WD=0.05
2.070027878613976
1.769350743875271
1.5886881603458063
1.4446809398449534
1.3447446852195553
1.2915962886034957
1.2163697306702776
1.203810277993117
1.125477712328841
1.1523746203600875
1.1095872739466226
1.1031128042112521
1.1109790792310141

In [ ]:
print("Ablation: Num Heads (Patch = 8) - Accuracy")
display(df_heads_ablation8.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

Ablation: Num Heads (Patch = 8) - Accuracy

Num Heads (Patch 8)     4       8       16      32      64      128     384
Mode
shared_context       0.6476  0.6261  0.6233  0.6395  0.6346  0.6330  0.6310
independent_context  0.6436  0.6387  0.6395  0.6395  0.6350  0.6334  0.6354

Patch = 8 — All metrics

,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted Precision,Weighted Recall,Weighted F1
Model,,,,,,,
Mask Only,0.6172,0.4982,0.3511,0.3603,0.5867,0.6172,0.5682
Mean Pooling,0.6456,0.4804,0.3776,0.3842,0.5968,0.6456,0.6006
Attention (shared_context),0.6342,0.4110,0.3668,0.3657,0.5673,0.6342,0.5802
Attention (independent_context),0.6436,0.4878,0.3712,0.3767,0.5938,0.6436,0.5886
MHA-4 (shared_context),0.6476,0.4558,0.3743,0.3727,0.5947,0.6476,0.5944
MHA-8 (shared_context),0.6261,0.4090,0.3550,0.3463,0.5611,0.6261,0.5571
MHA-16 (shared_context),0.6233,0.4337,0.3881,0.3990,0.5837,0.6233,0.5965
MHA-32 (shared_context),0.6395,0.4045,0.3716,0.3714,0.5691,0.6395,0.5828
MHA-64 (shared_context),0.6346,0.4716,0.3876,0.3840,0.5838,0.6346,0.5907
MHA-128 (shared_context),0.6330,0.3970,0.3713,0.3663,0.5615,0.6330,0.5773
MHA-384 (shared_context),0.6310,0.4085,0.3444,0.3460,0.5614,0.6310,0.5676
MHA-4 (independent_context),0.6436,0.4159,0.3756,0.3746,0.5768,0.6436,0.5791
MHA-8 (independent_context),0.6387,0.4266,0.3772,0.3739,0.5750,0.6387,0.5896
MHA-16 (independent_context),0.6395,0.3967,0.3706,0.3674,0.5630,0.6395,0.5838
MHA-32 (independent_context),0.6395,0.4034,0.3601,0.3660,0.5749,0.6395,0.5900
MHA-64 (independent_context),0.6350,0.3859,0.3657,0.3619,0.5569,0.6350,0.5795
MHA-128 (independent_context),0.6334,0.3983,0.3700,0.3731,0.5661,0.6334,0.5845
MHA-384 (independent_context),0.6354,0.4155,0.3690,0.3687,0.5660,0.6354,0.5721

## 5. Hierarchical MHA (Full FT)

In [ ]:
df_hierarchical = pd.DataFrame(index=MODES, columns=PATCH_SIZES_TO_TEST)
df_hierarchical.index.name = "Mode"
df_hierarchical.columns.name = "Patch Size"

for patch in PATCH_SIZES_TO_TEST:
    for mode in MODES:
        _, metrics_hier = universal_grid_search(
            model_class=FullHeadWrapper,
            model_kwargs={
                "head_class": HierarchicalMultiHeadClassifier,
                "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes, "patch_mode": mode, "num_heads": NUM_HEADS},
                "patch_size": patch, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
            },
            train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
            wd_grid=wd_grid, lr_grid=lr_grid
        )
        df_hierarchical.loc[mode, patch] = metrics_hier["Accuracy"]
        if patch == 8:
            df_patch_8_metrics.loc[f"Hierarchical ({mode})"] = metrics_hier

LR=5e-05| WD=0.01
 Early stopping : 15
Val Loss: 1.2653
LR=5e-05| WD=0.05
 Early stopping : 19
Val Loss: 1.2004
LR=5e-05| WD=0.01
 Early stopping : 17
Val Loss: 1.2204
LR=5e-05| WD=0.05
 Early stopping : 17
Val Loss: 1.2681
LR=5e-05| WD=0.01
 Early stopping : 15
Val Loss: 1.3088
LR=5e-05| WD=0.05
 Early stopping : 17
Val Loss: 1.2394
LR=5e-05| WD=0.01
 Early stopping : 18
Val Loss: 1.2928
LR=5e-05| WD=0.05
 Early stopping : 17
Val Loss: 1.2959
LR=5e-05| WD=0.01
 Early stopping : 17
Val Loss: 1.2641
LR=5e-05| WD=0.05
 Early stopping : 14
Val Loss: 1.2692
LR=5e-05| WD=0.01
 Early stopping : 14
Val Loss: 1.2758
LR=5e-05| WD=0.05
 Early stopping : 15
Val Loss: 1.2755
LR=5e-05| WD=0.01
 Early stopping : 16
Val Loss: 1.3162
LR=5e-05| WD=0.05
 Early stopping : 14
Val Loss: 1.2880
LR=5e-05| WD=0.01
 Early stopping : 12
Val Loss: 1.3121
LR=5e-05| WD=0.05
 Early stopping : 18
Val Loss: 1.2711

In [ ]:
print("Hierarchical MHA - Accuracy")
display(df_hierarchical.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

Hierarchical MHA - Accuracy

Patch Size               8       16      32      64
Mode
shared_context       0.5949  0.5787  0.5738  0.5876
independent_context  0.5961  0.5827  0.5726  0.5977

Patch = 8 — All metrics

,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted Precision,Weighted Recall,Weighted F1
Model,,,,,,,
Mask Only,0.6172,0.4982,0.3511,0.3603,0.5867,0.6172,0.5682
Mean Pooling,0.6456,0.4804,0.3776,0.3842,0.5968,0.6456,0.6006
Attention (shared_context),0.6342,0.4110,0.3668,0.3657,0.5673,0.6342,0.5802
Attention (independent_context),0.6436,0.4878,0.3712,0.3767,0.5938,0.6436,0.5886
MHA-4 (shared_context),0.6476,0.4558,0.3743,0.3727,0.5947,0.6476,0.5944
MHA-8 (shared_context),0.6261,0.4090,0.3550,0.3463,0.5611,0.6261,0.5571
MHA-16 (shared_context),0.6233,0.4337,0.3881,0.3990,0.5837,0.6233,0.5965
MHA-32 (shared_context),0.6395,0.4045,0.3716,0.3714,0.5691,0.6395,0.5828
MHA-64 (shared_context),0.6346,0.4716,0.3876,0.3840,0.5838,0.6346,0.5907
MHA-128 (shared_context),0.6330,0.3970,0.3713,0.3663,0.5615,0.6330,0.5773
MHA-384 (shared_context),0.6310,0.4085,0.3444,0.3460,0.5614,0.6310,0.5676
MHA-4 (independent_context),0.6436,0.4159,0.3756,0.3746,0.5768,0.6436,0.5791
MHA-8 (independent_context),0.6387,0.4266,0.3772,0.3739,0.5750,0.6387,0.5896
MHA-16 (independent_context),0.6395,0.3967,0.3706,0.3674,0.5630,0.6395,0.5838
MHA-32 (independent_context),0.6395,0.4034,0.3601,0.3660,0.5749,0.6395,0.5900
MHA-64 (independent_context),0.6350,0.3859,0.3657,0.3619,0.5569,0.6350,0.5795
MHA-128 (independent_context),0.6334,0.3983,0.3700,0.3731,0.5661,0.6334,0.5845
MHA-384 (independent_context),0.6354,0.4155,0.3690,0.3687,0.5660,0.6354,0.5721
Hierarchical (shared_context),0.5949,0.3143,0.3271,0.3143,0.4941,0.5949,0.5354
Hierarchical (independent_context),0.5961,0.3228,0.3173,0.3054,0.4865,0.5961,0.5246

In [ ]:
# ── Export Results to CSV ─────────────────────────────────────────────────────
import os
import numpy as np

os.makedirs("results_csv", exist_ok=True)

FINETUNING = "04_FullFT"
MHA_HEADS  = 64
MODE_LABEL = {'shared_context': 'shared', 'independent_context': 'indep'}
rows = []

for patch in PATCH_SIZES:
    # Mean Pooling (no mode)
    acc = float(df_mean_pool.loc['Mean Pooling', patch])
    if patch == 8:
        rec = float(df_patch_8_metrics.loc['Mean Pooling', 'Macro Recall'])
        f1  = float(df_patch_8_metrics.loc['Mean Pooling', 'Macro F1'])
    else:
        rec, f1 = float('nan'), float('nan')
    rows.append({'finetuning': FINETUNING, 'pooling': 'Mean', 'patch_size': patch,
                 'accuracy': acc, 'macro_recall': rec, 'macro_f1': f1})

    # Attention — both modes
    for mode, lbl in MODE_LABEL.items():
        acc = float(df_adv_single.loc[('Attention (Base)', mode), patch])
        if patch == 8:
            rec = float(df_patch_8_metrics.loc[f'Attention ({mode})', 'Macro Recall'])
            f1  = float(df_patch_8_metrics.loc[f'Attention ({mode})', 'Macro F1'])
        else:
            rec, f1 = float('nan'), float('nan')
        rows.append({'finetuning': FINETUNING, 'pooling': f'Attention-{lbl}', 'patch_size': patch,
                     'accuracy': acc, 'macro_recall': rec, 'macro_f1': f1})

    # MHA-64 — both modes (only evaluated at patch=8 in the ablation)
    for mode, lbl in MODE_LABEL.items():
        if patch == 8:
            acc = float(df_heads_ablation8.loc[mode, MHA_HEADS])
            rec = float(df_patch_8_metrics.loc[f'MHA-{MHA_HEADS} ({mode})', 'Macro Recall'])
            f1  = float(df_patch_8_metrics.loc[f'MHA-{MHA_HEADS} ({mode})', 'Macro F1'])
        else:
            acc = float(df_adv_single.loc[('MHA (Heads=64)', mode), patch])
            rec, f1 = float('nan'), float('nan')
        rows.append({'finetuning': FINETUNING, 'pooling': f'MHA-{lbl}', 'patch_size': patch,
                     'accuracy': acc, 'macro_recall': rec, 'macro_f1': f1})

    # Hierarchical — both modes
    for mode, lbl in MODE_LABEL.items():
        acc = float(df_hierarchical.loc[mode, patch])
        if patch == 8:
            rec = float(df_patch_8_metrics.loc[f'Hierarchical ({mode})', 'Macro Recall'])
            f1  = float(df_patch_8_metrics.loc[f'Hierarchical ({mode})', 'Macro F1'])
        else:
            rec, f1 = float('nan'), float('nan')
        rows.append({'finetuning': FINETUNING, 'pooling': f'Hierarchical-{lbl}', 'patch_size': patch,
                     'accuracy': acc, 'macro_recall': rec, 'macro_f1': f1})

df_nb04 = pd.DataFrame(rows)
df_nb04.to_csv("results_csv/nb04_results.csv", index=False)
print("Saved results_csv/nb04_results.csv")
display(df_nb04)

Saved results_csv/nb04_results.csv

,finetuning,pooling,patch_size,accuracy,macro_recall,macro_f1
0,04_FullFT,Mean,8,0.645580,0.377568,0.384207
1,04_FullFT,Attention-shared,8,0.634225,0.366776,0.365705
2,04_FullFT,Attention-indep,8,0.643552,0.371154,0.376716
3,04_FullFT,MHA-shared,8,0.634631,0.387556,0.383954
4,04_FullFT,MHA-indep,8,0.635036,0.365740,0.361883
5,04_FullFT,Hierarchical-shared,8,0.594891,0.327132,0.314330
6,04_FullFT,Hierarchical-indep,8,0.596107,0.317319,0.305447
7,04_FullFT,Mean,16,0.637470,NaN,NaN
8,04_FullFT,Attention-shared,16,0.626521,NaN,NaN
9,04_FullFT,Attention-indep,16,0.620032,NaN,NaN
10,04_FullFT,MHA-shared,16,NaN,NaN,NaN
11,04_FullFT,MHA-indep,16,NaN,NaN,NaN
12,04_FullFT,Hierarchical-shared,16,0.578670,NaN,NaN
13,04_FullFT,Hierarchical-indep,16,0.582725,NaN,NaN
14,04_FullFT,Mean,32,0.612733,NaN,NaN
15,04_FullFT,Attention-shared,32,0.611517,NaN,NaN
16,04_FullFT,Attention-indep,32,0.622060,NaN,NaN
17,04_FullFT,MHA-shared,32,NaN,NaN,NaN
18,04_FullFT,MHA-indep,32,NaN,NaN,NaN
19,04_FullFT,Hierarchical-shared,32,0.573804,NaN,NaN
20,04_FullFT,Hierarchical-indep,32,0.572587,NaN,NaN
21,04_FullFT,Mean,64,0.635036,NaN,NaN
22,04_FullFT,Attention-shared,64,0.637875,NaN,NaN
23,04_FullFT,Attention-indep,64,0.623682,NaN,NaN
24,04_FullFT,MHA-shared,64,NaN,NaN,NaN
25,04_FullFT,MHA-indep,64,NaN,NaN,NaN
26,04_FullFT,Hierarchical-shared,64,0.587591,NaN,NaN
27,04_FullFT,Hierarchical-indep,64,0.597729,NaN,NaN

In [ ]:
df_patch_8_metrics.to_csv("results_csv/nb04_patch_8_metrics.csv", index=True)