# Notebook 04: Full End-to-End Fine-Tuning

In this notebook, we perform true end-to-end training. **All weights of the Moirai encoder and the classification heads are updated**.

In [1]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import copy
from IPython.display import display

from tslearn.datasets import UCR_UEA_datasets
from sklearn.preprocessing import LabelEncoder
from uni2ts.model.moirai import MoiraiModule
from encoder import MoiraiEncoder

from heads import *
from models import *
from utils import  *

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
NUM_VARS = 6
SIZE = "small"
PATCH_SIZES = [8, 16, 32, 64]

lr_grid=[1e-4]
wd_grid=[0.05]

BATCH_SIZE = 256

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
tr_loader, va_loader, te_loader, num_classes = get_lsst_dataloaders(BATCH_SIZE, DEVICE)

In [3]:
METRICS_COLS = ["Accuracy", "Macro Precision", "Macro Recall", "Macro F1", "Weighted Precision", "Weighted Recall", "Weighted F1"]
df_patch_8_metrics = pd.DataFrame(columns=METRICS_COLS)
df_patch_8_metrics.index.name = "Model"

## 1. Baseline: Linear Model on Mask Embedding Only (Full FT)

In [4]:
df_mask_only = pd.DataFrame(index=["Mask Only"], columns=PATCH_SIZES)
df_mask_only.columns.name = "Patch Size"

for patch in PATCH_SIZES:
    _, metrics = universal_grid_search(
        model_class=FullMaskOnlyWrapper,
        model_kwargs={"patch_size": patch, "num_vars": NUM_VARS, "num_classes": num_classes, "size": SIZE},
        train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
        wd_grid=wd_grid, lr_grid=lr_grid, verbose=True
    )
    df_mask_only.loc["Mask Only", patch] = metrics["Accuracy"]
    if patch == 8:
        df_patch_8_metrics.loc["Mask Only"] = metrics

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

LR=0.0001| WD=0.05
1.8154859097023321
1.4946233799787072
1.3497064646666612
1.2532337419385833
1.212744335818097
1.1860913716680634
1.1744311330764274
1.2019058446574018
1.214283249242519
1.285621485089868
1.289043067916622
1.3211739673847105
 Early stopping : 11
Val Loss: 1.1744
LR=0.0001| WD=0.05
1.806666280195965
1.5223553674977
1.3537399216396053
1.2792758108154545
1.2521767102605927
1.2321503879578133
1.2576983905420072
1.314900387593401
1.326508004490922
1.394312181123873
1.427372438151662
 Early stopping : 10
Val Loss: 1.2322
LR=0.0001| WD=0.05
1.7792946575133781
1.491369708766782
1.3528182021970672
1.287336022873235
1.228137376831799
1.243063633034869
1.2630347972962914
1.2899045430547822
1.3466770387277371
1.4197385572805636
 Early stopping : 9
Val Loss: 1.2281
LR=0.0001| WD=0.05
1.6841828881240473
1.4120557628026822
1.2741529699263534
1.2645053659997336
1.2225948077876394
1.1934324493253134
1.2150062826590808
1.232910577843829
1.272711628820838
1.3422050359772473
1.341579542896612
 Early stopping : 10
Val Loss: 1.1934

In [5]:
print("Mask Only - Accuracy")
display(df_mask_only.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

Mask Only - Accuracy

Patch Size      8       16      32      64
Mask Only   0.6196  0.6188  0.6192  0.6099

Patch = 8 — All metrics

,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted Precision,Weighted Recall,Weighted F1
Model,,,,,,,
Mask Only,0.6196,0.4389,0.3398,0.3444,0.5618,0.6196,0.5624

## 2. Baseline: Mean Pooling

In [6]:
df_mean_pool = pd.DataFrame(index=["Mean Pooling"], columns=PATCH_SIZES)
df_mean_pool.columns.name = "Patch Size"

for patch in PATCH_SIZES:
    _, metrics = universal_grid_search(
        model_class=FullHeadWrapper,
        model_kwargs={
            "head_class": MeanPoolingClassifier,
            "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes},
            "patch_size": patch, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
        },
        train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
        wd_grid=wd_grid, lr_grid=lr_grid, verbose=True
    )
    df_mean_pool.loc["Mean Pooling", patch] = metrics["Accuracy"]
    if patch == 8:
        df_patch_8_metrics.loc["Mean Pooling"] = metrics

LR=0.0001| WD=0.05
1.7443417814688953
1.464175550918269
1.307793854697933
1.2296836773554485
1.1792836305571766
1.1108497885184558
1.1063486221359997
1.092919442711807
1.089577285254874
1.0918856587836412
1.1226664471432446
1.168960978345173
1.1996408574949435
1.2654931496798507
 Early stopping : 13
Val Loss: 1.0896
LR=0.0001| WD=0.05
1.7948515919165882
1.5026338565640334
1.3294052486497212
1.2087256113688152
1.1526291331624596
1.1192503586048033
1.0906712010623962
1.088459830943162
1.1372523230265796
1.1328330243506082
1.1152661592979742
1.1912941254251372
1.1941118094979264
 Early stopping : 12
Val Loss: 1.0885
LR=0.0001| WD=0.05
1.7367689783980207
1.4641395894492544
1.3026943042026302
1.2389535651943548
1.1509809552169428
1.1215324140176541
1.1110431944451682
1.1251201639330484
1.1493246981768104
1.208758041141479
1.2381882522164323
1.271044704972244
 Early stopping : 11
Val Loss: 1.1110
LR=0.0001| WD=0.05
1.615010870181448
1.3810684351417106
1.2481141090393066
1.1911004490968657
1.2013791877079785
1.154513595550041
1.1492277209351702
1.1829529264108922
1.1765729033850072
1.1925419607782752
1.241500973701477
1.2566359488944696
 Early stopping : 11
Val Loss: 1.1492

In [7]:
print("Mean Pooling - Accuracy")
display(df_mean_pool.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

Mean Pooling - Accuracy

Patch Size        8       16      32      64
Mean Pooling  0.6565  0.6383  0.6338  0.6285

Patch = 8 — All metrics

,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted Precision,Weighted Recall,Weighted F1
Model,,,,,,,
Mask Only,0.6196,0.4389,0.3398,0.3444,0.5618,0.6196,0.5624
Mean Pooling,0.6565,0.4276,0.3789,0.3802,0.5860,0.6565,0.6031

## 3. Advanced Pooling: Attention & MHA (Full FT)

In [8]:
PATCH_SIZES_TO_TEST = [8, 16, 32, 64]
MODES = ["shared_context", "independent_context"]
NUM_HEADS = 16

model_names_single = ["Attention (Base)", f"MHA (Heads={NUM_HEADS})"]
index_single = pd.MultiIndex.from_product([model_names_single, MODES], names=["Model", "Mode"])
df_adv_single = pd.DataFrame(index=index_single, columns=PATCH_SIZES_TO_TEST)
df_adv_single.columns.name = "Patch Size"

for patch in PATCH_SIZES_TO_TEST:
    for mode in MODES:
        # 1. Basic Attention
        _, metrics_attn = universal_grid_search(
            model_class=FullHeadWrapper,
            model_kwargs={
                "head_class": SingleScaleAttentionClassifier,
                "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes, "mode": mode},
                "patch_size": patch, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
            },
            train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
            wd_grid=wd_grid, lr_grid=lr_grid
        )
        df_adv_single.loc[("Attention (Base)", mode), patch] = metrics_attn["Accuracy"]
        if patch == 8:
            df_patch_8_metrics.loc[f"Attention ({mode})"] = metrics_attn

        # 2. Multi-Head Attention
        _, metrics_mha = universal_grid_search(
            model_class=FullHeadWrapper,
            model_kwargs={
                "head_class": SingleScaleMultiHeadClassifier,
                "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes, "patch_mode": mode, "num_heads": NUM_HEADS},
                "patch_size": patch, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
            },
            train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
            wd_grid=wd_grid, lr_grid=lr_grid
        )
        df_adv_single.loc[(f"MHA (Heads={NUM_HEADS})", mode), patch] = metrics_mha["Accuracy"]

print("Attention & MHA - Accuracy")
display(df_adv_single.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

LR=0.0001| WD=0.05
 Early stopping : 12
Val Loss: 1.1594
LR=0.0001| WD=0.05
 Early stopping : 12
Val Loss: 1.0785
LR=0.0001| WD=0.05
 Early stopping : 12
Val Loss: 1.1399
LR=0.0001| WD=0.05
 Early stopping : 13
Val Loss: 1.0694
LR=0.0001| WD=0.05
 Early stopping : 11
Val Loss: 1.1816
LR=0.0001| WD=0.05
 Early stopping : 10
Val Loss: 1.1092
LR=0.0001| WD=0.05
 Early stopping : 10
Val Loss: 1.1510
LR=0.0001| WD=0.05
 Early stopping : 11
Val Loss: 1.1321
LR=0.0001| WD=0.05
 Early stopping : 13
Val Loss: 1.1361
LR=0.0001| WD=0.05
 Early stopping : 12
Val Loss: 1.1215
LR=0.0001| WD=0.05
 Early stopping : 10
Val Loss: 1.1762
LR=0.0001| WD=0.05
 Early stopping : 9
Val Loss: 1.1665
LR=0.0001| WD=0.05
 Early stopping : 12
Val Loss: 1.1815
LR=0.0001| WD=0.05
 Early stopping : 11
Val Loss: 1.1430
LR=0.0001| WD=0.05
 Early stopping : 9
Val Loss: 1.1711
LR=0.0001| WD=0.05
 Early stopping : 10
Val Loss: 1.1519
Attention & MHA - Accuracy

Patch Size                                8       16      32      64
Model            Mode
Attention (Base) shared_context       0.6269  0.6375  0.6237  0.6221
                 independent_context  0.6387  0.6395  0.6107  0.6403
MHA (Heads=16)   shared_context       0.6448  0.6164  0.6233  0.6261
                 independent_context  0.6460  0.6123  0.6176  0.6245

Patch = 8 — All metrics

,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted Precision,Weighted Recall,Weighted F1
Model,,,,,,,
Mask Only,0.6196,0.4389,0.3398,0.3444,0.5618,0.6196,0.5624
Mean Pooling,0.6565,0.4276,0.3789,0.3802,0.5860,0.6565,0.6031
Attention (shared_context),0.6269,0.4200,0.3758,0.3693,0.5634,0.6269,0.5781
Attention (independent_context),0.6387,0.4777,0.3733,0.3738,0.5791,0.6387,0.5848

## 4. Ablation Study: Number of Attention Heads

In [9]:
HEADS_TO_TEST = [16, 32, 64, 128]

df_heads_ablation8 = pd.DataFrame(index=MODES, columns=HEADS_TO_TEST)
df_heads_ablation8.index.name = "Mode"
df_heads_ablation8.columns.name = "Num Heads (Patch 8)"
df_heads_ablation16 = pd.DataFrame(index=MODES, columns=HEADS_TO_TEST)
df_heads_ablation16.index.name = "Mode"
df_heads_ablation16.columns.name = "Num Heads (Patch 16)"

for PATCH in [8, 16]:
    for mode in MODES:
        for heads in HEADS_TO_TEST:
            _, metrics = universal_grid_search(
                model_class=FullHeadWrapper,
                model_kwargs={
                    "head_class": SingleScaleMultiHeadClassifier,
                    "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes, "patch_mode": mode, "num_heads": heads},
                    "patch_size": PATCH, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
                },
                train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
                wd_grid=wd_grid, lr_grid=lr_grid, verbose=True
            )
            if PATCH == 8:
                df_heads_ablation8.loc[mode, heads] = metrics["Accuracy"]
                df_patch_8_metrics.loc[f"MHA-{heads} ({mode})"] = metrics
            else:
                df_heads_ablation16.loc[mode, heads] = metrics["Accuracy"]

LR=0.0001| WD=0.05
1.8792030946995184
1.587150946865237
1.3727774503754406
1.2533731005056117
1.2024532643760122
1.1295714349281498
1.1120942540285064
1.0980616110127146
1.1063881240239957
1.1157859486293018
1.1964236391269094
1.2842744298097564
1.4340674722097753
 Early stopping : 12
Val Loss: 1.0981
LR=0.0001| WD=0.05
1.9495068003491658
1.574629487060919
1.3791399632042987
1.3061113260625823
1.2286659430682174
1.1426450266101496
1.1761039224097398
1.1324723590680255
1.096756697670231
1.1422289600217246
1.1594579966087653
1.2534034320009433
1.2797474570390655
1.4661017792011664
 Early stopping : 13
Val Loss: 1.0968
LR=0.0001| WD=0.05
1.9351809577244083
1.554339984568154
1.35819765998096
1.2449165747417668
1.1559496265116747
1.1580696832842943
1.1797341573529128
1.1181464563540326
1.1252768272306861
1.187676118641365
1.1802993809304587
1.2340882464153011
1.3137529661984948
 Early stopping : 12
Val Loss: 1.1181
LR=0.0001| WD=0.05
1.9458519685559157
1.5944017637066725
1.3478356309053374
1.24234768045627
1.1911645362047645
1.1097162845658093
1.0998655363796204
1.1339843215011969
1.0884879275066097
1.0711383955265448
1.1080461488506659
1.2132912951756298
1.2553011508491951
1.3904802896142976
1.4842385199011825
 Early stopping : 14
Val Loss: 1.0711
LR=0.0001| WD=0.05
1.8591938900753735
1.5961254437764485
1.3794708688084671
1.2726203745942775
1.180925965309143
1.1298658256608296
1.164575510877904
1.1321691546013686
1.1053752288585756
1.1384497987545603
1.132890025774638
1.207598813181001
1.2107333158089864
1.3520418570293644
 Early stopping : 13
Val Loss: 1.1054
LR=0.0001| WD=0.05
1.8658747605191983
1.4927478175822313
1.2987450632622572
1.1843589912585126
1.182561009880004
1.1042824954521366
1.0598512771652966
1.1890485819762315
1.0937875693406516
1.107132588944784
1.2405272644709766
1.189407988292415
 Early stopping : 11
Val Loss: 1.0599
LR=0.0001| WD=0.05
1.8092998518207208
1.5348000419818288
1.396196947834356
1.2826643135489486
1.1818211747378837
1.1463082253448362
1.0870690200386979
1.073174327369628
1.0700387770567483
1.0789143118431899
1.1421374760992158
1.2168945752508271
1.3211661761369162
1.4562074042917268
 Early stopping : 13
Val Loss: 1.0700
LR=0.0001| WD=0.05
1.7696529365167386
1.4881094122320655
1.3256858209284341
1.3068055941806576
1.1743514644421214
1.0884318429280102
1.0838265225170105
1.0971173348465586
1.0561335503570433
1.1206952682355555
1.1443197853196927
1.2558500708603277
1.318652118124613
1.3552218200714607
 Early stopping : 13
Val Loss: 1.0561
LR=0.0001| WD=0.05
1.874956125166358
1.5256117088038748
1.3725280684184253
1.2365558767706397
1.1682815745594055
1.1308957289874069
1.1562340530922743
1.1140042591870316
1.097570835090265
1.2064111484744684
1.2746992683022973
1.425527060904154
1.602945839486471
1.6517463893425175
 Early stopping : 13
Val Loss: 1.0976
LR=0.0001| WD=0.05
1.8966348995038165
1.5622551043828328
1.361642379101699
1.2661380186313536
1.1984770404614085
1.1444049521190365
1.1266846453271262
1.0911638940252908
1.188783251173128
1.2505455782743005
1.4443905392313392
1.4948555754452217
1.6562959643883435
 Early stopping : 12
Val Loss: 1.0912
LR=0.0001| WD=0.05
1.9287077295101756
1.572111452498087
1.3555093208948772
1.2569045797596132
1.198542289617585
1.136362632115682
1.1105522692688112
1.1424904005314276
1.1902573166823969
1.2725439294566954
1.3929705687654697
1.5519325035374338
 Early stopping : 11
Val Loss: 1.1106
LR=0.0001| WD=0.05
1.908876459772994
1.6397874326240727
1.3685616254806519
1.259219344069318
1.1471941170653677
1.1383493343989055
1.1099074429612819
1.1344129816303408
1.2538114708613575
1.3667209070872486
1.4612510340000555
1.5917255316323382
 Early stopping : 11
Val Loss: 1.1099
LR=0.0001| WD=0.05
1.9418940069229622
1.6376232248011644
1.401945023032708
1.2587191118457453
1.2011558757564886
1.1787966218421129
1.1123821812916577
1.1190765776285312
1.1506956137292754
1.2301628046888646
1.42240334429392
1.59646343797203
 Early stopping : 11
Val Loss: 1.1124
LR=0.0001| WD=0.05
1.9052431505870044
1.5958145440109377
1.3748504262629564
1.2218687049741668
1.1380977572464361
1.096379733667141
1.1360835864291927
1.0825547357884848
1.1297631370342844
1.1366966652676342
1.343222019149036
1.3700645919737777
1.5766751601444027
 Early stopping : 12
Val Loss: 1.0826
LR=0.0001| WD=0.05
1.9573877158203745
1.637056805253998
1.3875214103760758
1.2776576154600314
1.2145673598700422
1.1798865359003952
1.103453844543395
1.127335894398573
1.0837159864301604
1.144586066889569
1.2468907474502315
1.461940225546922
1.4895181946638154
1.5739192739734804
 Early stopping : 13
Val Loss: 1.0837
LR=0.0001| WD=0.05
1.7786280915019959
1.4831446787206137
1.3449579351316623
1.2182264395845614
1.137236323783068
1.0900739828745525
1.0657476351513127
1.1031253134332053
1.118998979165302
1.1770144264872482
1.394981115814147
1.4276005465809891
 Early stopping : 11
Val Loss: 1.0657

In [10]:
print("Ablation: Num Heads (Patch = 8) - Accuracy")
display(df_heads_ablation8.astype(float).round(4))
print("Ablation: Num Heads (Patch = 16) - Accuracy")
display(df_heads_ablation16.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

Ablation: Num Heads (Patch = 8) - Accuracy

Num Heads (Patch 8)     16      32      64      128
Mode
shared_context       0.6237  0.6480  0.6277  0.6334
independent_context  0.6371  0.6436  0.6403  0.6391

Ablation: Num Heads (Patch = 16) - Accuracy

Num Heads (Patch 16)     16      32      64      128
Mode
shared_context        0.6273  0.6310  0.6419  0.6290
independent_context   0.6277  0.6395  0.6375  0.6391

Patch = 8 — All metrics

,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted Precision,Weighted Recall,Weighted F1
Model,,,,,,,
Mask Only,0.6196,0.4389,0.3398,0.3444,0.5618,0.6196,0.5624
Mean Pooling,0.6565,0.4276,0.3789,0.3802,0.5860,0.6565,0.6031
Attention (shared_context),0.6269,0.4200,0.3758,0.3693,0.5634,0.6269,0.5781
Attention (independent_context),0.6387,0.4777,0.3733,0.3738,0.5791,0.6387,0.5848
MHA-16 (shared_context),0.6237,0.3861,0.3634,0.3552,0.5479,0.6237,0.5652
MHA-32 (shared_context),0.6480,0.4111,0.3815,0.3790,0.5760,0.6480,0.5950
MHA-64 (shared_context),0.6277,0.4512,0.3739,0.3780,0.5675,0.6277,0.5691
MHA-128 (shared_context),0.6334,0.4648,0.3835,0.3834,0.5869,0.6334,0.5977
MHA-16 (independent_context),0.6371,0.4089,0.3724,0.3731,0.5707,0.6371,0.5851
MHA-32 (independent_context),0.6436,0.4205,0.3802,0.3781,0.5744,0.6436,0.5945
MHA-64 (independent_context),0.6403,0.4518,0.3776,0.3830,0.5678,0.6403,0.5913
MHA-128 (independent_context),0.6391,0.4718,0.3981,0.4041,0.5776,0.6391,0.5996

## 5. Hierarchical MHA (Full FT)

In [11]:
df_hierarchical = pd.DataFrame(index=MODES, columns=PATCH_SIZES_TO_TEST)
df_hierarchical.index.name = "Mode"
df_hierarchical.columns.name = "Patch Size"

for patch in PATCH_SIZES_TO_TEST:
    for mode in MODES:
        _, metrics_hier = universal_grid_search(
            model_class=FullHeadWrapper,
            model_kwargs={
                "head_class": HierarchicalMultiHeadClassifier,
                "head_kwargs": {"num_vars": NUM_VARS, "num_classes": num_classes, "patch_mode": mode, "num_heads": NUM_HEADS},
                "patch_size": patch, "num_vars": NUM_VARS, "size": SIZE, "remove_last_patch": False
            },
            train_loader=tr_loader, val_loader=va_loader, test_loader=te_loader, device=DEVICE,
            wd_grid=wd_grid, lr_grid=lr_grid
        )
        df_hierarchical.loc[mode, patch] = metrics_hier["Accuracy"]
        if patch == 8:
            df_patch_8_metrics.loc[f"Hierarchical ({mode})"] = metrics_hier

LR=0.0001| WD=0.05
 Early stopping : 15
Val Loss: 1.2529
LR=0.0001| WD=0.05
 Early stopping : 13
Val Loss: 1.2223
LR=0.0001| WD=0.05
 Early stopping : 13
Val Loss: 1.2558
LR=0.0001| WD=0.05
 Early stopping : 12
Val Loss: 1.2814
LR=0.0001| WD=0.05
 Early stopping : 12
Val Loss: 1.2924
LR=0.0001| WD=0.05
 Early stopping : 14
Val Loss: 1.2507
LR=0.0001| WD=0.05
 Early stopping : 13
Val Loss: 1.2847
LR=0.0001| WD=0.05
 Early stopping : 11
Val Loss: 1.2634

In [12]:
print("Hierarchical MHA - Accuracy")
display(df_hierarchical.astype(float).round(4))
print("\nPatch = 8 — All metrics")
display(df_patch_8_metrics.astype(float).round(4))

Hierarchical MHA - Accuracy

Patch Size               8       16      32      64
Mode
shared_context       0.6148  0.5994  0.5795  0.5876
independent_context  0.5973  0.5848  0.5904  0.5961

Patch = 8 — All metrics

,Accuracy,Macro Precision,Macro Recall,Macro F1,Weighted Precision,Weighted Recall,Weighted F1
Model,,,,,,,
Mask Only,0.6196,0.4389,0.3398,0.3444,0.5618,0.6196,0.5624
Mean Pooling,0.6565,0.4276,0.3789,0.3802,0.5860,0.6565,0.6031
Attention (shared_context),0.6269,0.4200,0.3758,0.3693,0.5634,0.6269,0.5781
Attention (independent_context),0.6387,0.4777,0.3733,0.3738,0.5791,0.6387,0.5848
MHA-16 (shared_context),0.6237,0.3861,0.3634,0.3552,0.5479,0.6237,0.5652
MHA-32 (shared_context),0.6480,0.4111,0.3815,0.3790,0.5760,0.6480,0.5950
MHA-64 (shared_context),0.6277,0.4512,0.3739,0.3780,0.5675,0.6277,0.5691
MHA-128 (shared_context),0.6334,0.4648,0.3835,0.3834,0.5869,0.6334,0.5977
MHA-16 (independent_context),0.6371,0.4089,0.3724,0.3731,0.5707,0.6371,0.5851
MHA-32 (independent_context),0.6436,0.4205,0.3802,0.3781,0.5744,0.6436,0.5945
MHA-64 (independent_context),0.6403,0.4518,0.3776,0.3830,0.5678,0.6403,0.5913
MHA-128 (independent_context),0.6391,0.4718,0.3981,0.4041,0.5776,0.6391,0.5996
Hierarchical (shared_context),0.6148,0.3535,0.3335,0.3261,0.5215,0.6148,0.5526
Hierarchical (independent_context),0.5973,0.3201,0.3422,0.3271,0.4940,0.5973,0.5371