In [1]:

import numpy as np

from tslearn.datasets import UCR_UEA_datasets
import torch
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from sklearn.linear_model import LogisticRegression
from torch.utils.data import TensorDataset, DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from uni2ts.model.moirai import MoiraiModule
import torch.nn as nn
import torch.optim as optim
from sklearn.linear_model import RidgeClassifierCV
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
#import seaborn as sns

from encoder import MoiraiEncoder

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Utils

In [2]:
PATCH_SIZES = [8, 16, 32, 64]

SIZE = "small"
DEVICE = "cuda"
NUM_VARS = 6

DO_MASK = True
KEEP_MASK_EMBEDDING = False

In [3]:
def preprocess_data(
    data: np.ndarray,
    *,
    device: str | torch.device = "cpu",
    dtype: torch.dtype = torch.float32,
):
    """
    data: np.ndarray of shape (N, T, V) = (n_individual, time, variate)
    Assumes NO missing values and NO padding in the raw data.
    """

    if not isinstance(data, np.ndarray):
        raise TypeError("data must be a numpy.ndarray")
    if data.ndim != 3:
        raise ValueError(f"Expected shape (N,T,V), got {data.shape}")

    N, T, V = data.shape

    # (N,T,V)
    past_target = torch.as_tensor(data, dtype=dtype, device=device)

    # observed mask: (N,T,V) all True no missing values
    past_observed_target = torch.ones((N, T, V), dtype=torch.bool, device=device)

    # padding mask: (N,T) all if no padding
    past_is_pad = torch.zeros((N, T), dtype=torch.bool, device=device)

    return past_target, past_observed_target, past_is_pad

In [4]:
def apply_pooling_pt(Z_tensor, method, num_vars=NUM_VARS):
    N, S, F = Z_tensor.shape
    P = S // num_vars # Calcul automatique du nombre de patches par variable
    
    # On reshape le tenseur pour séparer les Variables et les Patches
    # Forme résultante : (Batch, Variables, Patches, Features)
    Z_reshaped = Z_tensor.view(N, num_vars, P, F)
    
    # Basique et Global
    if method == "flatten":
        return Z_tensor.reshape(N, -1)
        
    elif method == "global_mean":
        return Z_tensor.mean(dim=1)
        
    elif method == "global_max":
        return Z_tensor.max(dim=1).values
        
    elif method == "global_min":
        return Z_tensor.min(dim=1).values
    
    elif method == "global_mean_max_min":
        return torch.cat([
            Z_tensor.mean(dim=1),
            Z_tensor.max(dim=1).values,
            Z_tensor.min(dim=1).values
        ], dim=1)

    # Pooling sur les Patches (on garde les variables distinctes) ---
    # Réduction sur la dimension 2 (Patches). Résultat : (N, num_vars, F), puis on aplatit
    elif method == "mean_over_patches":
        return Z_reshaped.mean(dim=2).reshape(N, -1)
        
    elif method == "max_over_patches":
        return Z_reshaped.max(dim=2).values.reshape(N, -1)
        
    elif method == "min_over_patches":
        return Z_reshaped.min(dim=2).values.reshape(N, -1)
        
    elif method == "mean_max_min_over_patches":
        p_mean = Z_reshaped.mean(dim=2).reshape(N, -1)
        p_max  = Z_reshaped.max(dim=2).values.reshape(N, -1)
        p_min  = Z_reshaped.min(dim=2).values.reshape(N, -1)
        return torch.cat([p_mean, p_max, p_min], dim=1)

    # Pooling sur les Variables (on synchronise les patches entre variables) ---
    # Réduction sur la dimension 1 (Variables). Résultat : (N, P, F), puis on aplatit
    elif method == "mean_over_variables":
        return Z_reshaped.mean(dim=1).reshape(N, -1)
        
    elif method == "max_over_variables":
        return Z_reshaped.max(dim=1).values.reshape(N, -1)
        
    elif method == "min_over_variables":
        return Z_reshaped.min(dim=1).values.reshape(N, -1)
        
    elif method == "mean_max_min_over_variables":
        v_mean = Z_reshaped.mean(dim=1).reshape(N, -1)
        v_max  = Z_reshaped.max(dim=1).values.reshape(N, -1)
        v_min  = Z_reshaped.min(dim=1).values.reshape(N, -1)
        return torch.cat([v_mean, v_max, v_min], dim=1)

    else:
        raise ValueError(f"Method {method} unknow")

pooling_methods = [
    "flatten", 
    "global_mean", "global_max", "global_min", "global_mean_max_min",
    "mean_over_patches", "max_over_patches", "min_over_patches", "mean_max_min_over_patches",
    "mean_over_variables", "max_over_variables", "min_over_variables", "mean_max_min_over_variables"
]

In [5]:
alphas_to_test = [0.1,1,10,30,100,300,1000,10000]

models = {
    'Ridge': RidgeClassifierCV(alphas=alphas_to_test, cv=3),
    'RandomForest': RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
}

# Data

Import

In [6]:
ds = UCR_UEA_datasets()
X_train, y_train, X_test, y_test = ds.load_dataset("LSST")

n_classes = len(set(y_train))
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

y_train_tensor = torch.tensor(y_train, dtype=torch.long, device=DEVICE)
y_test_tensor = torch.tensor(y_test, dtype=torch.long, device=DEVICE)

NUM_CLASSES = len(torch.unique(y_train_tensor))

Prepare data

In [7]:
X_train_target_tensor, X_train_is_target_observed, X_train_is_target_padded = (
    preprocess_data(X_train, device=DEVICE)
)

X_test_target_tensor, X_test_is_target_observed, X_test_is_target_padded = (
    preprocess_data(X_test, device=DEVICE)
)
y_train_tensor = torch.tensor(y_train, dtype=torch.long, device=DEVICE)
y_test_tensor = torch.tensor(y_test, dtype=torch.long, device=DEVICE)

num_classes = len(torch.unique(y_train_tensor))
NUM_VARS = 6

print(X_train_target_tensor.shape)
print(X_train_is_target_observed.shape)
print(X_train_is_target_padded.shape)

torch.Size([2459, 36, 6])
torch.Size([2459, 36, 6])
torch.Size([2459, 36])

Creat Z_train and Z_test for each patch size

In [8]:
Z_train_patch = {}
Z_test_patch = {}
for patch in PATCH_SIZES:
    
    # 1. Définir les paramètres et l'encodeur pour la taille de patch actuelle
    MODEL_PARAMS = {
        "patch_size": patch,
        "num_samples": 100,
        "target_dim": 6,
        "feat_dynamic_real_dim": 0,
        "past_feat_dynamic_real_dim": 0,
    }
    if DO_MASK == True:
        prediction_length = patch
    else:
        prediction_length = 0
    encoder = MoiraiEncoder(
        module=MoiraiModule.from_pretrained(f"Salesforce/moirai-1.1-R-{SIZE}"),
        prediction_length=prediction_length,
        context_length=36,
        **MODEL_PARAMS,
    )
    encoder.eval()
    encoder.to(DEVICE)
    
    # 2. Extraire les embeddings (Z_train et Z_test)
    with torch.no_grad():
        Z_train = encoder(
            past_target=X_train_target_tensor,
            past_observed_target=X_train_is_target_observed,
            past_is_pad=X_train_is_target_padded,
        )
        Z_test = encoder(
            past_target=X_test_target_tensor,
            past_observed_target=X_test_is_target_observed,
            past_is_pad=X_test_is_target_padded,
        )
        
    if DO_MASK and not KEEP_MASK_EMBEDDING:
        N, S, F = Z_train.shape
        P = S // NUM_VARS  # Nombre de patchs par variable (Contexte + 1 Masque)
        
        # On reshape pour séparer les variables et les patchs : (Batch, 6 vars, Patchs, Features)
        Z_train_reshaped = Z_train.view(N, NUM_VARS, P, F)
        Z_test_reshaped = Z_test.view(Z_test.shape[0], NUM_VARS, P, F) # Attention à bien récupérer N_test = Z_test.shape[0]
        
        # On slice pour enlever le dernier patch (:-1) sur la dimension des patchs (dim=2)
        Z_train_no_mask = Z_train_reshaped[:, :, :-1, :]
        Z_test_no_mask = Z_test_reshaped[:, :, :-1, :]
        
        # On remet sous la forme attendue (Batch, Séquence_sans_masques, Features)
        Z_train = Z_train_no_mask.reshape(N, -1, F)
        Z_test = Z_test_no_mask.reshape(Z_test.shape[0], -1, F)



    Z_train_patch[patch] = Z_train
    Z_test_patch[patch] = Z_test

In [9]:

print(f"{'Patch Size':<12} | {'Train Shape':<25} | {'Test Shape':<25}")
for patch in PATCH_SIZES:
    train_tensor = Z_train_patch[patch]
    test_tensor = Z_test_patch[patch]
    print(f"{patch:<12} | {str(list(train_tensor.shape)):<25} | {str(list(test_tensor.shape)):<25}")

Patch Size   | Train Shape               | Test Shape
8            | [2459, 30, 384]           | [2466, 30, 384]
16           | [2459, 18, 384]           | [2466, 18, 384]
32           | [2459, 12, 384]           | [2466, 12, 384]
64           | [2459, 6, 384]            | [2466, 6, 384]

# Basic pooling with logistic regression and random forest

## Single patch size pooling

We started by applying simple pooling techniques (max, min, or mean) and comparing their performance across various patch sizes. Specifically, we evaluated whether to apply this pooling globally across all patches, locally within a single series, or across corresponding patches from all series.

### Training

We creat a dataframe to stock the results and we fill it

In [10]:
results_dfs = {
    model_name: pd.DataFrame(index=pooling_methods, columns=PATCH_SIZES)
    for model_name in models.keys()
}
for df in results_dfs.values():
    df.index.name = "Pooling \\ Patch"

We train

In [11]:
for patch in PATCH_SIZES:
    Z_train = Z_train_patch[patch].to(DEVICE)
    Z_test = Z_test_patch[patch].to(DEVICE)
    
    for pool in pooling_methods:
        X_train_pool = apply_pooling_pt(Z_train, pool).cpu().numpy()
        X_test_pool = apply_pooling_pt(Z_test, pool).cpu().numpy()

        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train_pool)
        X_test_scaled = scaler.transform(X_test_pool)
        
        for model_name, clf in models.items():
            clf.fit(X_train_scaled, y_train)
            
            y_pred = clf.predict(X_test_scaled)
            acc = accuracy_score(y_test, y_pred)
            
            results_dfs[model_name].loc[pool, patch] = round(acc, 3)

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.59159e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.567e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.59439e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.62058e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.49583e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.50158e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.79836e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.35658e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.35915e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.26701e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.03765e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.03389e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.12658e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.45604e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.30892e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.488e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

### Results

In [12]:
for model_name, df in results_dfs.items():
    print(f"RÉSULTATS POUR : {model_name.upper()}")
    display(df.astype(float))
    
    best_acc = df.max().max()
    best_pool, best_patch = df.astype(float).stack().idxmax()
    print(f"Meilleure combinaison = Patch: {best_patch} | Pooling: '{best_pool}' | Acc: {best_acc:.3f}\n")

RÉSULTATS POUR : RIDGE

                                8      16     32     64
Pooling \ Patch
flatten                      0.600  0.624  0.607  0.618
global_mean                  0.574  0.592  0.579  0.587
global_max                   0.543  0.553  0.532  0.562
global_min                   0.545  0.546  0.532  0.557
global_mean_max_min          0.569  0.575  0.554  0.581
mean_over_patches            0.604  0.616  0.603  0.618
max_over_patches             0.589  0.609  0.595  0.618
min_over_patches             0.591  0.599  0.599  0.618
mean_max_min_over_patches    0.607  0.632  0.612  0.623
mean_over_variables          0.580  0.596  0.563  0.587
max_over_variables           0.567  0.565  0.545  0.562
min_over_variables           0.554  0.562  0.543  0.557
mean_max_min_over_variables  0.596  0.594  0.560  0.581

Meilleure combinaison = Patch: 16 | Pooling: 'mean_max_min_over_patches' | Acc: 0.632

RÉSULTATS POUR : RANDOMFOREST

                                8      16     32     64
Pooling \ Patch
flatten                      0.568  0.553  0.539  0.597
global_mean                  0.569  0.581  0.551  0.568
global_max                   0.531  0.506  0.502  0.558
global_min                   0.520  0.525  0.508  0.564
global_mean_max_min          0.566  0.558  0.535  0.570
mean_over_patches            0.584  0.568  0.559  0.597
max_over_patches             0.561  0.558  0.554  0.597
min_over_patches             0.561  0.555  0.554  0.597
mean_max_min_over_patches    0.583  0.571  0.556  0.594
mean_over_variables          0.539  0.548  0.528  0.568
max_over_variables           0.529  0.513  0.503  0.558
min_over_variables           0.516  0.521  0.498  0.564
mean_max_min_over_variables  0.543  0.544  0.524  0.570

Meilleure combinaison = Patch: 64 | Pooling: 'flatten' | Acc: 0.597

df_ridge_plot = df_results_ridge.astype(float)
df_rf_plot = df_results_rf.astype(float)


fig, axes = plt.subplots(1, 2, figsize=(20, 10), sharey=True)

cmap = "YlGnBu"

sns.heatmap(df_ridge_plot, 
            annot=True,
            fmt=".3f",
            cmap=cmap,
            linewidths=0.5,
            ax=axes[0],
            cbar_kws={'label': 'Accuracy'})
axes[0].set_title("Single Patch Pooling - Accuracy (Ridge)", fontsize=16, fontweight='bold', pad=15)
axes[0].set_xlabel("Patch Size", fontsize=14)
axes[0].set_ylabel("Pooling Method", fontsize=14)
axes[0].tick_params(axis='both', which='major', labelsize=12)

sns.heatmap(df_rf_plot, 
            annot=True, 
            fmt=".3f", 
            cmap=cmap, 
            linewidths=0.5, 
            ax=axes[1], 
            cbar_kws={'label': 'Accuracy'})
axes[1].set_title("Single Patch Pooling - Accuracy (Random Forest)", fontsize=16, fontweight='bold', pad=15)
axes[1].set_xlabel("Patch Size", fontsize=14)
axes[1].tick_params(axis='both', which='major', labelsize=12)

plt.tight_layout()

plt.show()

Pooling over patches rather than series produces the highest accuracy.

## Multi Patch pooling

### Training

In [ ]:
df_multiscale_results = pd.DataFrame(index=pooling_methods, columns=models.keys())
df_multiscale_results.index.name = "Pooling Method"

for pool in pooling_methods:
    X_train_multi = []
    X_test_multi = []
    
    for patch in PATCH_SIZES:
        Z_train = Z_train_patch[patch].to(DEVICE)
        Z_test = Z_test_patch[patch].to(DEVICE)
        
        X_train_pool = apply_pooling_pt(Z_train, pool).cpu().numpy()
        X_test_pool = apply_pooling_pt(Z_test, pool).cpu().numpy()
        
        X_train_multi.append(X_train_pool)
        X_test_multi.append(X_test_pool)
        
    X_train_combined = np.concatenate(X_train_multi, axis=1)
    X_test_combined = np.concatenate(X_test_multi, axis=1)
    
    scaler = StandardScaler()
    X_train_combined_scaled = scaler.fit_transform(X_train_combined)
    X_test_combined_scaled = scaler.transform(X_test_combined)

    for model_name, clf in models.items():
        clf.fit(X_train_combined_scaled, y_train)
        
        y_pred = clf.predict(X_test_combined_scaled)
        acc = accuracy_score(y_test, y_pred)
        
        df_multiscale_results.loc[pool, model_name] = round(acc, 3)

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.92258e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.96062e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.9049e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:228: LinAlgWarning: Ill-conditioned matrix (rcond=3.48337e-08): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:228: LinAlgWarning: Ill-conditioned matrix (rcond=4.25069e-08): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:228: LinAlgWarning: Ill-conditioned matrix (rcond=2.95744e-08): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

### Results

In [ ]:
display(df_multiscale_results.astype(float))

best_acc = df_multiscale_results.max().max()
best_pool = df_multiscale_results.max(axis=1).idxmax()
best_model = df_multiscale_results.max(axis=0).idxmax()

print("MEILLEURE COMBINAISON MULTI-ÉCHELLE :")
print(f"Modèle : '{best_model}' | Pooling : '{best_pool}'")
print(f"Précision maximale : {best_acc:.3f}")

                             Ridge  RandomForest
Pooling Method
flatten                      0.646         0.559
global_mean                  0.622         0.589
global_max                   0.592         0.569
global_min                   0.588         0.562
global_mean_max_min          0.618         0.583
mean_over_patches            0.644         0.592
max_over_patches             0.648         0.570
min_over_patches             0.647         0.577
mean_max_min_over_patches    0.655         0.589
mean_over_variables          0.609         0.575
max_over_variables           0.606         0.563
min_over_variables           0.602         0.564
mean_max_min_over_variables  0.624         0.578

MEILLEURE COMBINAISON MULTI-ÉCHELLE :
Modèle : 'Ridge' | Pooling : 'mean_max_min_over_patches'
Précision maximale : 0.655

## Conclusion

pool over patch -> good
16 -> (max, mean, min) > flatten -> position not importante
multi patch -> good

# Advanced Pooling

## Attention Pooling

In [ ]:
class DynamicAttentionClassifier(nn.Module):
    def __init__(self, num_vars, num_classes, patches_counts, in_features=384, mode="global"):
        """
        patches_counts : liste du nombre de patchs par échelle (ex: [30, 18, 12, 6])
        mode : "global" (1), "per_scale" (4), "per_variable" (6), ou "per_both" (24)
        """
        super().__init__()
        self.num_vars = num_vars
        self.patches_counts = patches_counts
        self.num_scales = len(patches_counts)
        self.mode = mode
        
        if mode == "global":
            self.context = nn.Parameter(torch.randn(in_features) * 0.1)
            
        elif mode == "per_scale":
            self.context = nn.Parameter(torch.randn(self.num_scales, in_features) * 0.1)
            
        elif mode == "per_variable":
            self.context = nn.Parameter(torch.randn(self.num_vars, in_features) * 0.1)
            
        elif mode == "per_both":
            self.context = nn.Parameter(torch.randn(self.num_scales, self.num_vars, in_features) * 0.1)
            
            
        self.dropout = nn.Dropout(0.1)
        self.linear = nn.LazyLinear(num_classes)
        
    def forward(self, x):
        B = x.shape[0]
        F = x.shape[-1]
        
        split_sizes = [p * self.num_vars for p in self.patches_counts]
        x_splits = torch.split(x, split_sizes, dim=1)
        
        reshaped_splits = []
        for i, p in enumerate(self.patches_counts):
            reshaped_splits.append(x_splits[i].view(B, self.num_vars, p, F))
            
        if self.mode == "global":
            scores = torch.matmul(x, self.context)
            weights = torch.softmax(scores, dim=1).unsqueeze(-1)
            pooled = (weights * x).sum(dim=1)
            
        elif self.mode == "per_scale":
            pooled_list = []
            for i, xi in enumerate(reshaped_splits):
                xi_flat = xi.view(B, -1, F)
                scores = torch.matmul(xi_flat, self.context[i])
                weights = torch.softmax(scores, dim=1).unsqueeze(-1)
                pooled_list.append((weights * xi_flat).sum(dim=1))
            
            pooled = torch.cat(pooled_list, dim=1)
            
        elif self.mode == "per_variable":
            x_vars = torch.cat(reshaped_splits, dim=2)
            
            scores = (x_vars * self.context.view(1, self.num_vars, 1, F)).sum(dim=-1)
            weights = torch.softmax(scores, dim=2).unsqueeze(-1)
            pooled_vars = (weights * x_vars).sum(dim=2)
            pooled = pooled_vars.view(B, -1)
            
        elif self.mode == "per_both":
            pooled_list = []
            for i, xi in enumerate(reshaped_splits):
                scores = (xi * self.context[i].view(1, self.num_vars, 1, F)).sum(dim=-1)
                weights = torch.softmax(scores, dim=2).unsqueeze(-1)
                pooled_vars = (weights * xi).sum(dim=2)
                pooled_list.append(pooled_vars)
                
            pooled_all = torch.stack(pooled_list, dim=1)
            pooled = pooled_all.view(B, -1)
            
        return self.linear(self.dropout(pooled))

In [ ]:
patch_sizes = [8, 16, 32, 64]
NUM_VARS = 6

patches_counts = [Z_train_patch[p].shape[1] // NUM_VARS for p in patch_sizes]
print(f"Nomber of patch for each scale : {patches_counts}")

Z_train_concat = torch.cat([Z_train_patch[p].to(device) for p in patch_sizes], dim=1)
Z_test_concat  = torch.cat([Z_test_patch[p].to(device) for p in patch_sizes], dim=1)

print(f"Shape Z_train: {Z_train_concat.shape}")

Nomber of patch for each scale : [5, 3, 2, 1]

NameError: name 'device' is not defined

In [ ]:
BATCH_SIZE = 64
EPOCHS = 1000
LEARNING_RATE = 0.0001
EVAL_EVERY_N_EPOCHS = 10
PRINT_LOSS_EVERY = 5 
attention_modes = ['global', 'per_scale', 'per_variable', 'per_both']
df_results = pd.DataFrame(index=attention_modes, columns=["Test Accuracy"])
df_results.index.name = "Attention mode"

train_dataset = TensorDataset(Z_train_concat, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

mode = "global"

model = DynamicAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    patches_counts=patches_counts, 
    mode=mode
).to(device)

_ = model(Z_train_concat[:2]) # Dummy pass for LazyLinear

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss()

for epoch in range(EPOCHS):
    model.train()
    running_loss = 0.0
    
    for batch_z, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_z)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item() * batch_z.size(0)
        
    epoch_loss = running_loss / len(train_loader.dataset)
    

    if (epoch + 1) == 1 or (epoch + 1) % PRINT_LOSS_EVERY == 0:
        print(f"Epoch [{epoch+1:3d}/{EPOCHS}] | Train Loss : {epoch_loss:.4f}", end="")
        
        if (epoch + 1) % EVAL_EVERY_N_EPOCHS == 0:
            model.eval()
            with torch.no_grad():
                test_outputs = model(Z_test_concat)
                _, predicted = torch.max(test_outputs.data, 1)
                acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
            print(f" | Test Acc : {acc:.4f}")
        else:
            print() 
            
model.eval()
with torch.no_grad():
    test_outputs = model(Z_test_concat)
    _, predicted = torch.max(test_outputs.data, 1)
    final_acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
    
df_results.loc[mode, "Test Accuracy"] = round(final_acc, 3)

Epoch [  1/1000] | Train Loss : 2.5732
Epoch [  5/1000] | Train Loss : 2.2269
Epoch [ 10/1000] | Train Loss : 2.0220 | Test Acc : 0.3277
Epoch [ 15/1000] | Train Loss : 1.9158
Epoch [ 20/1000] | Train Loss : 1.8305 | Test Acc : 0.4205
Epoch [ 25/1000] | Train Loss : 1.7574
Epoch [ 30/1000] | Train Loss : 1.7009 | Test Acc : 0.4615
Epoch [ 35/1000] | Train Loss : 1.6577
Epoch [ 40/1000] | Train Loss : 1.6227 | Test Acc : 0.4911
Epoch [ 45/1000] | Train Loss : 1.5930
Epoch [ 50/1000] | Train Loss : 1.5653 | Test Acc : 0.5085
Epoch [ 55/1000] | Train Loss : 1.5364
Epoch [ 60/1000] | Train Loss : 1.5186 | Test Acc : 0.5207
Epoch [ 65/1000] | Train Loss : 1.5015
Epoch [ 70/1000] | Train Loss : 1.4811 | Test Acc : 0.5304
Epoch [ 75/1000] | Train Loss : 1.4629
Epoch [ 80/1000] | Train Loss : 1.4538 | Test Acc : 0.5381
Epoch [ 85/1000] | Train Loss : 1.4439
Epoch [ 90/1000] | Train Loss : 1.4248 | Test Acc : 0.5430
Epoch [ 95/1000] | Train Loss : 1.4187
Epoch [100/1000] | Train Loss : 1.4060 | Test Acc : 0.5470
Epoch [105/1000] | Train Loss : 1.3967
Epoch [110/1000] | Train Loss : 1.3919 | Test Acc : 0.5515
Epoch [115/1000] | Train Loss : 1.3751
Epoch [120/1000] | Train Loss : 1.3707 | Test Acc : 0.5539
Epoch [125/1000] | Train Loss : 1.3699
Epoch [130/1000] | Train Loss : 1.3519 | Test Acc : 0.5552
Epoch [135/1000] | Train Loss : 1.3464
Epoch [140/1000] | Train Loss : 1.3426 | Test Acc : 0.5596
Epoch [145/1000] | Train Loss : 1.3346
Epoch [150/1000] | Train Loss : 1.3272 | Test Acc : 0.5637
Epoch [155/1000] | Train Loss : 1.3255
Epoch [160/1000] | Train Loss : 1.3126 | Test Acc : 0.5673
Epoch [165/1000] | Train Loss : 1.3149
Epoch [170/1000] | Train Loss : 1.3061 | Test Acc : 0.5677
Epoch [175/1000] | Train Loss : 1.3045
Epoch [180/1000] | Train Loss : 1.2959 | Test Acc : 0.5689
Epoch [185/1000] | Train Loss : 1.2917
Epoch [190/1000] | Train Loss : 1.2906 | Test Acc : 0.5710
Epoch [195/1000] | Train Loss : 1.2845
Epoch [200/1000] | Train Loss : 1.2861 | Test Acc : 0.5722
Epoch [205/1000] | Train Loss : 1.2746
Epoch [210/1000] | Train Loss : 1.2697 | Test Acc : 0.5726
Epoch [215/1000] | Train Loss : 1.2715
Epoch [220/1000] | Train Loss : 1.2637 | Test Acc : 0.5742
Epoch [225/1000] | Train Loss : 1.2602
Epoch [230/1000] | Train Loss : 1.2496 | Test Acc : 0.5775
Epoch [235/1000] | Train Loss : 1.2525
Epoch [240/1000] | Train Loss : 1.2501 | Test Acc : 0.5783
Epoch [245/1000] | Train Loss : 1.2454
Epoch [250/1000] | Train Loss : 1.2399 | Test Acc : 0.5807
Epoch [255/1000] | Train Loss : 1.2398
Epoch [260/1000] | Train Loss : 1.2350 | Test Acc : 0.5811
Epoch [265/1000] | Train Loss : 1.2343
Epoch [270/1000] | Train Loss : 1.2293 | Test Acc : 0.5811
Epoch [275/1000] | Train Loss : 1.2260
Epoch [280/1000] | Train Loss : 1.2210 | Test Acc : 0.5823
Epoch [285/1000] | Train Loss : 1.2202
Epoch [290/1000] | Train Loss : 1.2162 | Test Acc : 0.5831
Epoch [295/1000] | Train Loss : 1.2131
Epoch [300/1000] | Train Loss : 1.2104 | Test Acc : 0.5848
Epoch [305/1000] | Train Loss : 1.2110
Epoch [310/1000] | Train Loss : 1.2128 | Test Acc : 0.5843
Epoch [315/1000] | Train Loss : 1.2102
Epoch [320/1000] | Train Loss : 1.2019 | Test Acc : 0.5835
Epoch [325/1000] | Train Loss : 1.2001
Epoch [330/1000] | Train Loss : 1.2016 | Test Acc : 0.5843
Epoch [335/1000] | Train Loss : 1.1917
Epoch [340/1000] | Train Loss : 1.1983 | Test Acc : 0.5852
Epoch [345/1000] | Train Loss : 1.1957
Epoch [350/1000] | Train Loss : 1.1886 | Test Acc : 0.5864
Epoch [355/1000] | Train Loss : 1.1901
Epoch [360/1000] | Train Loss : 1.1794 | Test Acc : 0.5868
Epoch [365/1000] | Train Loss : 1.1879
Epoch [370/1000] | Train Loss : 1.1867 | Test Acc : 0.5872
Epoch [375/1000] | Train Loss : 1.1760
Epoch [380/1000] | Train Loss : 1.1837 | Test Acc : 0.5884
Epoch [385/1000] | Train Loss : 1.1797
Epoch [390/1000] | Train Loss : 1.1750 | Test Acc : 0.5868
Epoch [395/1000] | Train Loss : 1.1730
Epoch [400/1000] | Train Loss : 1.1734 | Test Acc : 0.5884
Epoch [405/1000] | Train Loss : 1.1782
Epoch [410/1000] | Train Loss : 1.1706 | Test Acc : 0.5880
Epoch [415/1000] | Train Loss : 1.1679
Epoch [420/1000] | Train Loss : 1.1676 | Test Acc : 0.5884
Epoch [425/1000] | Train Loss : 1.1639
Epoch [430/1000] | Train Loss : 1.1601 | Test Acc : 0.5872
Epoch [435/1000] | Train Loss : 1.1611
Epoch [440/1000] | Train Loss : 1.1568 | Test Acc : 0.5880
Epoch [445/1000] | Train Loss : 1.1586
Epoch [450/1000] | Train Loss : 1.1538 | Test Acc : 0.5884
Epoch [455/1000] | Train Loss : 1.1527
Epoch [460/1000] | Train Loss : 1.1502 | Test Acc : 0.5884
Epoch [465/1000] | Train Loss : 1.1568
Epoch [470/1000] | Train Loss : 1.1416 | Test Acc : 0.5880
Epoch [475/1000] | Train Loss : 1.1444
Epoch [480/1000] | Train Loss : 1.1476 | Test Acc : 0.5884
Epoch [485/1000] | Train Loss : 1.1436
Epoch [490/1000] | Train Loss : 1.1434 | Test Acc : 0.5888
Epoch [495/1000] | Train Loss : 1.1411
Epoch [500/1000] | Train Loss : 1.1397 | Test Acc : 0.5888
Epoch [505/1000] | Train Loss : 1.1455
Epoch [510/1000] | Train Loss : 1.1366 | Test Acc : 0.5888
Epoch [515/1000] | Train Loss : 1.1376
Epoch [520/1000] | Train Loss : 1.1381 | Test Acc : 0.5904
Epoch [525/1000] | Train Loss : 1.1294
Epoch [530/1000] | Train Loss : 1.1297 | Test Acc : 0.5904
Epoch [535/1000] | Train Loss : 1.1259
Epoch [540/1000] | Train Loss : 1.1285 | Test Acc : 0.5916
Epoch [545/1000] | Train Loss : 1.1238
Epoch [550/1000] | Train Loss : 1.1252 | Test Acc : 0.5916
Epoch [555/1000] | Train Loss : 1.1226
Epoch [560/1000] | Train Loss : 1.1265 | Test Acc : 0.5929
Epoch [565/1000] | Train Loss : 1.1212
Epoch [570/1000] | Train Loss : 1.1239 | Test Acc : 0.5933
Epoch [575/1000] | Train Loss : 1.1213
Epoch [580/1000] | Train Loss : 1.1201 | Test Acc : 0.5933
Epoch [585/1000] | Train Loss : 1.1157
Epoch [590/1000] | Train Loss : 1.1130 | Test Acc : 0.5945
Epoch [595/1000] | Train Loss : 1.1199
Epoch [600/1000] | Train Loss : 1.1113 | Test Acc : 0.5937
Epoch [605/1000] | Train Loss : 1.1161
Epoch [610/1000] | Train Loss : 1.1167 | Test Acc : 0.5953
Epoch [615/1000] | Train Loss : 1.1116
Epoch [620/1000] | Train Loss : 1.1035 | Test Acc : 0.5933
Epoch [625/1000] | Train Loss : 1.1089
Epoch [630/1000] | Train Loss : 1.1115 | Test Acc : 0.5945
Epoch [635/1000] | Train Loss : 1.1066
Epoch [640/1000] | Train Loss : 1.1072 | Test Acc : 0.5941
Epoch [645/1000] | Train Loss : 1.1093
Epoch [650/1000] | Train Loss : 1.0993 | Test Acc : 0.5941
Epoch [655/1000] | Train Loss : 1.1004
Epoch [660/1000] | Train Loss : 1.1002 | Test Acc : 0.5941
Epoch [665/1000] | Train Loss : 1.1016
Epoch [670/1000] | Train Loss : 1.0974 | Test Acc : 0.5937
Epoch [675/1000] | Train Loss : 1.1011
Epoch [680/1000] | Train Loss : 1.0994 | Test Acc : 0.5937
Epoch [685/1000] | Train Loss : 1.0984
Epoch [690/1000] | Train Loss : 1.0943 | Test Acc : 0.5941
Epoch [695/1000] | Train Loss : 1.0976
Epoch [700/1000] | Train Loss : 1.0888 | Test Acc : 0.5933
Epoch [705/1000] | Train Loss : 1.0861
Epoch [710/1000] | Train Loss : 1.0850 | Test Acc : 0.5941
Epoch [715/1000] | Train Loss : 1.0916
Epoch [720/1000] | Train Loss : 1.0807 | Test Acc : 0.5937
Epoch [725/1000] | Train Loss : 1.0796
Epoch [730/1000] | Train Loss : 1.0948 | Test Acc : 0.5929
Epoch [735/1000] | Train Loss : 1.0856
Epoch [740/1000] | Train Loss : 1.0884 | Test Acc : 0.5953
Epoch [745/1000] | Train Loss : 1.0846
Epoch [750/1000] | Train Loss : 1.0868 | Test Acc : 0.5945
Epoch [755/1000] | Train Loss : 1.0855
Epoch [760/1000] | Train Loss : 1.0789 | Test Acc : 0.5929
Epoch [765/1000] | Train Loss : 1.0821
Epoch [770/1000] | Train Loss : 1.0796 | Test Acc : 0.5916
Epoch [775/1000] | Train Loss : 1.0751
Epoch [780/1000] | Train Loss : 1.0761 | Test Acc : 0.5945
Epoch [785/1000] | Train Loss : 1.0805
Epoch [790/1000] | Train Loss : 1.0741 | Test Acc : 0.5937
Epoch [795/1000] | Train Loss : 1.0741
Epoch [800/1000] | Train Loss : 1.0694 | Test Acc : 0.5933
Epoch [805/1000] | Train Loss : 1.0725
Epoch [810/1000] | Train Loss : 1.0758 | Test Acc : 0.5921
Epoch [815/1000] | Train Loss : 1.0677
Epoch [820/1000] | Train Loss : 1.0705 | Test Acc : 0.5933
Epoch [825/1000] | Train Loss : 1.0682
Epoch [830/1000] | Train Loss : 1.0662 | Test Acc : 0.5925
Epoch [835/1000] | Train Loss : 1.0640
Epoch [840/1000] | Train Loss : 1.0662 | Test Acc : 0.5921
Epoch [845/1000] | Train Loss : 1.0663
Epoch [850/1000] | Train Loss : 1.0702 | Test Acc : 0.5912
Epoch [855/1000] | Train Loss : 1.0706
Epoch [860/1000] | Train Loss : 1.0677 | Test Acc : 0.5912
Epoch [865/1000] | Train Loss : 1.0691
Epoch [870/1000] | Train Loss : 1.0595 | Test Acc : 0.5916
Epoch [875/1000] | Train Loss : 1.0651
Epoch [880/1000] | Train Loss : 1.0642 | Test Acc : 0.5908
Epoch [885/1000] | Train Loss : 1.0568
Epoch [890/1000] | Train Loss : 1.0636 | Test Acc : 0.5912
Epoch [895/1000] | Train Loss : 1.0627
Epoch [900/1000] | Train Loss : 1.0581 | Test Acc : 0.5912
Epoch [905/1000] | Train Loss : 1.0561
Epoch [910/1000] | Train Loss : 1.0547 | Test Acc : 0.5908
Epoch [915/1000] | Train Loss : 1.0589
Epoch [920/1000] | Train Loss : 1.0478 | Test Acc : 0.5908
Epoch [925/1000] | Train Loss : 1.0513
Epoch [930/1000] | Train Loss : 1.0519 | Test Acc : 0.5912
Epoch [935/1000] | Train Loss : 1.0476
Epoch [940/1000] | Train Loss : 1.0532 | Test Acc : 0.5916
Epoch [945/1000] | Train Loss : 1.0560
Epoch [950/1000] | Train Loss : 1.0509 | Test Acc : 0.5912
Epoch [955/1000] | Train Loss : 1.0504
Epoch [960/1000] | Train Loss : 1.0503 | Test Acc : 0.5925
Epoch [965/1000] | Train Loss : 1.0538
Epoch [970/1000] | Train Loss : 1.0505 | Test Acc : 0.5925
Epoch [975/1000] | Train Loss : 1.0484
Epoch [980/1000] | Train Loss : 1.0488 | Test Acc : 0.5912
Epoch [985/1000] | Train Loss : 1.0494
Epoch [990/1000] | Train Loss : 1.0503 | Test Acc : 0.5904
Epoch [995/1000] | Train Loss : 1.0421
Epoch [1000/1000] | Train Loss : 1.0449 | Test Acc : 0.5916

In [ ]:
mode = "per_scale"

model = DynamicAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    patches_counts=patches_counts, 
    mode=mode
).to(device)

_ = model(Z_train_concat[:2]) # Dummy pass for LazyLinear

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss()

for epoch in range(EPOCHS):
    model.train()
    running_loss = 0.0
    
    for batch_z, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_z)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item() * batch_z.size(0)
        
    epoch_loss = running_loss / len(train_loader.dataset)
    

    if (epoch + 1) == 1 or (epoch + 1) % PRINT_LOSS_EVERY == 0:
        print(f"Epoch [{epoch+1:3d}/{EPOCHS}] | Train Loss : {epoch_loss:.4f}", end="")
        
        if (epoch + 1) % EVAL_EVERY_N_EPOCHS == 0:
            model.eval()
            with torch.no_grad():
                test_outputs = model(Z_test_concat)
                _, predicted = torch.max(test_outputs.data, 1)
                acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
            print(f" | Test Acc : {acc:.4f}")
        else:
            print() 
            
model.eval()
with torch.no_grad():
    test_outputs = model(Z_test_concat)
    _, predicted = torch.max(test_outputs.data, 1)
    final_acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
    
df_results.loc[mode, "Test Accuracy"] = round(final_acc, 3)

Epoch [  1/1000] | Train Loss : 2.4546
Epoch [  5/1000] | Train Loss : 1.8087
Epoch [ 10/1000] | Train Loss : 1.6112 | Test Acc : 0.5024
Epoch [ 15/1000] | Train Loss : 1.4951
Epoch [ 20/1000] | Train Loss : 1.4152 | Test Acc : 0.5539
Epoch [ 25/1000] | Train Loss : 1.3630
Epoch [ 30/1000] | Train Loss : 1.3198 | Test Acc : 0.5746
Epoch [ 35/1000] | Train Loss : 1.2825
Epoch [ 40/1000] | Train Loss : 1.2541 | Test Acc : 0.5835
Epoch [ 45/1000] | Train Loss : 1.2284
Epoch [ 50/1000] | Train Loss : 1.2058 | Test Acc : 0.5908
Epoch [ 55/1000] | Train Loss : 1.1881
Epoch [ 60/1000] | Train Loss : 1.1654 | Test Acc : 0.5929
Epoch [ 65/1000] | Train Loss : 1.1436
Epoch [ 70/1000] | Train Loss : 1.1357 | Test Acc : 0.5957
Epoch [ 75/1000] | Train Loss : 1.1182
Epoch [ 80/1000] | Train Loss : 1.1063 | Test Acc : 0.5985
Epoch [ 85/1000] | Train Loss : 1.0902
Epoch [ 90/1000] | Train Loss : 1.0761 | Test Acc : 0.5969
Epoch [ 95/1000] | Train Loss : 1.0624
Epoch [100/1000] | Train Loss : 1.0518 | Test Acc : 0.5949
Epoch [105/1000] | Train Loss : 1.0400
Epoch [110/1000] | Train Loss : 1.0334 | Test Acc : 0.5937
Epoch [115/1000] | Train Loss : 1.0180
Epoch [120/1000] | Train Loss : 1.0128 | Test Acc : 0.5941
Epoch [125/1000] | Train Loss : 1.0032
Epoch [130/1000] | Train Loss : 0.9901 | Test Acc : 0.5937
Epoch [135/1000] | Train Loss : 0.9807
Epoch [140/1000] | Train Loss : 0.9729 | Test Acc : 0.5945
Epoch [145/1000] | Train Loss : 0.9652
Epoch [150/1000] | Train Loss : 0.9560 | Test Acc : 0.5945
Epoch [155/1000] | Train Loss : 0.9515
Epoch [160/1000] | Train Loss : 0.9418 | Test Acc : 0.5965
Epoch [165/1000] | Train Loss : 0.9324
Epoch [170/1000] | Train Loss : 0.9216 | Test Acc : 0.5945
Epoch [175/1000] | Train Loss : 0.9244
Epoch [180/1000] | Train Loss : 0.9082 | Test Acc : 0.5945
Epoch [185/1000] | Train Loss : 0.9068
Epoch [190/1000] | Train Loss : 0.9019 | Test Acc : 0.5925
Epoch [195/1000] | Train Loss : 0.8913
Epoch [200/1000] | Train Loss : 0.8841 | Test Acc : 0.5945
Epoch [205/1000] | Train Loss : 0.8771
Epoch [210/1000] | Train Loss : 0.8687 | Test Acc : 0.5957
Epoch [215/1000] | Train Loss : 0.8716
Epoch [220/1000] | Train Loss : 0.8669 | Test Acc : 0.5969
Epoch [225/1000] | Train Loss : 0.8595
Epoch [230/1000] | Train Loss : 0.8482 | Test Acc : 0.5969
Epoch [235/1000] | Train Loss : 0.8468
Epoch [240/1000] | Train Loss : 0.8341 | Test Acc : 0.5981
Epoch [245/1000] | Train Loss : 0.8342
Epoch [250/1000] | Train Loss : 0.8217 | Test Acc : 0.5953
Epoch [255/1000] | Train Loss : 0.8221
Epoch [260/1000] | Train Loss : 0.8216 | Test Acc : 0.5949
Epoch [265/1000] | Train Loss : 0.8069
Epoch [270/1000] | Train Loss : 0.7985 | Test Acc : 0.5961
Epoch [275/1000] | Train Loss : 0.7948
Epoch [280/1000] | Train Loss : 0.7973 | Test Acc : 0.5941
Epoch [285/1000] | Train Loss : 0.7898
Epoch [290/1000] | Train Loss : 0.7854 | Test Acc : 0.5937
Epoch [295/1000] | Train Loss : 0.7858
Epoch [300/1000] | Train Loss : 0.7825 | Test Acc : 0.5921
Epoch [305/1000] | Train Loss : 0.7729
Epoch [310/1000] | Train Loss : 0.7643 | Test Acc : 0.5921
Epoch [315/1000] | Train Loss : 0.7666
Epoch [320/1000] | Train Loss : 0.7680 | Test Acc : 0.5900
Epoch [325/1000] | Train Loss : 0.7580
Epoch [330/1000] | Train Loss : 0.7476 | Test Acc : 0.5904
Epoch [335/1000] | Train Loss : 0.7538
Epoch [340/1000] | Train Loss : 0.7453 | Test Acc : 0.5921
Epoch [345/1000] | Train Loss : 0.7381
Epoch [350/1000] | Train Loss : 0.7340 | Test Acc : 0.5912
Epoch [355/1000] | Train Loss : 0.7259
Epoch [360/1000] | Train Loss : 0.7352 | Test Acc : 0.5900
Epoch [365/1000] | Train Loss : 0.7225
Epoch [370/1000] | Train Loss : 0.7200 | Test Acc : 0.5904
Epoch [375/1000] | Train Loss : 0.7186
Epoch [380/1000] | Train Loss : 0.7151 | Test Acc : 0.5908
Epoch [385/1000] | Train Loss : 0.7050
Epoch [390/1000] | Train Loss : 0.7083 | Test Acc : 0.5908
Epoch [395/1000] | Train Loss : 0.7134
Epoch [400/1000] | Train Loss : 0.7052 | Test Acc : 0.5912
Epoch [405/1000] | Train Loss : 0.6905
Epoch [410/1000] | Train Loss : 0.6957 | Test Acc : 0.5876
Epoch [415/1000] | Train Loss : 0.6862
Epoch [420/1000] | Train Loss : 0.6873 | Test Acc : 0.5880
Epoch [425/1000] | Train Loss : 0.6755
Epoch [430/1000] | Train Loss : 0.6768 | Test Acc : 0.5888
Epoch [435/1000] | Train Loss : 0.6842
Epoch [440/1000] | Train Loss : 0.6793 | Test Acc : 0.5864
Epoch [445/1000] | Train Loss : 0.6677
Epoch [450/1000] | Train Loss : 0.6700 | Test Acc : 0.5856
Epoch [455/1000] | Train Loss : 0.6636
Epoch [460/1000] | Train Loss : 0.6600 | Test Acc : 0.5843
Epoch [465/1000] | Train Loss : 0.6515
Epoch [470/1000] | Train Loss : 0.6581 | Test Acc : 0.5848
Epoch [475/1000] | Train Loss : 0.6603
Epoch [480/1000] | Train Loss : 0.6529 | Test Acc : 0.5839
Epoch [485/1000] | Train Loss : 0.6394
Epoch [490/1000] | Train Loss : 0.6484 | Test Acc : 0.5819
Epoch [495/1000] | Train Loss : 0.6387
Epoch [500/1000] | Train Loss : 0.6375 | Test Acc : 0.5827
Epoch [505/1000] | Train Loss : 0.6409
Epoch [510/1000] | Train Loss : 0.6372 | Test Acc : 0.5803
Epoch [515/1000] | Train Loss : 0.6302
Epoch [520/1000] | Train Loss : 0.6292 | Test Acc : 0.5783
Epoch [525/1000] | Train Loss : 0.6212
Epoch [530/1000] | Train Loss : 0.6298 | Test Acc : 0.5795
Epoch [535/1000] | Train Loss : 0.6168
Epoch [540/1000] | Train Loss : 0.6237 | Test Acc : 0.5787
Epoch [545/1000] | Train Loss : 0.6169
Epoch [550/1000] | Train Loss : 0.6139 | Test Acc : 0.5779
Epoch [555/1000] | Train Loss : 0.6201
Epoch [560/1000] | Train Loss : 0.6112 | Test Acc : 0.5791
Epoch [565/1000] | Train Loss : 0.6058
Epoch [570/1000] | Train Loss : 0.6051 | Test Acc : 0.5783
Epoch [575/1000] | Train Loss : 0.6060
Epoch [580/1000] | Train Loss : 0.6046 | Test Acc : 0.5775
Epoch [585/1000] | Train Loss : 0.5950
Epoch [590/1000] | Train Loss : 0.6008 | Test Acc : 0.5734
Epoch [595/1000] | Train Loss : 0.5887
Epoch [600/1000] | Train Loss : 0.6032 | Test Acc : 0.5758
Epoch [605/1000] | Train Loss : 0.5882
Epoch [610/1000] | Train Loss : 0.5863 | Test Acc : 0.5742
Epoch [615/1000] | Train Loss : 0.5859
Epoch [620/1000] | Train Loss : 0.5816 | Test Acc : 0.5754
Epoch [625/1000] | Train Loss : 0.5804
Epoch [630/1000] | Train Loss : 0.5840 | Test Acc : 0.5730
Epoch [635/1000] | Train Loss : 0.5763
Epoch [640/1000] | Train Loss : 0.5799 | Test Acc : 0.5714
Epoch [645/1000] | Train Loss : 0.5831
Epoch [650/1000] | Train Loss : 0.5729 | Test Acc : 0.5706
Epoch [655/1000] | Train Loss : 0.5725
Epoch [660/1000] | Train Loss : 0.5669 | Test Acc : 0.5665
Epoch [665/1000] | Train Loss : 0.5691
Epoch [670/1000] | Train Loss : 0.5638 | Test Acc : 0.5681
Epoch [675/1000] | Train Loss : 0.5585
Epoch [680/1000] | Train Loss : 0.5661 | Test Acc : 0.5669
Epoch [685/1000] | Train Loss : 0.5579
Epoch [690/1000] | Train Loss : 0.5523 | Test Acc : 0.5649
Epoch [695/1000] | Train Loss : 0.5518
Epoch [700/1000] | Train Loss : 0.5573 | Test Acc : 0.5669
Epoch [705/1000] | Train Loss : 0.5475
Epoch [710/1000] | Train Loss : 0.5473 | Test Acc : 0.5657
Epoch [715/1000] | Train Loss : 0.5440
Epoch [720/1000] | Train Loss : 0.5516 | Test Acc : 0.5633
Epoch [725/1000] | Train Loss : 0.5421
Epoch [730/1000] | Train Loss : 0.5444 | Test Acc : 0.5596
Epoch [735/1000] | Train Loss : 0.5410
Epoch [740/1000] | Train Loss : 0.5333 | Test Acc : 0.5588
Epoch [745/1000] | Train Loss : 0.5403
Epoch [750/1000] | Train Loss : 0.5347 | Test Acc : 0.5588
Epoch [755/1000] | Train Loss : 0.5382
Epoch [760/1000] | Train Loss : 0.5289 | Test Acc : 0.5592
Epoch [765/1000] | Train Loss : 0.5350
Epoch [770/1000] | Train Loss : 0.5212 | Test Acc : 0.5584
Epoch [775/1000] | Train Loss : 0.5266
Epoch [780/1000] | Train Loss : 0.5228 | Test Acc : 0.5572
Epoch [785/1000] | Train Loss : 0.5231
Epoch [790/1000] | Train Loss : 0.5159 | Test Acc : 0.5580
Epoch [795/1000] | Train Loss : 0.5199
Epoch [800/1000] | Train Loss : 0.5248 | Test Acc : 0.5588
Epoch [805/1000] | Train Loss : 0.5167
Epoch [810/1000] | Train Loss : 0.5126 | Test Acc : 0.5580
Epoch [815/1000] | Train Loss : 0.5180
Epoch [820/1000] | Train Loss : 0.5179 | Test Acc : 0.5572
Epoch [825/1000] | Train Loss : 0.5168
Epoch [830/1000] | Train Loss : 0.5119 | Test Acc : 0.5592
Epoch [835/1000] | Train Loss : 0.4931
Epoch [840/1000] | Train Loss : 0.5038 | Test Acc : 0.5576
Epoch [845/1000] | Train Loss : 0.5072
Epoch [850/1000] | Train Loss : 0.5035 | Test Acc : 0.5620
Epoch [855/1000] | Train Loss : 0.5021
Epoch [860/1000] | Train Loss : 0.5020 | Test Acc : 0.5608
Epoch [865/1000] | Train Loss : 0.5034
Epoch [870/1000] | Train Loss : 0.4999 | Test Acc : 0.5588
Epoch [875/1000] | Train Loss : 0.4966
Epoch [880/1000] | Train Loss : 0.5101 | Test Acc : 0.5576
Epoch [885/1000] | Train Loss : 0.4911
Epoch [890/1000] | Train Loss : 0.4946 | Test Acc : 0.5568
Epoch [895/1000] | Train Loss : 0.4898
Epoch [900/1000] | Train Loss : 0.4894 | Test Acc : 0.5584
Epoch [905/1000] | Train Loss : 0.4818
Epoch [910/1000] | Train Loss : 0.4815 | Test Acc : 0.5600
Epoch [915/1000] | Train Loss : 0.4940
Epoch [920/1000] | Train Loss : 0.4909 | Test Acc : 0.5564
Epoch [925/1000] | Train Loss : 0.4791
Epoch [930/1000] | Train Loss : 0.4746 | Test Acc : 0.5560
Epoch [935/1000] | Train Loss : 0.4787
Epoch [940/1000] | Train Loss : 0.4835 | Test Acc : 0.5576
Epoch [945/1000] | Train Loss : 0.4815
Epoch [950/1000] | Train Loss : 0.4714 | Test Acc : 0.5572
Epoch [955/1000] | Train Loss : 0.4742
Epoch [960/1000] | Train Loss : 0.4757 | Test Acc : 0.5588
Epoch [965/1000] | Train Loss : 0.4658
Epoch [970/1000] | Train Loss : 0.4601 | Test Acc : 0.5560
Epoch [975/1000] | Train Loss : 0.4662
Epoch [980/1000] | Train Loss : 0.4717 | Test Acc : 0.5576
Epoch [985/1000] | Train Loss : 0.4729
Epoch [990/1000] | Train Loss : 0.4790 | Test Acc : 0.5572
Epoch [995/1000] | Train Loss : 0.4682
Epoch [1000/1000] | Train Loss : 0.4683 | Test Acc : 0.5552

In [ ]:
mode = "per_variable"

model = DynamicAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    patches_counts=patches_counts, 
    mode=mode
).to(device)

_ = model(Z_train_concat[:2]) # Dummy pass for LazyLinear

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss()

for epoch in range(EPOCHS):
    model.train()
    running_loss = 0.0
    
    for batch_z, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_z)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item() * batch_z.size(0)
        
    epoch_loss = running_loss / len(train_loader.dataset)
    

    if (epoch + 1) == 1 or (epoch + 1) % PRINT_LOSS_EVERY == 0:
        print(f"Epoch [{epoch+1:3d}/{EPOCHS}] | Train Loss : {epoch_loss:.4f}", end="")
        
        if (epoch + 1) % EVAL_EVERY_N_EPOCHS == 0:
            model.eval()
            with torch.no_grad():
                test_outputs = model(Z_test_concat)
                _, predicted = torch.max(test_outputs.data, 1)
                acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
            print(f" | Test Acc : {acc:.4f}")
        else:
            print() 
            
model.eval()
with torch.no_grad():
    test_outputs = model(Z_test_concat)
    _, predicted = torch.max(test_outputs.data, 1)
    final_acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
    
df_results.loc[mode, "Test Accuracy"] = round(final_acc, 3)

Epoch [  1/1000] | Train Loss : 2.4016
Epoch [  5/1000] | Train Loss : 1.8149
Epoch [ 10/1000] | Train Loss : 1.5742 | Test Acc : 0.5134
Epoch [ 15/1000] | Train Loss : 1.4266
Epoch [ 20/1000] | Train Loss : 1.3243 | Test Acc : 0.5608
Epoch [ 25/1000] | Train Loss : 1.2464
Epoch [ 30/1000] | Train Loss : 1.1873 | Test Acc : 0.5864
Epoch [ 35/1000] | Train Loss : 1.1397
Epoch [ 40/1000] | Train Loss : 1.1004 | Test Acc : 0.5985
Epoch [ 45/1000] | Train Loss : 1.0611
Epoch [ 50/1000] | Train Loss : 1.0281 | Test Acc : 0.6099
Epoch [ 55/1000] | Train Loss : 0.9992
Epoch [ 60/1000] | Train Loss : 0.9723 | Test Acc : 0.6107
Epoch [ 65/1000] | Train Loss : 0.9433
Epoch [ 70/1000] | Train Loss : 0.9211 | Test Acc : 0.6119
Epoch [ 75/1000] | Train Loss : 0.9024
Epoch [ 80/1000] | Train Loss : 0.8755 | Test Acc : 0.6131
Epoch [ 85/1000] | Train Loss : 0.8564
Epoch [ 90/1000] | Train Loss : 0.8326 | Test Acc : 0.6156
Epoch [ 95/1000] | Train Loss : 0.8220
Epoch [100/1000] | Train Loss : 0.8044 | Test Acc : 0.6176
Epoch [105/1000] | Train Loss : 0.7864
Epoch [110/1000] | Train Loss : 0.7727 | Test Acc : 0.6127
Epoch [115/1000] | Train Loss : 0.7549
Epoch [120/1000] | Train Loss : 0.7345 | Test Acc : 0.6139
Epoch [125/1000] | Train Loss : 0.7306
Epoch [130/1000] | Train Loss : 0.7155 | Test Acc : 0.6148
Epoch [135/1000] | Train Loss : 0.7022
Epoch [140/1000] | Train Loss : 0.6915 | Test Acc : 0.6115
Epoch [145/1000] | Train Loss : 0.6783
Epoch [150/1000] | Train Loss : 0.6690 | Test Acc : 0.6103
Epoch [155/1000] | Train Loss : 0.6602
Epoch [160/1000] | Train Loss : 0.6536 | Test Acc : 0.6099
Epoch [165/1000] | Train Loss : 0.6347
Epoch [170/1000] | Train Loss : 0.6294 | Test Acc : 0.6087
Epoch [175/1000] | Train Loss : 0.6195
Epoch [180/1000] | Train Loss : 0.6032 | Test Acc : 0.6083
Epoch [185/1000] | Train Loss : 0.5963
Epoch [190/1000] | Train Loss : 0.5893 | Test Acc : 0.6062
Epoch [195/1000] | Train Loss : 0.5770
Epoch [200/1000] | Train Loss : 0.5720 | Test Acc : 0.6018
Epoch [205/1000] | Train Loss : 0.5628
Epoch [210/1000] | Train Loss : 0.5648 | Test Acc : 0.6038
Epoch [215/1000] | Train Loss : 0.5474
Epoch [220/1000] | Train Loss : 0.5319 | Test Acc : 0.6034
Epoch [225/1000] | Train Loss : 0.5310
Epoch [230/1000] | Train Loss : 0.5217 | Test Acc : 0.5985
Epoch [235/1000] | Train Loss : 0.5153
Epoch [240/1000] | Train Loss : 0.5126 | Test Acc : 0.5977
Epoch [245/1000] | Train Loss : 0.4998
Epoch [250/1000] | Train Loss : 0.4948 | Test Acc : 0.5965
Epoch [255/1000] | Train Loss : 0.4855
Epoch [260/1000] | Train Loss : 0.4735 | Test Acc : 0.5961
Epoch [265/1000] | Train Loss : 0.4768
Epoch [270/1000] | Train Loss : 0.4586 | Test Acc : 0.5953
Epoch [275/1000] | Train Loss : 0.4688
Epoch [280/1000] | Train Loss : 0.4541 | Test Acc : 0.5949
Epoch [285/1000] | Train Loss : 0.4461
Epoch [290/1000] | Train Loss : 0.4467 | Test Acc : 0.5912
Epoch [295/1000] | Train Loss : 0.4451
Epoch [300/1000] | Train Loss : 0.4355 | Test Acc : 0.5912
Epoch [305/1000] | Train Loss : 0.4272
Epoch [310/1000] | Train Loss : 0.4232 | Test Acc : 0.5896
Epoch [315/1000] | Train Loss : 0.4170
Epoch [320/1000] | Train Loss : 0.4139 | Test Acc : 0.5880
Epoch [325/1000] | Train Loss : 0.4091
Epoch [330/1000] | Train Loss : 0.4024 | Test Acc : 0.5884
Epoch [335/1000] | Train Loss : 0.4016
Epoch [340/1000] | Train Loss : 0.3913 | Test Acc : 0.5848
Epoch [345/1000] | Train Loss : 0.3905
Epoch [350/1000] | Train Loss : 0.3789 | Test Acc : 0.5848
Epoch [355/1000] | Train Loss : 0.3792
Epoch [360/1000] | Train Loss : 0.3786 | Test Acc : 0.5835
Epoch [365/1000] | Train Loss : 0.3690
Epoch [370/1000] | Train Loss : 0.3623 | Test Acc : 0.5835
Epoch [375/1000] | Train Loss : 0.3640
Epoch [380/1000] | Train Loss : 0.3628 | Test Acc : 0.5831
Epoch [385/1000] | Train Loss : 0.3549
Epoch [390/1000] | Train Loss : 0.3499 | Test Acc : 0.5819
Epoch [395/1000] | Train Loss : 0.3476
Epoch [400/1000] | Train Loss : 0.3401 | Test Acc : 0.5803
Epoch [405/1000] | Train Loss : 0.3401
Epoch [410/1000] | Train Loss : 0.3401 | Test Acc : 0.5787
Epoch [415/1000] | Train Loss : 0.3307
Epoch [420/1000] | Train Loss : 0.3260 | Test Acc : 0.5787
Epoch [425/1000] | Train Loss : 0.3253
Epoch [430/1000] | Train Loss : 0.3252 | Test Acc : 0.5775
Epoch [435/1000] | Train Loss : 0.3131
Epoch [440/1000] | Train Loss : 0.3158 | Test Acc : 0.5779
Epoch [445/1000] | Train Loss : 0.3081
Epoch [450/1000] | Train Loss : 0.3070 | Test Acc : 0.5742
Epoch [455/1000] | Train Loss : 0.3098
Epoch [460/1000] | Train Loss : 0.3026 | Test Acc : 0.5754
Epoch [465/1000] | Train Loss : 0.3024
Epoch [470/1000] | Train Loss : 0.2990 | Test Acc : 0.5718
Epoch [475/1000] | Train Loss : 0.2943
Epoch [480/1000] | Train Loss : 0.2968 | Test Acc : 0.5750
Epoch [485/1000] | Train Loss : 0.2918
Epoch [490/1000] | Train Loss : 0.2886 | Test Acc : 0.5746
Epoch [495/1000] | Train Loss : 0.2887
Epoch [500/1000] | Train Loss : 0.2786 | Test Acc : 0.5758
Epoch [505/1000] | Train Loss : 0.2694
Epoch [510/1000] | Train Loss : 0.2756 | Test Acc : 0.5706
Epoch [515/1000] | Train Loss : 0.2723
Epoch [520/1000] | Train Loss : 0.2674 | Test Acc : 0.5710
Epoch [525/1000] | Train Loss : 0.2722
Epoch [530/1000] | Train Loss : 0.2760 | Test Acc : 0.5697
Epoch [535/1000] | Train Loss : 0.2628
Epoch [540/1000] | Train Loss : 0.2624 | Test Acc : 0.5714
Epoch [545/1000] | Train Loss : 0.2604
Epoch [550/1000] | Train Loss : 0.2514 | Test Acc : 0.5722
Epoch [555/1000] | Train Loss : 0.2519
Epoch [560/1000] | Train Loss : 0.2498 | Test Acc : 0.5730
Epoch [565/1000] | Train Loss : 0.2541
Epoch [570/1000] | Train Loss : 0.2471 | Test Acc : 0.5730
Epoch [575/1000] | Train Loss : 0.2494
Epoch [580/1000] | Train Loss : 0.2431 | Test Acc : 0.5718
Epoch [585/1000] | Train Loss : 0.2418
Epoch [590/1000] | Train Loss : 0.2392 | Test Acc : 0.5734
Epoch [595/1000] | Train Loss : 0.2401
Epoch [600/1000] | Train Loss : 0.2321 | Test Acc : 0.5706
Epoch [605/1000] | Train Loss : 0.2331
Epoch [610/1000] | Train Loss : 0.2359 | Test Acc : 0.5697
Epoch [615/1000] | Train Loss : 0.2268
Epoch [620/1000] | Train Loss : 0.2231 | Test Acc : 0.5702
Epoch [625/1000] | Train Loss : 0.2236
Epoch [630/1000] | Train Loss : 0.2167 | Test Acc : 0.5710
Epoch [635/1000] | Train Loss : 0.2203
Epoch [640/1000] | Train Loss : 0.2184 | Test Acc : 0.5702
Epoch [645/1000] | Train Loss : 0.2187
Epoch [650/1000] | Train Loss : 0.2170 | Test Acc : 0.5693
Epoch [655/1000] | Train Loss : 0.2122
Epoch [660/1000] | Train Loss : 0.2115 | Test Acc : 0.5689
Epoch [665/1000] | Train Loss : 0.2061
Epoch [670/1000] | Train Loss : 0.2066 | Test Acc : 0.5685
Epoch [675/1000] | Train Loss : 0.2080
Epoch [680/1000] | Train Loss : 0.2044 | Test Acc : 0.5657
Epoch [685/1000] | Train Loss : 0.2010
Epoch [690/1000] | Train Loss : 0.2001 | Test Acc : 0.5689
Epoch [695/1000] | Train Loss : 0.2000
Epoch [700/1000] | Train Loss : 0.2014 | Test Acc : 0.5661
Epoch [705/1000] | Train Loss : 0.1975
Epoch [710/1000] | Train Loss : 0.2001 | Test Acc : 0.5661
Epoch [715/1000] | Train Loss : 0.1986
Epoch [720/1000] | Train Loss : 0.1933 | Test Acc : 0.5685
Epoch [725/1000] | Train Loss : 0.1853
Epoch [730/1000] | Train Loss : 0.1892 | Test Acc : 0.5620
Epoch [735/1000] | Train Loss : 0.1920
Epoch [740/1000] | Train Loss : 0.1908 | Test Acc : 0.5637
Epoch [745/1000] | Train Loss : 0.1908
Epoch [750/1000] | Train Loss : 0.1866 | Test Acc : 0.5641
Epoch [755/1000] | Train Loss : 0.1868
Epoch [760/1000] | Train Loss : 0.1767 | Test Acc : 0.5641
Epoch [765/1000] | Train Loss : 0.1807
Epoch [770/1000] | Train Loss : 0.1846 | Test Acc : 0.5649
Epoch [775/1000] | Train Loss : 0.1824
Epoch [780/1000] | Train Loss : 0.1843 | Test Acc : 0.5653
Epoch [785/1000] | Train Loss : 0.1760
Epoch [790/1000] | Train Loss : 0.1738 | Test Acc : 0.5657
Epoch [795/1000] | Train Loss : 0.1699
Epoch [800/1000] | Train Loss : 0.1753 | Test Acc : 0.5641
Epoch [805/1000] | Train Loss : 0.1686
Epoch [810/1000] | Train Loss : 0.1671 | Test Acc : 0.5616
Epoch [815/1000] | Train Loss : 0.1650
Epoch [820/1000] | Train Loss : 0.1665 | Test Acc : 0.5645
Epoch [825/1000] | Train Loss : 0.1695
Epoch [830/1000] | Train Loss : 0.1630 | Test Acc : 0.5661
Epoch [835/1000] | Train Loss : 0.1606
Epoch [840/1000] | Train Loss : 0.1640 | Test Acc : 0.5641
Epoch [845/1000] | Train Loss : 0.1557
Epoch [850/1000] | Train Loss : 0.1569 | Test Acc : 0.5649
Epoch [855/1000] | Train Loss : 0.1594
Epoch [860/1000] | Train Loss : 0.1555 | Test Acc : 0.5641
Epoch [865/1000] | Train Loss : 0.1513
Epoch [870/1000] | Train Loss : 0.1536 | Test Acc : 0.5641
Epoch [875/1000] | Train Loss : 0.1567
Epoch [880/1000] | Train Loss : 0.1514 | Test Acc : 0.5624
Epoch [885/1000] | Train Loss : 0.1573
Epoch [890/1000] | Train Loss : 0.1549 | Test Acc : 0.5629
Epoch [895/1000] | Train Loss : 0.1526
Epoch [900/1000] | Train Loss : 0.1480 | Test Acc : 0.5629
Epoch [905/1000] | Train Loss : 0.1478
Epoch [910/1000] | Train Loss : 0.1554 | Test Acc : 0.5604
Epoch [915/1000] | Train Loss : 0.1438
Epoch [920/1000] | Train Loss : 0.1427 | Test Acc : 0.5612
Epoch [925/1000] | Train Loss : 0.1403
Epoch [930/1000] | Train Loss : 0.1417 | Test Acc : 0.5612
Epoch [935/1000] | Train Loss : 0.1355
Epoch [940/1000] | Train Loss : 0.1415 | Test Acc : 0.5592
Epoch [945/1000] | Train Loss : 0.1454
Epoch [950/1000] | Train Loss : 0.1437 | Test Acc : 0.5592
Epoch [955/1000] | Train Loss : 0.1407
Epoch [960/1000] | Train Loss : 0.1386 | Test Acc : 0.5592
Epoch [965/1000] | Train Loss : 0.1400
Epoch [970/1000] | Train Loss : 0.1390 | Test Acc : 0.5568
Epoch [975/1000] | Train Loss : 0.1337
Epoch [980/1000] | Train Loss : 0.1376 | Test Acc : 0.5580
Epoch [985/1000] | Train Loss : 0.1361
Epoch [990/1000] | Train Loss : 0.1319 | Test Acc : 0.5584
Epoch [995/1000] | Train Loss : 0.1314
Epoch [1000/1000] | Train Loss : 0.1337 | Test Acc : 0.5580

In [ ]:
mode = "per_both"

model = DynamicAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    patches_counts=patches_counts, 
    mode=mode
).to(device)

_ = model(Z_train_concat[:2]) # Dummy pass for LazyLinear

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss()

for epoch in range(EPOCHS):
    model.train()
    running_loss = 0.0
    
    for batch_z, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_z)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item() * batch_z.size(0)
        
    epoch_loss = running_loss / len(train_loader.dataset)
    

    if (epoch + 1) == 1 or (epoch + 1) % PRINT_LOSS_EVERY == 0:
        print(f"Epoch [{epoch+1:3d}/{EPOCHS}] | Train Loss : {epoch_loss:.4f}", end="")
        
        if (epoch + 1) % EVAL_EVERY_N_EPOCHS == 0:
            model.eval()
            with torch.no_grad():
                test_outputs = model(Z_test_concat)
                _, predicted = torch.max(test_outputs.data, 1)
                acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
            print(f" | Test Acc : {acc:.4f}")
        else:
            print() 
            
model.eval()
with torch.no_grad():
    test_outputs = model(Z_test_concat)
    _, predicted = torch.max(test_outputs.data, 1)
    final_acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
    
df_results.loc[mode, "Test Accuracy"] = round(final_acc, 3)

Epoch [  1/1000] | Train Loss : 2.0565
Epoch [  5/1000] | Train Loss : 1.2490
Epoch [ 10/1000] | Train Loss : 1.0207 | Test Acc : 0.6225
Epoch [ 15/1000] | Train Loss : 0.8901
Epoch [ 20/1000] | Train Loss : 0.7820 | Test Acc : 0.6403
Epoch [ 25/1000] | Train Loss : 0.7095
Epoch [ 30/1000] | Train Loss : 0.6394 | Test Acc : 0.6464
Epoch [ 35/1000] | Train Loss : 0.5824
Epoch [ 40/1000] | Train Loss : 0.5296 | Test Acc : 0.6387
Epoch [ 45/1000] | Train Loss : 0.4894
Epoch [ 50/1000] | Train Loss : 0.4488 | Test Acc : 0.6346
Epoch [ 55/1000] | Train Loss : 0.4175
Epoch [ 60/1000] | Train Loss : 0.3866 | Test Acc : 0.6387
Epoch [ 65/1000] | Train Loss : 0.3612
Epoch [ 70/1000] | Train Loss : 0.3359 | Test Acc : 0.6322
Epoch [ 75/1000] | Train Loss : 0.3099
Epoch [ 80/1000] | Train Loss : 0.2878 | Test Acc : 0.6302
Epoch [ 85/1000] | Train Loss : 0.2684
Epoch [ 90/1000] | Train Loss : 0.2525 | Test Acc : 0.6318
Epoch [ 95/1000] | Train Loss : 0.2386
Epoch [100/1000] | Train Loss : 0.2252 | Test Acc : 0.6310
Epoch [105/1000] | Train Loss : 0.2118
Epoch [110/1000] | Train Loss : 0.1968 | Test Acc : 0.6322
Epoch [115/1000] | Train Loss : 0.1849
Epoch [120/1000] | Train Loss : 0.1745 | Test Acc : 0.6257
Epoch [125/1000] | Train Loss : 0.1669
Epoch [130/1000] | Train Loss : 0.1534 | Test Acc : 0.6281
Epoch [135/1000] | Train Loss : 0.1464
Epoch [140/1000] | Train Loss : 0.1371 | Test Acc : 0.6294
Epoch [145/1000] | Train Loss : 0.1305
Epoch [150/1000] | Train Loss : 0.1268 | Test Acc : 0.6294
Epoch [155/1000] | Train Loss : 0.1163
Epoch [160/1000] | Train Loss : 0.1104 | Test Acc : 0.6281
Epoch [165/1000] | Train Loss : 0.1073
Epoch [170/1000] | Train Loss : 0.1000 | Test Acc : 0.6261
Epoch [175/1000] | Train Loss : 0.0946
Epoch [180/1000] | Train Loss : 0.0897 | Test Acc : 0.6298
Epoch [185/1000] | Train Loss : 0.0854
Epoch [190/1000] | Train Loss : 0.0819 | Test Acc : 0.6261
Epoch [195/1000] | Train Loss : 0.0779
Epoch [200/1000] | Train Loss : 0.0730 | Test Acc : 0.6225
Epoch [205/1000] | Train Loss : 0.0699
Epoch [210/1000] | Train Loss : 0.0674 | Test Acc : 0.6212
Epoch [215/1000] | Train Loss : 0.0632
Epoch [220/1000] | Train Loss : 0.0594 | Test Acc : 0.6212
Epoch [225/1000] | Train Loss : 0.0563
Epoch [230/1000] | Train Loss : 0.0559 | Test Acc : 0.6188
Epoch [235/1000] | Train Loss : 0.0550
Epoch [240/1000] | Train Loss : 0.0499 | Test Acc : 0.6273
Epoch [245/1000] | Train Loss : 0.0494
Epoch [250/1000] | Train Loss : 0.0482 | Test Acc : 0.6160
Epoch [255/1000] | Train Loss : 0.0456
Epoch [260/1000] | Train Loss : 0.0441 | Test Acc : 0.6229
Epoch [265/1000] | Train Loss : 0.0425
Epoch [270/1000] | Train Loss : 0.0409 | Test Acc : 0.6204
Epoch [275/1000] | Train Loss : 0.0391
Epoch [280/1000] | Train Loss : 0.0354 | Test Acc : 0.6221
Epoch [285/1000] | Train Loss : 0.0348
Epoch [290/1000] | Train Loss : 0.0329 | Test Acc : 0.6164
Epoch [295/1000] | Train Loss : 0.0339
Epoch [300/1000] | Train Loss : 0.0315 | Test Acc : 0.6156
Epoch [305/1000] | Train Loss : 0.0293
Epoch [310/1000] | Train Loss : 0.0298 | Test Acc : 0.6111
Epoch [315/1000] | Train Loss : 0.0283
Epoch [320/1000] | Train Loss : 0.0272 | Test Acc : 0.6144
Epoch [325/1000] | Train Loss : 0.0263
Epoch [330/1000] | Train Loss : 0.0242 | Test Acc : 0.6119
Epoch [335/1000] | Train Loss : 0.0241
Epoch [340/1000] | Train Loss : 0.0236 | Test Acc : 0.6152
Epoch [345/1000] | Train Loss : 0.0226
Epoch [350/1000] | Train Loss : 0.0222 | Test Acc : 0.6131
Epoch [355/1000] | Train Loss : 0.0218
Epoch [360/1000] | Train Loss : 0.0212 | Test Acc : 0.6135
Epoch [365/1000] | Train Loss : 0.0196
Epoch [370/1000] | Train Loss : 0.0198 | Test Acc : 0.6103
Epoch [375/1000] | Train Loss : 0.0199
Epoch [380/1000] | Train Loss : 0.0182 | Test Acc : 0.6079
Epoch [385/1000] | Train Loss : 0.0179
Epoch [390/1000] | Train Loss : 0.0181 | Test Acc : 0.6083
Epoch [395/1000] | Train Loss : 0.0180
Epoch [400/1000] | Train Loss : 0.0167 | Test Acc : 0.6103
Epoch [405/1000] | Train Loss : 0.0171
Epoch [410/1000] | Train Loss : 0.0165 | Test Acc : 0.6075
Epoch [415/1000] | Train Loss : 0.0148
Epoch [420/1000] | Train Loss : 0.0145 | Test Acc : 0.6083
Epoch [425/1000] | Train Loss : 0.0158
Epoch [430/1000] | Train Loss : 0.0152 | Test Acc : 0.6099
Epoch [435/1000] | Train Loss : 0.0146
Epoch [440/1000] | Train Loss : 0.0135 | Test Acc : 0.6058
Epoch [445/1000] | Train Loss : 0.0136
Epoch [450/1000] | Train Loss : 0.0135 | Test Acc : 0.6034
Epoch [455/1000] | Train Loss : 0.0127
Epoch [460/1000] | Train Loss : 0.0124 | Test Acc : 0.6067
Epoch [465/1000] | Train Loss : 0.0125
Epoch [470/1000] | Train Loss : 0.0128 | Test Acc : 0.6034
Epoch [475/1000] | Train Loss : 0.0127
Epoch [480/1000] | Train Loss : 0.0128 | Test Acc : 0.6018
Epoch [485/1000] | Train Loss : 0.0119
Epoch [490/1000] | Train Loss : 0.0117 | Test Acc : 0.6026
Epoch [495/1000] | Train Loss : 0.0122
Epoch [500/1000] | Train Loss : 0.0117 | Test Acc : 0.6046
Epoch [505/1000] | Train Loss : 0.0110
Epoch [510/1000] | Train Loss : 0.0116 | Test Acc : 0.6018
Epoch [515/1000] | Train Loss : 0.0112
Epoch [520/1000] | Train Loss : 0.0115 | Test Acc : 0.6026
Epoch [525/1000] | Train Loss : 0.0100
Epoch [530/1000] | Train Loss : 0.0110 | Test Acc : 0.6046
Epoch [535/1000] | Train Loss : 0.0108
Epoch [540/1000] | Train Loss : 0.0106 | Test Acc : 0.6022
Epoch [545/1000] | Train Loss : 0.0097
Epoch [550/1000] | Train Loss : 0.0098 | Test Acc : 0.6038
Epoch [555/1000] | Train Loss : 0.0103
Epoch [560/1000] | Train Loss : 0.0101 | Test Acc : 0.6014
Epoch [565/1000] | Train Loss : 0.0097
Epoch [570/1000] | Train Loss : 0.0100 | Test Acc : 0.6046
Epoch [575/1000] | Train Loss : 0.0096
Epoch [580/1000] | Train Loss : 0.0114 | Test Acc : 0.6067
Epoch [585/1000] | Train Loss : 0.0100
Epoch [590/1000] | Train Loss : 0.0104 | Test Acc : 0.6030
Epoch [595/1000] | Train Loss : 0.0090
Epoch [600/1000] | Train Loss : 0.0087 | Test Acc : 0.6002
Epoch [605/1000] | Train Loss : 0.0089
Epoch [610/1000] | Train Loss : 0.0082 | Test Acc : 0.6022
Epoch [615/1000] | Train Loss : 0.0096
Epoch [620/1000] | Train Loss : 0.0087 | Test Acc : 0.6026
Epoch [625/1000] | Train Loss : 0.0087
Epoch [630/1000] | Train Loss : 0.0088 | Test Acc : 0.5994
Epoch [635/1000] | Train Loss : 0.0082
Epoch [640/1000] | Train Loss : 0.0089 | Test Acc : 0.6046
Epoch [645/1000] | Train Loss : 0.0082
Epoch [650/1000] | Train Loss : 0.0084 | Test Acc : 0.6050
Epoch [655/1000] | Train Loss : 0.0086
Epoch [660/1000] | Train Loss : 0.0085 | Test Acc : 0.5969
Epoch [665/1000] | Train Loss : 0.0079
Epoch [670/1000] | Train Loss : 0.0082 | Test Acc : 0.6030
Epoch [675/1000] | Train Loss : 0.0077
Epoch [680/1000] | Train Loss : 0.0076 | Test Acc : 0.6006
Epoch [685/1000] | Train Loss : 0.0084
Epoch [690/1000] | Train Loss : 0.0078 | Test Acc : 0.6054
Epoch [695/1000] | Train Loss : 0.0082
Epoch [700/1000] | Train Loss : 0.0082 | Test Acc : 0.6038
Epoch [705/1000] | Train Loss : 0.0072
Epoch [710/1000] | Train Loss : 0.0081 | Test Acc : 0.5985
Epoch [715/1000] | Train Loss : 0.0085
Epoch [720/1000] | Train Loss : 0.0077 | Test Acc : 0.6030
Epoch [725/1000] | Train Loss : 0.0077
Epoch [730/1000] | Train Loss : 0.0077 | Test Acc : 0.6010
Epoch [735/1000] | Train Loss : 0.0077
Epoch [740/1000] | Train Loss : 0.0080 | Test Acc : 0.5985
Epoch [745/1000] | Train Loss : 0.0085
Epoch [750/1000] | Train Loss : 0.0073 | Test Acc : 0.5998
Epoch [755/1000] | Train Loss : 0.0072
Epoch [760/1000] | Train Loss : 0.0077 | Test Acc : 0.6042
Epoch [765/1000] | Train Loss : 0.0075
Epoch [770/1000] | Train Loss : 0.0073 | Test Acc : 0.5998
Epoch [775/1000] | Train Loss : 0.0078
Epoch [780/1000] | Train Loss : 0.0073 | Test Acc : 0.6034
Epoch [785/1000] | Train Loss : 0.0077
Epoch [790/1000] | Train Loss : 0.0077 | Test Acc : 0.5994
Epoch [795/1000] | Train Loss : 0.0067
Epoch [800/1000] | Train Loss : 0.0072 | Test Acc : 0.6022
Epoch [805/1000] | Train Loss : 0.0076
Epoch [810/1000] | Train Loss : 0.0071 | Test Acc : 0.6006
Epoch [815/1000] | Train Loss : 0.0073
Epoch [820/1000] | Train Loss : 0.0084 | Test Acc : 0.5989
Epoch [825/1000] | Train Loss : 0.0072
Epoch [830/1000] | Train Loss : 0.0075 | Test Acc : 0.6034
Epoch [835/1000] | Train Loss : 0.0076
Epoch [840/1000] | Train Loss : 0.0071 | Test Acc : 0.6026
Epoch [845/1000] | Train Loss : 0.0070
Epoch [850/1000] | Train Loss : 0.0078 | Test Acc : 0.5994
Epoch [855/1000] | Train Loss : 0.0070
Epoch [860/1000] | Train Loss : 0.0072 | Test Acc : 0.6002
Epoch [865/1000] | Train Loss : 0.0071
Epoch [870/1000] | Train Loss : 0.0071 | Test Acc : 0.5985
Epoch [875/1000] | Train Loss : 0.0066
Epoch [880/1000] | Train Loss : 0.0071 | Test Acc : 0.5965
Epoch [885/1000] | Train Loss : 0.0065
Epoch [890/1000] | Train Loss : 0.0067 | Test Acc : 0.5981
Epoch [895/1000] | Train Loss : 0.0063
Epoch [900/1000] | Train Loss : 0.0066 | Test Acc : 0.5994
Epoch [905/1000] | Train Loss : 0.0073
Epoch [910/1000] | Train Loss : 0.0072 | Test Acc : 0.6002
Epoch [915/1000] | Train Loss : 0.0065
Epoch [920/1000] | Train Loss : 0.0066 | Test Acc : 0.6006
Epoch [925/1000] | Train Loss : 0.0068
Epoch [930/1000] | Train Loss : 0.0068 | Test Acc : 0.5981
Epoch [935/1000] | Train Loss : 0.0076
Epoch [940/1000] | Train Loss : 0.0066 | Test Acc : 0.5998
Epoch [945/1000] | Train Loss : 0.0065
Epoch [950/1000] | Train Loss : 0.0062 | Test Acc : 0.5981
Epoch [955/1000] | Train Loss : 0.0074
Epoch [960/1000] | Train Loss : 0.0065 | Test Acc : 0.5989
Epoch [965/1000] | Train Loss : 0.0076
Epoch [970/1000] | Train Loss : 0.0071 | Test Acc : 0.5961
Epoch [975/1000] | Train Loss : 0.0066
Epoch [980/1000] | Train Loss : 0.0067 | Test Acc : 0.5981
Epoch [985/1000] | Train Loss : 0.0071
Epoch [990/1000] | Train Loss : 0.0061 | Test Acc : 0.5985
Epoch [995/1000] | Train Loss : 0.0068
Epoch [1000/1000] | Train Loss : 0.0063 | Test Acc : 0.5994

In [ ]:
display(df_results)

               Test Accuracy
Attention mode
global                 0.592
per_scale              0.555
per_variable           0.558
per_both               0.599

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

# 1. Définition du nouveau modèle Multi-Head Attention
class MultiHeadAttentionPooling(nn.Module):
    def __init__(self, in_features=384, num_heads=8, num_classes=2, dropout=0.01):
        super().__init__()
        # Token apprenable [CLS] (la "Query" qui va interroger les patchs)
        self.cls_token = nn.Parameter(torch.randn(1, 1, in_features) * 0.02)
        
        # La fameuse couche d'attention multi-têtes native de PyTorch
        self.mha = nn.MultiheadAttention(
            embed_dim=in_features, 
            num_heads=num_heads, 
            dropout=dropout, 
            batch_first=True
        )
        
        # Classifieur final (MLP un peu plus robuste qu'un simple Linear)
        self.lin = nn.Linear(in_features, num_classes)

    def forward(self, x):
        # x shape: (Batch, Seq_Len=66, Features=384)
        B = x.shape[0]
        
        # On duplique le token [CLS] pour l'avoir sur tout le batch
        cls_tokens = self.cls_token.expand(B, -1, -1)  # (Batch, 1, 384)
        
        # Cross-Attention : Le [CLS] (Query) regarde tous tes patchs (Key / Value)
        attn_output, attn_weights = self.mha(query=cls_tokens, key=x, value=x)
        
        # attn_output est de taille (Batch, 1, 384). On enlève la dimension 1 inutile avec squeeze
        pooled = attn_output.squeeze(1)  # (Batch, 384)
        
        # On passe l'embedding agrégé dans le classifieur
        return self.lin(pooled)


# 2. Paramètres d'entraînement (identiques aux tiens)
BATCH_SIZE = 64*2**2
EPOCHS = 1000
LEARNING_RATE = 0.0001
EVAL_EVERY_N_EPOCHS = 10
PRINT_LOSS_EVERY = 5 

# 3. Préparation du DataLoader
train_dataset = TensorDataset(Z_train_concat, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

# 4. Instanciation du modèle et de l'optimiseur
model_mha = MultiHeadAttentionPooling(
    in_features=384, 
    num_heads=4, 
    num_classes=num_classes, # Utilise ta variable déjà existante
    dropout=0.01
).to(device)

optimizer = optim.Adam(model_mha.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss()

print("🚀 Début de l'entraînement avec Multi-Head Attention Pooling...")

# 5. Boucle d'entraînement
for epoch in range(EPOCHS):
    model_mha.train()
    running_loss = 0.0
    
    for batch_z, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model_mha(batch_z)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item() * batch_z.size(0)
        
    epoch_loss = running_loss / len(train_loader.dataset)
    
    # Affichage des logs
    if (epoch + 1) == 1 or (epoch + 1) % PRINT_LOSS_EVERY == 0:
        print(f"Epoch [{epoch+1:3d}/{EPOCHS}] | Train Loss : {epoch_loss:.4f}", end="")
        
        # Évaluation périodique sur le test set
        if (epoch + 1) % EVAL_EVERY_N_EPOCHS == 0:
            model_mha.eval()
            with torch.no_grad():
                test_outputs = model_mha(Z_test_concat)
                _, predicted = torch.max(test_outputs.data, 1)
                acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
            print(f" | Test Acc : {acc:.4f}")
        else:
            print() 
            
# 6. Évaluation finale
model_mha.eval()
with torch.no_grad():
    test_outputs = model_mha(Z_test_concat)
    _, predicted = torch.max(test_outputs.data, 1)
    final_acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
    
print(f"\n🏆 Précision finale sur le Test Set : {final_acc:.3f}")

🚀 Début de l'entraînement avec Multi-Head Attention Pooling...
Epoch [  1/1000] | Train Loss : 2.4292
Epoch [  5/1000] | Train Loss : 2.0335
Epoch [ 10/1000] | Train Loss : 1.8379 | Test Acc : 0.4465
Epoch [ 15/1000] | Train Loss : 1.6199
Epoch [ 20/1000] | Train Loss : 1.4592 | Test Acc : 0.5251
Epoch [ 25/1000] | Train Loss : 1.3577
Epoch [ 30/1000] | Train Loss : 1.3010 | Test Acc : 0.5689
Epoch [ 35/1000] | Train Loss : 1.2585
Epoch [ 40/1000] | Train Loss : 1.2248 | Test Acc : 0.5892
Epoch [ 45/1000] | Train Loss : 1.1917
Epoch [ 50/1000] | Train Loss : 1.1547 | Test Acc : 0.5880
Epoch [ 55/1000] | Train Loss : 1.1254
Epoch [ 60/1000] | Train Loss : 1.0939 | Test Acc : 0.5900
Epoch [ 65/1000] | Train Loss : 1.0648
Epoch [ 70/1000] | Train Loss : 1.0368 | Test Acc : 0.5929
Epoch [ 75/1000] | Train Loss : 1.0036
Epoch [ 80/1000] | Train Loss : 0.9753 | Test Acc : 0.5872
Epoch [ 85/1000] | Train Loss : 0.9533
Epoch [ 90/1000] | Train Loss : 0.9230 | Test Acc : 0.5811
Epoch [ 95/1000] | Train Loss : 0.8981
Epoch [100/1000] | Train Loss : 0.8697 | Test Acc : 0.5779
Epoch [105/1000] | Train Loss : 0.8455
Epoch [110/1000] | Train Loss : 0.8258 | Test Acc : 0.5750
Epoch [115/1000] | Train Loss : 0.8006
Epoch [120/1000] | Train Loss : 0.7810 | Test Acc : 0.5681
Epoch [125/1000] | Train Loss : 0.7581
Epoch [130/1000] | Train Loss : 0.7366 | Test Acc : 0.5624
Epoch [135/1000] | Train Loss : 0.7145
Epoch [140/1000] | Train Loss : 0.6962 | Test Acc : 0.5527
Epoch [145/1000] | Train Loss : 0.6759
Epoch [150/1000] | Train Loss : 0.6527 | Test Acc : 0.5499
Epoch [155/1000] | Train Loss : 0.6363
Epoch [160/1000] | Train Loss : 0.6181 | Test Acc : 0.5519
Epoch [165/1000] | Train Loss : 0.5951
Epoch [170/1000] | Train Loss : 0.5775 | Test Acc : 0.5547
Epoch [175/1000] | Train Loss : 0.5576
Epoch [180/1000] | Train Loss : 0.5353 | Test Acc : 0.5507
Epoch [185/1000] | Train Loss : 0.5251
Epoch [190/1000] | Train Loss : 0.4993 | Test Acc : 0.5474
Epoch [195/1000] | Train Loss : 0.4823
Epoch [200/1000] | Train Loss : 0.4648 | Test Acc : 0.5458
Epoch [205/1000] | Train Loss : 0.4446
Epoch [210/1000] | Train Loss : 0.4265 | Test Acc : 0.5426
Epoch [215/1000] | Train Loss : 0.4135
Epoch [220/1000] | Train Loss : 0.3991 | Test Acc : 0.5292
Epoch [225/1000] | Train Loss : 0.3857
Epoch [230/1000] | Train Loss : 0.3619 | Test Acc : 0.5288
Epoch [235/1000] | Train Loss : 0.3492
Epoch [240/1000] | Train Loss : 0.3348 | Test Acc : 0.5174
Epoch [245/1000] | Train Loss : 0.3229
Epoch [250/1000] | Train Loss : 0.3073 | Test Acc : 0.5195
Epoch [255/1000] | Train Loss : 0.2895
Epoch [260/1000] | Train Loss : 0.2811 | Test Acc : 0.5142
Epoch [265/1000] | Train Loss : 0.2712
Epoch [270/1000] | Train Loss : 0.2541 | Test Acc : 0.5182
Epoch [275/1000] | Train Loss : 0.2486
Epoch [280/1000] | Train Loss : 0.2259 | Test Acc : 0.5097
Epoch [285/1000] | Train Loss : 0.2225
Epoch [290/1000] | Train Loss : 0.2095 | Test Acc : 0.5085
Epoch [295/1000] | Train Loss : 0.2050
Epoch [300/1000] | Train Loss : 0.1847 | Test Acc : 0.5065
Epoch [305/1000] | Train Loss : 0.1798
Epoch [310/1000] | Train Loss : 0.1726 | Test Acc : 0.5085
Epoch [315/1000] | Train Loss : 0.1700
Epoch [320/1000] | Train Loss : 0.1553 | Test Acc : 0.5012
Epoch [325/1000] | Train Loss : 0.1486
Epoch [330/1000] | Train Loss : 0.1421 | Test Acc : 0.5049
Epoch [335/1000] | Train Loss : 0.1338
Epoch [340/1000] | Train Loss : 0.1210 | Test Acc : 0.4959
Epoch [345/1000] | Train Loss : 0.1207
Epoch [350/1000] | Train Loss : 0.1177 | Test Acc : 0.4996
Epoch [355/1000] | Train Loss : 0.1061
Epoch [360/1000] | Train Loss : 0.1003 | Test Acc : 0.4976
Epoch [365/1000] | Train Loss : 0.0978
Epoch [370/1000] | Train Loss : 0.0976 | Test Acc : 0.4947
Epoch [375/1000] | Train Loss : 0.1055
Epoch [380/1000] | Train Loss : 0.0856 | Test Acc : 0.4968
Epoch [385/1000] | Train Loss : 0.0854
Epoch [390/1000] | Train Loss : 0.0765 | Test Acc : 0.4935
Epoch [395/1000] | Train Loss : 0.0752
Epoch [400/1000] | Train Loss : 0.0770 | Test Acc : 0.4915
Epoch [405/1000] | Train Loss : 0.0725
Epoch [410/1000] | Train Loss : 0.0746 | Test Acc : 0.4866
Epoch [415/1000] | Train Loss : 0.0755
Epoch [420/1000] | Train Loss : 0.0663 | Test Acc : 0.4907
Epoch [425/1000] | Train Loss : 0.0561
Epoch [430/1000] | Train Loss : 0.0595 | Test Acc : 0.4911
Epoch [435/1000] | Train Loss : 0.0548
Epoch [440/1000] | Train Loss : 0.0603 | Test Acc : 0.4931
Epoch [445/1000] | Train Loss : 0.0542
Epoch [450/1000] | Train Loss : 0.0480 | Test Acc : 0.5004
Epoch [455/1000] | Train Loss : 0.0541
Epoch [460/1000] | Train Loss : 0.0484 | Test Acc : 0.4968
Epoch [465/1000] | Train Loss : 0.0509
Epoch [470/1000] | Train Loss : 0.0503 | Test Acc : 0.4951
Epoch [475/1000] | Train Loss : 0.0424
Epoch [480/1000] | Train Loss : 0.0457 | Test Acc : 0.4874
Epoch [485/1000] | Train Loss : 0.0386
Epoch [490/1000] | Train Loss : 0.0366 | Test Acc : 0.4972
Epoch [495/1000] | Train Loss : 0.0342
Epoch [500/1000] | Train Loss : 0.0446 | Test Acc : 0.4959
Epoch [505/1000] | Train Loss : 0.0355
Epoch [510/1000] | Train Loss : 0.0401 | Test Acc : 0.4959
Epoch [515/1000] | Train Loss : 0.0455
Epoch [520/1000] | Train Loss : 0.0346 | Test Acc : 0.4923
Epoch [525/1000] | Train Loss : 0.0355
Epoch [530/1000] | Train Loss : 0.0412 | Test Acc : 0.4947
Epoch [535/1000] | Train Loss : 0.0387
Epoch [540/1000] | Train Loss : 0.0344 | Test Acc : 0.4943
Epoch [545/1000] | Train Loss : 0.0343
Epoch [550/1000] | Train Loss : 0.0457 | Test Acc : 0.5012
Epoch [555/1000] | Train Loss : 0.0360
Epoch [560/1000] | Train Loss : 0.0316 | Test Acc : 0.4923
Epoch [565/1000] | Train Loss : 0.0325
Epoch [570/1000] | Train Loss : 0.0414 | Test Acc : 0.4984
Epoch [575/1000] | Train Loss : 0.0370
Epoch [580/1000] | Train Loss : 0.0396 | Test Acc : 0.4968
Epoch [585/1000] | Train Loss : 0.0376
Epoch [590/1000] | Train Loss : 0.0322 | Test Acc : 0.5008
Epoch [595/1000] | Train Loss : 0.0330
Epoch [600/1000] | Train Loss : 0.0203 | Test Acc : 0.4972
Epoch [605/1000] | Train Loss : 0.0310
Epoch [610/1000] | Train Loss : 0.0325 | Test Acc : 0.4968
Epoch [615/1000] | Train Loss : 0.0291
Epoch [620/1000] | Train Loss : 0.0278 | Test Acc : 0.4980
Epoch [625/1000] | Train Loss : 0.0305
Epoch [630/1000] | Train Loss : 0.0251 | Test Acc : 0.5008
Epoch [635/1000] | Train Loss : 0.0270
Epoch [640/1000] | Train Loss : 0.0373 | Test Acc : 0.4964
Epoch [645/1000] | Train Loss : 0.0329
Epoch [650/1000] | Train Loss : 0.0269 | Test Acc : 0.4895
Epoch [655/1000] | Train Loss : 0.0304
Epoch [660/1000] | Train Loss : 0.0377 | Test Acc : 0.4858
Epoch [665/1000] | Train Loss : 0.0290
Epoch [670/1000] | Train Loss : 0.0230 | Test Acc : 0.5004
Epoch [675/1000] | Train Loss : 0.0294
Epoch [680/1000] | Train Loss : 0.0270 | Test Acc : 0.4955
Epoch [685/1000] | Train Loss : 0.0280
Epoch [690/1000] | Train Loss : 0.0244 | Test Acc : 0.5000
Epoch [695/1000] | Train Loss : 0.0367
Epoch [700/1000] | Train Loss : 0.0349 | Test Acc : 0.4939
Epoch [705/1000] | Train Loss : 0.0339
Epoch [710/1000] | Train Loss : 0.0335 | Test Acc : 0.4988
Epoch [715/1000] | Train Loss : 0.0231
Epoch [720/1000] | Train Loss : 0.0226 | Test Acc : 0.4959
Epoch [725/1000] | Train Loss : 0.0215
Epoch [730/1000] | Train Loss : 0.0237 | Test Acc : 0.4919
Epoch [735/1000] | Train Loss : 0.0227
Epoch [740/1000] | Train Loss : 0.0264 | Test Acc : 0.4984
Epoch [745/1000] | Train Loss : 0.0279
Epoch [750/1000] | Train Loss : 0.0161 | Test Acc : 0.4891
Epoch [755/1000] | Train Loss : 0.0301
Epoch [760/1000] | Train Loss : 0.0284 | Test Acc : 0.4919
Epoch [765/1000] | Train Loss : 0.0244
Epoch [770/1000] | Train Loss : 0.0292 | Test Acc : 0.4988
Epoch [775/1000] | Train Loss : 0.0317
Epoch [780/1000] | Train Loss : 0.0229 | Test Acc : 0.4939
Epoch [785/1000] | Train Loss : 0.0245
Epoch [790/1000] | Train Loss : 0.0260 | Test Acc : 0.4972
Epoch [795/1000] | Train Loss : 0.0294
Epoch [800/1000] | Train Loss : 0.0229 | Test Acc : 0.5004
Epoch [805/1000] | Train Loss : 0.0168
Epoch [810/1000] | Train Loss : 0.0291 | Test Acc : 0.4951
Epoch [815/1000] | Train Loss : 0.0273
Epoch [820/1000] | Train Loss : 0.0275 | Test Acc : 0.4939
Epoch [825/1000] | Train Loss : 0.0284
Epoch [830/1000] | Train Loss : 0.0287 | Test Acc : 0.5024
Epoch [835/1000] | Train Loss : 0.0236
Epoch [840/1000] | Train Loss : 0.0240 | Test Acc : 0.4964
Epoch [845/1000] | Train Loss : 0.0186
Epoch [850/1000] | Train Loss : 0.0180 | Test Acc : 0.4984
Epoch [855/1000] | Train Loss : 0.0199
Epoch [860/1000] | Train Loss : 0.0238 | Test Acc : 0.4915
Epoch [865/1000] | Train Loss : 0.0231
Epoch [870/1000] | Train Loss : 0.0218 | Test Acc : 0.5073
Epoch [875/1000] | Train Loss : 0.0310
Epoch [880/1000] | Train Loss : 0.0217 | Test Acc : 0.5012
Epoch [885/1000] | Train Loss : 0.0157
Epoch [890/1000] | Train Loss : 0.0200 | Test Acc : 0.4988
Epoch [895/1000] | Train Loss : 0.0243
Epoch [900/1000] | Train Loss : 0.0269 | Test Acc : 0.4980
Epoch [905/1000] | Train Loss : 0.0228
Epoch [910/1000] | Train Loss : 0.0174 | Test Acc : 0.4955
Epoch [915/1000] | Train Loss : 0.0303
Epoch [920/1000] | Train Loss : 0.0332 | Test Acc : 0.5016
Epoch [925/1000] | Train Loss : 0.0141
Epoch [930/1000] | Train Loss : 0.0291 | Test Acc : 0.4842
Epoch [935/1000] | Train Loss : 0.0201
Epoch [940/1000] | Train Loss : 0.0184 | Test Acc : 0.4972
Epoch [945/1000] | Train Loss : 0.0191
Epoch [950/1000] | Train Loss : 0.0127 | Test Acc : 0.4939
Epoch [955/1000] | Train Loss : 0.0240
Epoch [960/1000] | Train Loss : 0.0243 | Test Acc : 0.4988
Epoch [965/1000] | Train Loss : 0.0189
Epoch [970/1000] | Train Loss : 0.0148 | Test Acc : 0.4919
Epoch [975/1000] | Train Loss : 0.0171
Epoch [980/1000] | Train Loss : 0.0188 | Test Acc : 0.4935
Epoch [985/1000] | Train Loss : 0.0247
Epoch [990/1000] | Train Loss : 0.0264 | Test Acc : 0.5049
Epoch [995/1000] | Train Loss : 0.0192
Epoch [1000/1000] | Train Loss : 0.0139 | Test Acc : 0.4984

🏆 Précision finale sur le Test Set : 0.498

In [ ]:
import torch
import torch.nn as nn

class ImprovedMultiHeadAttention(nn.Module):
    def __init__(self, in_features=384, seq_len=66, num_heads=8, num_classes=2, dropout=0.1):
        super().__init__()
        
        # 1. Le Manager (Token CLS)
        self.cls_token = nn.Parameter(torch.randn(1, 1, in_features) * 0.02)
        
        # 2. Le Positional Encoding (Le remède contre l'amnésie)
        self.pos_embed = nn.Parameter(torch.randn(1, seq_len, in_features) * 0.02)
        
        # 3. Layer Normalization (Pour la stabilité avant l'attention)
        self.norm_k = nn.LayerNorm(in_features)
        self.norm_q = nn.LayerNorm(in_features)
        
        # 4. L'Attention Multi-Têtes
        self.mha = nn.MultiheadAttention(
            embed_dim=in_features, 
            num_heads=num_heads, 
            dropout=dropout, 
            batch_first=True
        )
        
        # 5. La Tête de Classification : Juste Linéaire !
        self.classifier = nn.Linear(in_features, num_classes)

    def forward(self, x):
        # x shape: (Batch, Seq_Len=66, Features=384)
        B = x.shape[0]
        
        # On ajoute l'encodage de position aux patchs AVANT l'attention
        x = x + self.pos_embed
        
        # On duplique le token CLS pour le batch
        cls_tokens = self.cls_token.expand(B, -1, -1)
        
        # Normalisation pour stabiliser l'entraînement
        x_norm = self.norm_k(x)
        cls_norm = self.norm_q(cls_tokens)
        
        # Cross-Attention
        attn_output, _ = self.mha(query=cls_norm, key=x_norm, value=x_norm)
        
        # On retire la dimension de la séquence qui vaut 1
        pooled = attn_output.squeeze(1)
        
        # On passe directement dans la couche linéaire
        return self.classifier(pooled)

In [ ]:
model_mha = ImprovedMultiHeadAttention(
    in_features=384, 
    seq_len=66, # Tu as 66 patchs au total d'après ton print
    num_heads=8, 
    num_classes=num_classes, 
    dropout=0.1
).to(device)

optimizer = optim.Adam(model_mha.parameters(), lr=0.0001, weight_decay=1e-3)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import pandas as pd

# ==========================================
# 1. DÉFINITION DU MODÈLE
# ==========================================
class ImprovedMultiHeadAttention(nn.Module):
    def __init__(self, in_features=384, seq_len=66, num_heads=8, num_classes=2, dropout=0.1):
        super().__init__()
        
        # Le Manager (Token CLS)
        self.cls_token = nn.Parameter(torch.randn(1, 1, in_features) * 0.02)
        
        # Le Positional Encoding (Le remède contre l'amnésie)
        self.pos_embed = nn.Parameter(torch.randn(1, seq_len, in_features) * 0.02)
        
        # Layer Normalization (Pour la stabilité avant l'attention)
        self.norm_k = nn.LayerNorm(in_features)
        self.norm_q = nn.LayerNorm(in_features)
        
        # L'Attention Multi-Têtes
        self.mha = nn.MultiheadAttention(
            embed_dim=in_features, 
            num_heads=num_heads, 
            dropout=dropout, 
            batch_first=True
        )
        
        # La Tête de Classification : Juste Linéaire !
        self.classifier = nn.Linear(in_features, num_classes)

    def forward(self, x):
        B = x.shape[0]
        
        # On ajoute l'encodage de position aux patchs AVANT l'attention
        x = x + self.pos_embed
        
        # On duplique le token CLS pour le batch
        cls_tokens = self.cls_token.expand(B, -1, -1)
        
        # Normalisation pour stabiliser l'entraînement
        x_norm = self.norm_k(x)
        cls_norm = self.norm_q(cls_tokens)
        
        # Cross-Attention
        attn_output, _ = self.mha(query=cls_norm, key=x_norm, value=x_norm)
        
        # On retire la dimension de la séquence
        pooled = attn_output.squeeze(1)
        
        # Prédiction finale
        return self.classifier(pooled)


# ==========================================
# 2. PARAMÈTRES ET PRÉPARATION
# ==========================================
BATCH_SIZE = 64*2**2
EPOCHS = 1000
LEARNING_RATE = 0.00001
EVAL_EVERY_N_EPOCHS = 10
PRINT_LOSS_EVERY = 5 
WEIGHT_DECAY = 1e-3 # Plus élevé pour lutter contre l'overfitting

# On s'assure d'avoir notre DataFrame pour stocker les résultats
if 'df_results' not in locals():
    df_results = pd.DataFrame(columns=["Test Accuracy"])
    df_results.index.name = "Attention mode"

mode_name = "multi_head_cls_linear"

# Préparation du DataLoader
train_dataset = TensorDataset(Z_train_concat, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

# Instanciation du modèle
# seq_len=66 correspond au nombre total de patchs concaténés (5+3+2+1 * 6 variables)
model = ImprovedMultiHeadAttention(
    in_features=384, 
    seq_len=66, 
    num_heads=16, 
    num_classes=num_classes, 
    dropout=0.0
).to(device)

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
criterion = nn.CrossEntropyLoss()

# ==========================================
# 3. BOUCLE D'ENTRAÎNEMENT
# ==========================================
print(f"🚀 Début de l'entraînement pour le mode : {mode_name}")

for epoch in range(EPOCHS):
    model.train()
    running_loss = 0.0
    
    for batch_z, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_z)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item() * batch_z.size(0)
        
    epoch_loss = running_loss / len(train_loader.dataset)
    
    # Affichage régulier
    if (epoch + 1) == 1 or (epoch + 1) % PRINT_LOSS_EVERY == 0:
        print(f"Epoch [{epoch+1:3d}/{EPOCHS}] | Train Loss : {epoch_loss:.4f}", end="")
        
        if (epoch + 1) % EVAL_EVERY_N_EPOCHS == 0:
            model.eval()
            with torch.no_grad():
                test_outputs = model(Z_test_concat)
                _, predicted = torch.max(test_outputs.data, 1)
                acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
            print(f" | Test Acc : {acc:.4f}")
        else:
            print() 

# ==========================================
# 4. ÉVALUATION FINALE ET SAUVEGARDE
# ==========================================
model.eval()
with torch.no_grad():
    test_outputs = model(Z_test_concat)
    _, predicted = torch.max(test_outputs.data, 1)
    final_acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)

# Enregistrement dans le DataFrame
df_results.loc[mode_name, "Test Accuracy"] = round(final_acc, 3)

print("\n" + "="*40)
print(f"🏆 Précision finale sur le Test Set : {final_acc:.3f}")
print("="*40)

# Afficher le tableau des résultats mis à jour
display(df_results)

🚀 Début de l'entraînement pour le mode : multi_head_cls_linear
Epoch [  1/1000] | Train Loss : 2.5486

Epoch [  5/1000] | Train Loss : 2.3399
Epoch [ 10/1000] | Train Loss : 2.1800 | Test Acc : 0.3151
Epoch [ 15/1000] | Train Loss : 2.0910
Epoch [ 20/1000] | Train Loss : 2.0277 | Test Acc : 0.3402
Epoch [ 25/1000] | Train Loss : 1.9690
Epoch [ 30/1000] | Train Loss : 1.9100 | Test Acc : 0.4063
Epoch [ 35/1000] | Train Loss : 1.8511
Epoch [ 40/1000] | Train Loss : 1.7947 | Test Acc : 0.4331
Epoch [ 45/1000] | Train Loss : 1.7417
Epoch [ 50/1000] | Train Loss : 1.6922 | Test Acc : 0.4651
Epoch [ 55/1000] | Train Loss : 1.6461
Epoch [ 60/1000] | Train Loss : 1.6030 | Test Acc : 0.4846
Epoch [ 65/1000] | Train Loss : 1.5628
Epoch [ 70/1000] | Train Loss : 1.5260 | Test Acc : 0.5126
Epoch [ 75/1000] | Train Loss : 1.4924
Epoch [ 80/1000] | Train Loss : 1.4616 | Test Acc : 0.5324
Epoch [ 85/1000] | Train Loss : 1.4337
Epoch [ 90/1000] | Train Loss : 1.4084 | Test Acc : 0.5466
Epoch [ 95/1000] | Train Loss : 1.3853
Epoch [100/1000] | Train Loss : 1.3641 | Test Acc : 0.5608
Epoch [105/1000] | Train Loss : 1.3446
Epoch [110/1000] | Train Loss : 1.3266 | Test Acc : 0.5677
Epoch [115/1000] | Train Loss : 1.3094
Epoch [120/1000] | Train Loss : 1.2934 | Test Acc : 0.5750
Epoch [125/1000] | Train Loss : 1.2781
Epoch [130/1000] | Train Loss : 1.2636 | Test Acc : 0.5803
Epoch [135/1000] | Train Loss : 1.2496
Epoch [140/1000] | Train Loss : 1.2361 | Test Acc : 0.5807
Epoch [145/1000] | Train Loss : 1.2229
Epoch [150/1000] | Train Loss : 1.2102 | Test Acc : 0.5864
Epoch [155/1000] | Train Loss : 1.1976
Epoch [160/1000] | Train Loss : 1.1852 | Test Acc : 0.5868
Epoch [165/1000] | Train Loss : 1.1731
Epoch [170/1000] | Train Loss : 1.1611 | Test Acc : 0.5908
Epoch [175/1000] | Train Loss : 1.1493
Epoch [180/1000] | Train Loss : 1.1376 | Test Acc : 0.5904
Epoch [185/1000] | Train Loss : 1.1258
Epoch [190/1000] | Train Loss : 1.1143 | Test Acc : 0.5888
Epoch [195/1000] | Train Loss : 1.1030
Epoch [200/1000] | Train Loss : 1.0913 | Test Acc : 0.5908
Epoch [205/1000] | Train Loss : 1.0800
Epoch [210/1000] | Train Loss : 1.0689 | Test Acc : 0.5929
Epoch [215/1000] | Train Loss : 1.0575
Epoch [220/1000] | Train Loss : 1.0462 | Test Acc : 0.5908
Epoch [225/1000] | Train Loss : 1.0352
Epoch [230/1000] | Train Loss : 1.0239 | Test Acc : 0.5916
Epoch [235/1000] | Train Loss : 1.0127
Epoch [240/1000] | Train Loss : 1.0022 | Test Acc : 0.5933
Epoch [245/1000] | Train Loss : 0.9909
Epoch [250/1000] | Train Loss : 0.9797 | Test Acc : 0.5937
Epoch [255/1000] | Train Loss : 0.9687
Epoch [260/1000] | Train Loss : 0.9580 | Test Acc : 0.5933
Epoch [265/1000] | Train Loss : 0.9467
Epoch [270/1000] | Train Loss : 0.9357 | Test Acc : 0.5933
Epoch [275/1000] | Train Loss : 0.9248
Epoch [280/1000] | Train Loss : 0.9140 | Test Acc : 0.5908
Epoch [285/1000] | Train Loss : 0.9032
Epoch [290/1000] | Train Loss : 0.8923 | Test Acc : 0.5880
Epoch [295/1000] | Train Loss : 0.8815
Epoch [300/1000] | Train Loss : 0.8710 | Test Acc : 0.5896
Epoch [305/1000] | Train Loss : 0.8600
Epoch [310/1000] | Train Loss : 0.8495 | Test Acc : 0.5892
Epoch [315/1000] | Train Loss : 0.8385
Epoch [320/1000] | Train Loss : 0.8282 | Test Acc : 0.5864
Epoch [325/1000] | Train Loss : 0.8172
Epoch [330/1000] | Train Loss : 0.8068 | Test Acc : 0.5856
Epoch [335/1000] | Train Loss : 0.7962
Epoch [340/1000] | Train Loss : 0.7858 | Test Acc : 0.5843
Epoch [345/1000] | Train Loss : 0.7756
Epoch [350/1000] | Train Loss : 0.7649 | Test Acc : 0.5835
Epoch [355/1000] | Train Loss : 0.7547
Epoch [360/1000] | Train Loss : 0.7443 | Test Acc : 0.5823
Epoch [365/1000] | Train Loss : 0.7341
Epoch [370/1000] | Train Loss : 0.7243 | Test Acc : 0.5823
Epoch [375/1000] | Train Loss : 0.7141
Epoch [380/1000] | Train Loss : 0.7041 | Test Acc : 0.5775
Epoch [385/1000] | Train Loss : 0.6943
Epoch [390/1000] | Train Loss : 0.6845 | Test Acc : 0.5750
Epoch [395/1000] | Train Loss : 0.6743
Epoch [400/1000] | Train Loss : 0.6649 | Test Acc : 0.5710
Epoch [405/1000] | Train Loss : 0.6553
Epoch [410/1000] | Train Loss : 0.6461 | Test Acc : 0.5722
Epoch [415/1000] | Train Loss : 0.6363
Epoch [420/1000] | Train Loss : 0.6269 | Test Acc : 0.5624
Epoch [425/1000] | Train Loss : 0.6177
Epoch [430/1000] | Train Loss : 0.6084 | Test Acc : 0.5637
Epoch [435/1000] | Train Loss : 0.5992
Epoch [440/1000] | Train Loss : 0.5901 | Test Acc : 0.5624
Epoch [445/1000] | Train Loss : 0.5813
Epoch [450/1000] | Train Loss : 0.5725 | Test Acc : 0.5633
Epoch [455/1000] | Train Loss : 0.5636
Epoch [460/1000] | Train Loss : 0.5550 | Test Acc : 0.5608
Epoch [465/1000] | Train Loss : 0.5461
Epoch [470/1000] | Train Loss : 0.5375 | Test Acc : 0.5616
Epoch [475/1000] | Train Loss : 0.5291
Epoch [480/1000] | Train Loss : 0.5209 | Test Acc : 0.5608
Epoch [485/1000] | Train Loss : 0.5121
Epoch [490/1000] | Train Loss : 0.5041 | Test Acc : 0.5576
Epoch [495/1000] | Train Loss : 0.4955
Epoch [500/1000] | Train Loss : 0.4876 | Test Acc : 0.5543
Epoch [505/1000] | Train Loss : 0.4792
Epoch [510/1000] | Train Loss : 0.4714 | Test Acc : 0.5543
Epoch [515/1000] | Train Loss : 0.4634
Epoch [520/1000] | Train Loss : 0.4556 | Test Acc : 0.5552
Epoch [525/1000] | Train Loss : 0.4475
Epoch [530/1000] | Train Loss : 0.4399 | Test Acc : 0.5527
Epoch [535/1000] | Train Loss : 0.4321
Epoch [540/1000] | Train Loss : 0.4246 | Test Acc : 0.5539
Epoch [545/1000] | Train Loss : 0.4172
Epoch [550/1000] | Train Loss : 0.4098 | Test Acc : 0.5515
Epoch [555/1000] | Train Loss : 0.4025
Epoch [560/1000] | Train Loss : 0.3951 | Test Acc : 0.5499
Epoch [565/1000] | Train Loss : 0.3880
Epoch [570/1000] | Train Loss : 0.3806 | Test Acc : 0.5491
Epoch [575/1000] | Train Loss : 0.3736
Epoch [580/1000] | Train Loss : 0.3667 | Test Acc : 0.5495
Epoch [585/1000] | Train Loss : 0.3597
Epoch [590/1000] | Train Loss : 0.3529 | Test Acc : 0.5466
Epoch [595/1000] | Train Loss : 0.3459
Epoch [600/1000] | Train Loss : 0.3392 | Test Acc : 0.5466
Epoch [605/1000] | Train Loss : 0.3326
Epoch [610/1000] | Train Loss : 0.3263 | Test Acc : 0.5462
Epoch [615/1000] | Train Loss : 0.3195
Epoch [620/1000] | Train Loss : 0.3132 | Test Acc : 0.5458
Epoch [625/1000] | Train Loss : 0.3068
Epoch [630/1000] | Train Loss : 0.3004 | Test Acc : 0.5430
Epoch [635/1000] | Train Loss : 0.2944
Epoch [640/1000] | Train Loss : 0.2883 | Test Acc : 0.5446
Epoch [645/1000] | Train Loss : 0.2824
Epoch [650/1000] | Train Loss : 0.2767 | Test Acc : 0.5426
Epoch [655/1000] | Train Loss : 0.2706
Epoch [660/1000] | Train Loss : 0.2647 | Test Acc : 0.5397
Epoch [665/1000] | Train Loss : 0.2590
Epoch [670/1000] | Train Loss : 0.2533 | Test Acc : 0.5397
Epoch [675/1000] | Train Loss : 0.2480
Epoch [680/1000] | Train Loss : 0.2424 | Test Acc : 0.5393
Epoch [685/1000] | Train Loss : 0.2370
Epoch [690/1000] | Train Loss : 0.2318 | Test Acc : 0.5389
Epoch [695/1000] | Train Loss : 0.2265
Epoch [700/1000] | Train Loss : 0.2215 | Test Acc : 0.5373
Epoch [705/1000] | Train Loss : 0.2162
Epoch [710/1000] | Train Loss : 0.2112 | Test Acc : 0.5357
Epoch [715/1000] | Train Loss : 0.2063
Epoch [720/1000] | Train Loss : 0.2015 | Test Acc : 0.5369
Epoch [725/1000] | Train Loss : 0.1968
Epoch [730/1000] | Train Loss : 0.1921 | Test Acc : 0.5349
Epoch [735/1000] | Train Loss : 0.1875
Epoch [740/1000] | Train Loss : 0.1830 | Test Acc : 0.5333
Epoch [745/1000] | Train Loss : 0.1786
Epoch [750/1000] | Train Loss : 0.1742 | Test Acc : 0.5320
Epoch [755/1000] | Train Loss : 0.1699
Epoch [760/1000] | Train Loss : 0.1658 | Test Acc : 0.5316
Epoch [765/1000] | Train Loss : 0.1618
Epoch [770/1000] | Train Loss : 0.1576 | Test Acc : 0.5316
Epoch [775/1000] | Train Loss : 0.1538
Epoch [780/1000] | Train Loss : 0.1499 | Test Acc : 0.5304
Epoch [785/1000] | Train Loss : 0.1461
Epoch [790/1000] | Train Loss : 0.1425 | Test Acc : 0.5296
Epoch [795/1000] | Train Loss : 0.1390
Epoch [800/1000] | Train Loss : 0.1353 | Test Acc : 0.5284
Epoch [805/1000] | Train Loss : 0.1320
Epoch [810/1000] | Train Loss : 0.1285 | Test Acc : 0.5280
Epoch [815/1000] | Train Loss : 0.1253
Epoch [820/1000] | Train Loss : 0.1221 | Test Acc : 0.5264
Epoch [825/1000] | Train Loss : 0.1191

KeyboardInterrupt:

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import pandas as pd

# ==========================================
# 1. DÉFINITION DU MODÈLE
# ==========================================
class PerScaleVariableAttentionFlatten(nn.Module):
    def __init__(self, in_features=384, num_vars=6, patches_counts=[5, 3, 2, 1], num_heads=4, num_classes=2, dropout=0.1):
        super().__init__()
        self.num_vars = num_vars
        self.patches_counts = patches_counts
        self.num_scales = len(patches_counts)
        self.in_features = in_features
        
        # On crée une liste de paramètres apprenables (1 pour chaque échelle)
        # - Un token CLS par échelle
        # - Un Positional Encoding par échelle (taille = nb de patches pour cette échelle)
        self.cls_tokens = nn.ParameterList([
            nn.Parameter(torch.randn(1, 1, in_features) * 0.02) for _ in range(self.num_scales)
        ])
        
        self.pos_embeds = nn.ParameterList([
            nn.Parameter(torch.randn(1, p_count, in_features) * 0.02) for p_count in patches_counts
        ])
        
        # On crée 4 couches d'attention indépendantes (1 par échelle)
        self.mhas = nn.ModuleList([
            nn.MultiheadAttention(embed_dim=in_features, num_heads=num_heads, dropout=dropout, batch_first=True)
            for _ in range(self.num_scales)
        ])
        
        # Classifieur linéaire final
        # Il va recevoir (6 variables) x (4 échelles) = 24 résumés de taille 384
        # Donc 24 * 384 = 9216 features en entrée
        flat_dim = self.num_vars * self.num_scales * in_features
        self.classifier = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(flat_dim, num_classes)
        )

    def forward(self, x):
            # x shape: (Batch, Total_Patches=66, Features=384)
            B = x.shape[0]
            
            # 1. On redécoupe le tenseur global en ses 4 échelles
            split_sizes = [p * self.num_vars for p in self.patches_counts] # ex: [30, 18, 12, 6]
            x_splits = torch.split(x, split_sizes, dim=1)
            
            all_pooled = []
            
            # 2. On boucle sur chaque échelle
            for i, p_count in enumerate(self.patches_counts):
                x_i = x_splits[i]  # shape: (Batch, p_count * 6, 384)
                
                # On sépare les variables avec RESHAPE (au lieu de view)
                x_i = x_i.reshape(B, self.num_vars, p_count, self.in_features)
                
                # On fusionne Batch et Variables avec RESHAPE
                x_fused = x_i.reshape(B * self.num_vars, p_count, self.in_features)
                
                # On ajoute le Positional Encoding spécifique à cette échelle
                x_fused = x_fused + self.pos_embeds[i]
                
                # On prépare le CLS token et on l'étend
                cls_expanded = self.cls_tokens[i].expand(B * self.num_vars, -1, -1)
                
                # Multi-Head Attention
                attn_out, _ = self.mhas[i](query=cls_expanded, key=x_fused, value=x_fused)
                
                # On enlève la dimension de séquence
                pooled = attn_out.squeeze(1)
                
                # On sépare à nouveau Batch et Variables et on "Flatten" avec RESHAPE
                pooled_flat = pooled.reshape(B, self.num_vars * self.in_features)
                
                all_pooled.append(pooled_flat)
                
            # 3. Flatten final (On concatène les 4 échelles)
            final_flat = torch.cat(all_pooled, dim=1)
            
            # 4. Prédiction linéaire
            return self.classifier(final_flat)


# ==========================================
# 2. PARAMÈTRES ET PRÉPARATION
# ==========================================
BATCH_SIZE = 64*2**2
EPOCHS = 1000
LEARNING_RATE = 0.00001
EVAL_EVERY_N_EPOCHS = 10
PRINT_LOSS_EVERY = 5 
WEIGHT_DECAY = 1e-3

if 'df_results' not in locals():
    df_results = pd.DataFrame(columns=["Test Accuracy"])
    df_results.index.name = "Attention mode"

mode_name = "attention_per_scale_var_flatten"

# DataLoader
train_dataset = TensorDataset(Z_train_concat, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

# Instanciation
model = PerScaleVariableAttentionFlatten(
    in_features=384, 
    num_vars=NUM_VARS, # 6
    patches_counts=patches_counts, # [5, 3, 2, 1]
    num_heads=4, 
    num_classes=num_classes, 
    dropout=0.1
).to(device)

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=WEIGHT_DECAY)
criterion = nn.CrossEntropyLoss()

# ==========================================
# 3. BOUCLE D'ENTRAÎNEMENT
# ==========================================
print(f"🚀 Début de l'entraînement pour le mode : {mode_name}")

for epoch in range(EPOCHS):
    model.train()
    running_loss = 0.0
    
    for batch_z, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_z)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item() * batch_z.size(0)
        
    epoch_loss = running_loss / len(train_loader.dataset)
    
    if (epoch + 1) == 1 or (epoch + 1) % PRINT_LOSS_EVERY == 0:
        print(f"Epoch [{epoch+1:3d}/{EPOCHS}] | Train Loss : {epoch_loss:.4f}", end="")
        
        if (epoch + 1) % EVAL_EVERY_N_EPOCHS == 0:
            model.eval()
            with torch.no_grad():
                test_outputs = model(Z_test_concat)
                _, predicted = torch.max(test_outputs.data, 1)
                acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
            print(f" | Test Acc : {acc:.4f}")
        else:
            print() 

# ==========================================
# 4. ÉVALUATION FINALE ET SAUVEGARDE
# ==========================================
model.eval()
with torch.no_grad():
    test_outputs = model(Z_test_concat)
    _, predicted = torch.max(test_outputs.data, 1)
    final_acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)

df_results.loc[mode_name, "Test Accuracy"] = round(final_acc, 3)

print("\n" + "="*40)
print(f"🏆 Précision finale sur le Test Set : {final_acc:.3f}")
print("="*40)

display(df_results)

🚀 Début de l'entraînement pour le mode : attention_per_scale_var_flatten
Epoch [  1/1000] | Train Loss : 2.6025
Epoch [  5/1000] | Train Loss : 2.1316
Epoch [ 10/1000] | Train Loss : 1.9188 | Test Acc : 0.3982
Epoch [ 15/1000] | Train Loss : 1.7961
Epoch [ 20/1000] | Train Loss : 1.6944 | Test Acc : 0.4619
Epoch [ 25/1000] | Train Loss : 1.6112
Epoch [ 30/1000] | Train Loss : 1.5413 | Test Acc : 0.5109
Epoch [ 35/1000] | Train Loss : 1.4774
Epoch [ 40/1000] | Train Loss : 1.4211 | Test Acc : 0.5377
Epoch [ 45/1000] | Train Loss : 1.3729
Epoch [ 50/1000] | Train Loss : 1.3335 | Test Acc : 0.5547
Epoch [ 55/1000] | Train Loss : 1.2974
Epoch [ 60/1000] | Train Loss : 1.2653 | Test Acc : 0.5750
Epoch [ 65/1000] | Train Loss : 1.2401
Epoch [ 70/1000] | Train Loss : 1.2110 | Test Acc : 0.5880
Epoch [ 75/1000] | Train Loss : 1.1876
Epoch [ 80/1000] | Train Loss : 1.1676 | Test Acc : 0.5945
Epoch [ 85/1000] | Train Loss : 1.1472
Epoch [ 90/1000] | Train Loss : 1.1290 | Test Acc : 0.6010
Epoch [ 95/1000] | Train Loss : 1.1135
Epoch [100/1000] | Train Loss : 1.1005 | Test Acc : 0.6058
Epoch [105/1000] | Train Loss : 1.0854
Epoch [110/1000] | Train Loss : 1.0689 | Test Acc : 0.6111
Epoch [115/1000] | Train Loss : 1.0605
Epoch [120/1000] | Train Loss : 1.0432 | Test Acc : 0.6127
Epoch [125/1000] | Train Loss : 1.0283
Epoch [130/1000] | Train Loss : 1.0215 | Test Acc : 0.6131

KeyboardInterrupt:

TODO :
- target_dim?
- result diff de maxime car moi moi pytorch pour reglog