In [1]:

import numpy as np

from tslearn.datasets import UCR_UEA_datasets
import torch
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from sklearn.linear_model import LogisticRegression
from torch.utils.data import TensorDataset, DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from uni2ts.model.moirai import MoiraiModule
import torch.nn as nn
import torch.optim as optim
from sklearn.linear_model import RidgeClassifierCV
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
#import seaborn as sns

from encoder import MoiraiEncoder

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Utils

In [2]:
PATCH_SIZES = [8, 16, 32, 64]

SIZE = "small"
DEVICE = "cuda"
NUM_VARS = 6

DO_MASK = True
KEEP_MASK_EMBEDDING = True

In [3]:
def preprocess_data(
    data: np.ndarray,
    *,
    device: str | torch.device = "cpu",
    dtype: torch.dtype = torch.float32,
):
    """
    data: np.ndarray of shape (N, T, V) = (n_individual, time, variate)
    Assumes NO missing values and NO padding in the raw data.
    """

    if not isinstance(data, np.ndarray):
        raise TypeError("data must be a numpy.ndarray")
    if data.ndim != 3:
        raise ValueError(f"Expected shape (N,T,V), got {data.shape}")

    N, T, V = data.shape

    # (N,T,V)
    past_target = torch.as_tensor(data, dtype=dtype, device=device)

    # observed mask: (N,T,V) all True no missing values
    past_observed_target = torch.ones((N, T, V), dtype=torch.bool, device=device)

    # padding mask: (N,T) all if no padding
    past_is_pad = torch.zeros((N, T), dtype=torch.bool, device=device)

    return past_target, past_observed_target, past_is_pad

In [4]:
def apply_pooling_pt(Z_tensor, method, num_vars=NUM_VARS):
    N, S, F = Z_tensor.shape
    P = S // num_vars # Calcul automatique du nombre de patches par variable
    
    # On reshape le tenseur pour séparer les Variables et les Patches
    # Forme résultante : (Batch, Variables, Patches, Features)
    Z_reshaped = Z_tensor.view(N, num_vars, P, F)
    
    # Basique et Global
    if method == "flatten":
        return Z_tensor.reshape(N, -1)
        
    elif method == "global_mean":
        return Z_tensor.mean(dim=1)
        
    elif method == "global_max":
        return Z_tensor.max(dim=1).values
        
    elif method == "global_min":
        return Z_tensor.min(dim=1).values
    
    elif method == "global_mean_max_min":
        return torch.cat([
            Z_tensor.mean(dim=1),
            Z_tensor.max(dim=1).values,
            Z_tensor.min(dim=1).values
        ], dim=1)

    # Pooling sur les Patches (on garde les variables distinctes) ---
    # Réduction sur la dimension 2 (Patches). Résultat : (N, num_vars, F), puis on aplatit
    elif method == "mean_over_patches":
        return Z_reshaped.mean(dim=2).reshape(N, -1)
        
    elif method == "max_over_patches":
        return Z_reshaped.max(dim=2).values.reshape(N, -1)
        
    elif method == "min_over_patches":
        return Z_reshaped.min(dim=2).values.reshape(N, -1)
        
    elif method == "mean_max_min_over_patches":
        p_mean = Z_reshaped.mean(dim=2).reshape(N, -1)
        p_max  = Z_reshaped.max(dim=2).values.reshape(N, -1)
        p_min  = Z_reshaped.min(dim=2).values.reshape(N, -1)
        return torch.cat([p_mean, p_max, p_min], dim=1)

    # Pooling sur les Variables (on synchronise les patches entre variables) ---
    # Réduction sur la dimension 1 (Variables). Résultat : (N, P, F), puis on aplatit
    elif method == "mean_over_variables":
        return Z_reshaped.mean(dim=1).reshape(N, -1)
        
    elif method == "max_over_variables":
        return Z_reshaped.max(dim=1).values.reshape(N, -1)
        
    elif method == "min_over_variables":
        return Z_reshaped.min(dim=1).values.reshape(N, -1)
        
    elif method == "mean_max_min_over_variables":
        v_mean = Z_reshaped.mean(dim=1).reshape(N, -1)
        v_max  = Z_reshaped.max(dim=1).values.reshape(N, -1)
        v_min  = Z_reshaped.min(dim=1).values.reshape(N, -1)
        return torch.cat([v_mean, v_max, v_min], dim=1)

    else:
        raise ValueError(f"Method {method} unknow")

pooling_methods = [
    "flatten", 
    "global_mean", "global_max", "global_min", "global_mean_max_min",
    "mean_over_patches", "max_over_patches", "min_over_patches", "mean_max_min_over_patches",
    "mean_over_variables", "max_over_variables", "min_over_variables", "mean_max_min_over_variables"
]

In [5]:
alphas_to_test = [0.1,1,10,30,100,300,1000,10000]

models = {
    'Ridge': RidgeClassifierCV(alphas=alphas_to_test, cv=3),
    'RandomForest': RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
}

# Data

Import

In [6]:
ds = UCR_UEA_datasets()
X_train, y_train, X_test, y_test = ds.load_dataset("LSST")

n_classes = len(set(y_train))
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

y_train_tensor = torch.tensor(y_train, dtype=torch.long, device=DEVICE)
y_test_tensor = torch.tensor(y_test, dtype=torch.long, device=DEVICE)

NUM_CLASSES = len(torch.unique(y_train_tensor))

Prepare data

In [7]:
X_train_target_tensor, X_train_is_target_observed, X_train_is_target_padded = (
    preprocess_data(X_train, device=DEVICE)
)

X_test_target_tensor, X_test_is_target_observed, X_test_is_target_padded = (
    preprocess_data(X_test, device=DEVICE)
)
y_train_tensor = torch.tensor(y_train, dtype=torch.long, device=DEVICE)
y_test_tensor = torch.tensor(y_test, dtype=torch.long, device=DEVICE)

num_classes = len(torch.unique(y_train_tensor))
NUM_VARS = 6

print(X_train_target_tensor.shape)
print(X_train_is_target_observed.shape)
print(X_train_is_target_padded.shape)

torch.Size([2459, 36, 6])
torch.Size([2459, 36, 6])
torch.Size([2459, 36])

Creat Z_train and Z_test for each patch size

In [8]:
Z_train_patch = {}
Z_test_patch = {}
for patch in PATCH_SIZES:
    
    # 1. Définir les paramètres et l'encodeur pour la taille de patch actuelle
    MODEL_PARAMS = {
        "patch_size": patch,
        "num_samples": 100,
        "target_dim": 6,
        "feat_dynamic_real_dim": 0,
        "past_feat_dynamic_real_dim": 0,
    }
    if DO_MASK == True:
        prediction_length = patch
    else:
        prediction_length = 0
    encoder = MoiraiEncoder(
        module=MoiraiModule.from_pretrained(f"Salesforce/moirai-1.1-R-{SIZE}"),
        prediction_length=prediction_length,
        context_length=36,
        **MODEL_PARAMS,
    )
    encoder.eval()
    encoder.to(DEVICE)
    
    # 2. Extraire les embeddings (Z_train et Z_test)
    with torch.no_grad():
        Z_train = encoder(
            past_target=X_train_target_tensor,
            past_observed_target=X_train_is_target_observed,
            past_is_pad=X_train_is_target_padded,
        )
        Z_test = encoder(
            past_target=X_test_target_tensor,
            past_observed_target=X_test_is_target_observed,
            past_is_pad=X_test_is_target_padded,
        )
        
    if DO_MASK and not KEEP_MASK_EMBEDDING:
        N, S, F = Z_train.shape
        P = S // NUM_VARS  # Nombre de patchs par variable (Contexte + 1 Masque)
        
        # On reshape pour séparer les variables et les patchs : (Batch, 6 vars, Patchs, Features)
        Z_train_reshaped = Z_train.view(N, NUM_VARS, P, F)
        Z_test_reshaped = Z_test.view(Z_test.shape[0], NUM_VARS, P, F) # Attention à bien récupérer N_test = Z_test.shape[0]
        
        # On slice pour enlever le dernier patch (:-1) sur la dimension des patchs (dim=2)
        Z_train_no_mask = Z_train_reshaped[:, :, :-1, :]
        Z_test_no_mask = Z_test_reshaped[:, :, :-1, :]
        
        # On remet sous la forme attendue (Batch, Séquence_sans_masques, Features)
        Z_train = Z_train_no_mask.reshape(N, -1, F)
        Z_test = Z_test_no_mask.reshape(Z_test.shape[0], -1, F)



    Z_train_patch[patch] = Z_train
    Z_test_patch[patch] = Z_test

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [9]:

print(f"{'Patch Size':<12} | {'Train Shape':<25} | {'Test Shape':<25}")
for patch in PATCH_SIZES:
    train_tensor = Z_train_patch[patch]
    test_tensor = Z_test_patch[patch]
    print(f"{patch:<12} | {str(list(train_tensor.shape)):<25} | {str(list(test_tensor.shape)):<25}")

Patch Size   | Train Shape               | Test Shape
8            | [2459, 36, 384]           | [2466, 36, 384]
16           | [2459, 24, 384]           | [2466, 24, 384]
32           | [2459, 18, 384]           | [2466, 18, 384]
64           | [2459, 12, 384]           | [2466, 12, 384]

# Basic pooling with logistic regression and random forest

## Single patch size pooling

We started by applying simple pooling techniques (max, min, or mean) and comparing their performance across various patch sizes. Specifically, we evaluated whether to apply this pooling globally across all patches, locally within a single series, or across corresponding patches from all series.

### Training

We creat a dataframe to stock the results and we fill it

In [10]:
results_dfs = {
    model_name: pd.DataFrame(index=pooling_methods, columns=PATCH_SIZES)
    for model_name in models.keys()
}
for df in results_dfs.values():
    df.index.name = "Pooling \\ Patch"

We train

In [11]:
for patch in PATCH_SIZES:
    Z_train = Z_train_patch[patch].to(DEVICE)
    Z_test = Z_test_patch[patch].to(DEVICE)
    
    for pool in pooling_methods:
        X_train_pool = apply_pooling_pt(Z_train, pool).cpu().numpy()
        X_test_pool = apply_pooling_pt(Z_test, pool).cpu().numpy()

        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train_pool)
        X_test_scaled = scaler.transform(X_test_pool)
        
        for model_name, clf in models.items():
            clf.fit(X_train_scaled, y_train)
            
            y_pred = clf.predict(X_test_scaled)
            acc = accuracy_score(y_test, y_pred)
            
            results_dfs[model_name].loc[pool, patch] = round(acc, 3)

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=2.96243e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=2.99794e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=2.95261e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.36704e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.37841e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.35784e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.57836e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.6041e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.54891e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.69446e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.92684e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.72995e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.48717e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.70362e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.61865e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:228: LinAlgWarning: Ill-conditioned matrix (rcond=5.00829e-08): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.79612e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.74796e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.83876e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.57468e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.41627e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.50492e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.88766e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.86009e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.93979e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

### Results

In [12]:
for model_name, df in results_dfs.items():
    print(f"RÉSULTATS POUR : {model_name.upper()}")
    display(df.astype(float))
    
    best_acc = df.max().max()
    best_pool, best_patch = df.astype(float).stack().idxmax()
    print(f"Meilleure combinaison = Patch: {best_patch} | Pooling: '{best_pool}' | Acc: {best_acc:.3f}\n")

RÉSULTATS POUR : RIDGE

                                8      16     32     64
Pooling \ Patch
flatten                      0.608  0.625  0.620  0.633
global_mean                  0.586  0.590  0.583  0.598
global_max                   0.544  0.552  0.536  0.578
global_min                   0.545  0.553  0.538  0.565
global_mean_max_min          0.577  0.581  0.577  0.594
mean_over_patches            0.617  0.623  0.619  0.636
max_over_patches             0.590  0.610  0.601  0.632
min_over_patches             0.589  0.605  0.603  0.632
mean_max_min_over_patches    0.611  0.631  0.626  0.633
mean_over_variables          0.593  0.593  0.578  0.585
max_over_variables           0.569  0.569  0.554  0.578
min_over_variables           0.577  0.571  0.545  0.582
mean_max_min_over_variables  0.601  0.589  0.571  0.590

Meilleure combinaison = Patch: 64 | Pooling: 'mean_over_patches' | Acc: 0.636

RÉSULTATS POUR : RANDOMFOREST

                                8      16     32     64
Pooling \ Patch
flatten                      0.567  0.553  0.551  0.592
global_mean                  0.574  0.576  0.559  0.579
global_max                   0.546  0.522  0.521  0.564
global_min                   0.523  0.528  0.515  0.565
global_mean_max_min          0.571  0.573  0.547  0.580
mean_over_patches            0.591  0.578  0.559  0.602
max_over_patches             0.565  0.566  0.552  0.597
min_over_patches             0.559  0.559  0.552  0.597
mean_max_min_over_patches    0.581  0.573  0.564  0.599
mean_over_variables          0.554  0.543  0.537  0.575
max_over_variables           0.530  0.514  0.511  0.569
min_over_variables           0.525  0.523  0.510  0.560
mean_max_min_over_variables  0.556  0.547  0.531  0.572

Meilleure combinaison = Patch: 64 | Pooling: 'mean_over_patches' | Acc: 0.602

df_ridge_plot = df_results_ridge.astype(float)
df_rf_plot = df_results_rf.astype(float)


fig, axes = plt.subplots(1, 2, figsize=(20, 10), sharey=True)

cmap = "YlGnBu"

sns.heatmap(df_ridge_plot, 
            annot=True,
            fmt=".3f",
            cmap=cmap,
            linewidths=0.5,
            ax=axes[0],
            cbar_kws={'label': 'Accuracy'})
axes[0].set_title("Single Patch Pooling - Accuracy (Ridge)", fontsize=16, fontweight='bold', pad=15)
axes[0].set_xlabel("Patch Size", fontsize=14)
axes[0].set_ylabel("Pooling Method", fontsize=14)
axes[0].tick_params(axis='both', which='major', labelsize=12)

sns.heatmap(df_rf_plot, 
            annot=True, 
            fmt=".3f", 
            cmap=cmap, 
            linewidths=0.5, 
            ax=axes[1], 
            cbar_kws={'label': 'Accuracy'})
axes[1].set_title("Single Patch Pooling - Accuracy (Random Forest)", fontsize=16, fontweight='bold', pad=15)
axes[1].set_xlabel("Patch Size", fontsize=14)
axes[1].tick_params(axis='both', which='major', labelsize=12)

plt.tight_layout()

plt.show()

Pooling over patches rather than series produces the highest accuracy.

## Multi Patch pooling

### Training

In [13]:
df_multiscale_results = pd.DataFrame(index=pooling_methods, columns=models.keys())
df_multiscale_results.index.name = "Pooling Method"

for pool in pooling_methods:
    X_train_multi = []
    X_test_multi = []
    
    for patch in PATCH_SIZES:
        Z_train = Z_train_patch[patch].to(DEVICE)
        Z_test = Z_test_patch[patch].to(DEVICE)
        
        X_train_pool = apply_pooling_pt(Z_train, pool).cpu().numpy()
        X_test_pool = apply_pooling_pt(Z_test, pool).cpu().numpy()
        
        X_train_multi.append(X_train_pool)
        X_test_multi.append(X_test_pool)
        
    X_train_combined = np.concatenate(X_train_multi, axis=1)
    X_test_combined = np.concatenate(X_test_multi, axis=1)
    
    scaler = StandardScaler()
    X_train_combined_scaled = scaler.fit_transform(X_train_combined)
    X_test_combined_scaled = scaler.transform(X_test_combined)

    for model_name, clf in models.items():
        clf.fit(X_train_combined_scaled, y_train)
        
        y_pred = clf.predict(X_test_combined_scaled)
        acc = accuracy_score(y_test, y_pred)
        
        df_multiscale_results.loc[pool, model_name] = round(acc, 3)

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.40241e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.42041e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.37498e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:228: LinAlgWarning: Ill-conditioned matrix (rcond=1.93437e-08): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:228: LinAlgWarning: Ill-conditioned matrix (rcond=3.27096e-08): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:228: LinAlgWarning: Ill-conditioned matrix (rcond=3.04643e-08): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.41731e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.51254e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.4663e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=2.91889e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.17843e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.00851e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.81234e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.86106e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.76852e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.90541e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.91834e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.82939e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.23847e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.19952e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.21664e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.02706e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.41847e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.22329e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.83316e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.83658e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.73767e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.83893e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.83468e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.85096e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

### Results

In [14]:
display(df_multiscale_results.astype(float))

best_acc = df_multiscale_results.max().max()
best_pool = df_multiscale_results.max(axis=1).idxmax()
best_model = df_multiscale_results.max(axis=0).idxmax()

print("MEILLEURE COMBINAISON MULTI-ÉCHELLE :")
print(f"Modèle : '{best_model}' | Pooling : '{best_pool}'")
print(f"Précision maximale : {best_acc:.3f}")

                             Ridge  RandomForest
Pooling Method
flatten                      0.649         0.580
global_mean                  0.623         0.594
global_max                   0.591         0.564
global_min                   0.587         0.562
global_mean_max_min          0.612         0.590
mean_over_patches            0.658         0.608
max_over_patches             0.659         0.591
min_over_patches             0.650         0.596
mean_max_min_over_patches    0.664         0.599
mean_over_variables          0.625         0.571
max_over_variables           0.621         0.552
min_over_variables           0.622         0.557
mean_max_min_over_variables  0.632         0.567

MEILLEURE COMBINAISON MULTI-ÉCHELLE :
Modèle : 'Ridge' | Pooling : 'mean_max_min_over_patches'
Précision maximale : 0.664

## Conclusion

pool over patch -> good
16 -> (max, mean, min) > flatten -> position not importante
multi patch -> good

# Advanced Pooling

## Attention Pooling

In [58]:
import copy
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim.lr_scheduler import ReduceLROnPlateau
from tqdm.auto import tqdm

def train_and_evaluate_attention(
    model, 
    train_loader, 
    test_loader, 
    epochs=1000, 
    lr=1e-4, 
    weight_decay=1e-4,
    optimizer_name="Adam",
    scheduler_patience=50,
    early_stopping_patience=300,
    device="cuda",
    verbose=True
):
    """
    Boucle d'entraînement robuste spécifiquement adaptée pour les modèles d'attention
    qui prennent des embeddings pré-calculés (Z_concat) en entrée.
    """
    model.to(device)
    criterion = nn.CrossEntropyLoss()
    
    # 1. Sélection de l'optimiseur
    if optimizer_name.lower() == "adamw":
        optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
    elif optimizer_name.lower() == "adam":
        optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    else:
        raise ValueError(f"Optimizer {optimizer_name} non supporté.")
        
    # 2. Scheduler
    scheduler = ReduceLROnPlateau(optimizer, mode='max', factor=0.7, patience=scheduler_patience)
    
    # 3. Suivi et Checkpointing
    history = {'train_loss': [], 'test_loss': [], 'test_acc': [], 'lr': []}
    best_acc = 0.0
    best_model_weights = copy.deepcopy(model.state_dict())
    epochs_no_improve = 0
    
    for epoch in range(epochs):
        model.train()
        total_train_loss = 0.0
        
        # --- ENTRAÎNEMENT ---
        # Remarquez que le DataLoader renvoie (batch_z, batch_y)
        train_bar = tqdm(train_loader, desc=f"Epoch {epoch+1:03d}/{epochs} [Train]", leave=False, disable=not verbose)
        for batch_z, batch_y in train_bar:
            batch_z, batch_y = batch_z.to(device), batch_y.to(device)
            
            optimizer.zero_grad()
            logits = model(batch_z)
            loss = criterion(logits, batch_y)
            loss.backward()
            optimizer.step()
            
            total_train_loss += loss.item() * batch_y.size(0)
            
        avg_train_loss = total_train_loss / len(train_loader.dataset)
        
        # --- ÉVALUATION ---
        model.eval()
        total_test_loss = 0.0
        correct, total = 0, 0
        
        test_bar = tqdm(test_loader, desc=f"Epoch {epoch+1:03d}/{epochs} [Test]", leave=False, disable=not verbose)
        with torch.no_grad():
            for batch_z, batch_y in test_bar:
                batch_z, batch_y = batch_z.to(device), batch_y.to(device)
                
                logits = model(batch_z)
                loss = criterion(logits, batch_y)
                total_test_loss += loss.item() * batch_y.size(0)
                
                predictions = torch.argmax(logits, dim=-1)
                correct += (predictions == batch_y).sum().item()
                total += batch_y.size(0)
                
        avg_test_loss = total_test_loss / total
        test_acc = correct / total
        
        # Mise à jour du Scheduler
        scheduler.step(test_acc)
        current_lr = optimizer.param_groups[0]['lr']
        
        # Sauvegarde de l'historique
        history['train_loss'].append(avg_train_loss)
        history['test_loss'].append(avg_test_loss)
        history['test_acc'].append(test_acc)
        history['lr'].append(current_lr)
        
        if verbose and ((epoch + 1) % 10 == 0 or epoch == 0):
            print(f"Epoch {epoch+1:03d}/{epochs} | "
                  f"Train Loss: {avg_train_loss:.4f} | "
                  f"Test Loss: {avg_test_loss:.4f} | "
                  f"Test Acc: {test_acc:.4f} | "
                  f"LR: {current_lr:.2e}")
            
        # --- EARLY STOPPING & CHECKPOINTING ---
        if test_acc > best_acc:
            best_acc = test_acc
            best_model_weights = copy.deepcopy(model.state_dict())
            epochs_no_improve = 0
        else:
            epochs_no_improve += 1
            
        if epochs_no_improve >= early_stopping_patience:
            if verbose:
                print(f"\n[!] Early stopping déclenché après {epoch+1} époques.")
            break
            
    # Chargement des poids du MEILLEUR modèle avant de le retourner
    model.load_state_dict(best_model_weights)
    if verbose:
        print(f"--- Entraînement Terminé. Meilleure Test Acc: {best_acc:.4f} ---")
        
    return history, model

In [25]:
class DynamicAttentionClassifier(nn.Module):
    def __init__(self, num_vars, num_classes, patches_counts, in_features=384, mode="global"):
        """
        patches_counts : liste du nombre de patchs par échelle (ex: [30, 18, 12, 6])
        mode : "global" (1), "per_scale" (4), "per_variable" (6), ou "per_both" (24)
        """
        super().__init__()
        self.num_vars = num_vars
        self.patches_counts = patches_counts
        self.num_scales = len(patches_counts)
        self.mode = mode
        
        if mode == "global":
            self.context = nn.Parameter(torch.randn(in_features) * 0.1)
            
        elif mode == "per_scale":
            self.context = nn.Parameter(torch.randn(self.num_scales, in_features) * 0.1)
            
        elif mode == "per_variable":
            self.context = nn.Parameter(torch.randn(self.num_vars, in_features) * 0.1)
            
        elif mode == "per_both":
            self.context = nn.Parameter(torch.randn(self.num_scales, self.num_vars, in_features) * 0.1)
            
            
        self.dropout = nn.Dropout(0.1)
        self.linear = nn.LazyLinear(num_classes)

        
    def forward(self, x):
        B = x.shape[0]
        F = x.shape[-1]
        
        split_sizes = [p * self.num_vars for p in self.patches_counts]
        x_splits = torch.split(x, split_sizes, dim=1)
        
        reshaped_splits = []
        for i, p in enumerate(self.patches_counts):
            reshaped_splits.append(x_splits[i].view(B, self.num_vars, p, F))
            
        if self.mode == "global":
            scores = torch.matmul(x, self.context)
            weights = torch.softmax(scores, dim=1).unsqueeze(-1)
            pooled = (weights * x).sum(dim=1)
            
        elif self.mode == "per_scale":
            pooled_list = []
            for i, xi in enumerate(reshaped_splits):
                xi_flat = xi.view(B, -1, F)
                scores = torch.matmul(xi_flat, self.context[i])
                weights = torch.softmax(scores, dim=1).unsqueeze(-1)
                pooled_list.append((weights * xi_flat).sum(dim=1))
            
            pooled = torch.cat(pooled_list, dim=1)
            
        elif self.mode == "per_variable":
            x_vars = torch.cat(reshaped_splits, dim=2)
            
            scores = (x_vars * self.context.view(1, self.num_vars, 1, F)).sum(dim=-1)
            weights = torch.softmax(scores, dim=2).unsqueeze(-1)
            pooled_vars = (weights * x_vars).sum(dim=2)
            pooled = pooled_vars.view(B, -1)
            
        elif self.mode == "per_both":
            pooled_list = []
            for i, xi in enumerate(reshaped_splits):
                scores = (xi * self.context[i].view(1, self.num_vars, 1, F)).sum(dim=-1)
                weights = torch.softmax(scores, dim=2).unsqueeze(-1)
                pooled_vars = (weights * xi).sum(dim=2)
                pooled_list.append(pooled_vars)
                
            pooled_all = torch.stack(pooled_list, dim=1)
            pooled = pooled_all.view(B, -1)
        
            
        return self.linear(self.dropout(pooled))

In [26]:
patch_sizes = [8, 16, 32, 64]
NUM_VARS = 6

patches_counts = [Z_train_patch[p].shape[1] // NUM_VARS for p in patch_sizes]
print(f"Nomber of patch for each scale : {patches_counts}")

Z_train_concat = torch.cat([Z_train_patch[p].to(DEVICE) for p in patch_sizes], dim=1)
Z_test_concat  = torch.cat([Z_test_patch[p].to(DEVICE) for p in patch_sizes], dim=1)

print(f"Shape Z_train: {Z_train_concat.shape}")

Nomber of patch for each scale : [6, 4, 3, 2]
Shape Z_train: torch.Size([2459, 90, 384])

In [27]:
BATCH_SIZE = 64*2**2

attention_modes = ['global', 'per_scale', 'per_variable', 'per_both']
df_results = pd.DataFrame(index=attention_modes, columns=["Test Accuracy"])
df_results.index.name = "Attention mode"

train_dataset = TensorDataset(Z_train_concat, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

test_dataset = TensorDataset(Z_test_concat, y_test_tensor)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

In [28]:
mode = "global"
model_dyn = DynamicAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    patches_counts=patches_counts, 
    mode=mode
).to(DEVICE)

# For LazyLinear
_ = model_dyn(Z_train_concat[:2].to(DEVICE))


history_dyn, best_model_dyn = train_and_evaluate_attention(
    model=model_dyn,
    train_loader=train_loader,
    test_loader=test_loader,
    epochs=1000,
    lr=1e-4,
    weight_decay=1e-6,
    scheduler_patience=15,
    early_stopping_patience=40,
    device=DEVICE,
    verbose=True
)

best_acc_dyn = max(history_dyn['test_acc'])
df_results.loc[mode, "Test Accuracy"] = round(best_acc_dyn, 3)

Epoch 001/1000 | Train Loss: 2.6142 | Test Loss: 2.5905 | Test Acc: 0.0369 | LR: 1.00e-04

Epoch 010/1000 | Train Loss: 2.3196 | Test Loss: 2.2998 | Test Acc: 0.3248 | LR: 1.00e-04

Epoch 020/1000 | Train Loss: 2.1135 | Test Loss: 2.1015 | Test Acc: 0.3159 | LR: 1.00e-04

Epoch 030/1000 | Train Loss: 2.0389 | Test Loss: 2.0324 | Test Acc: 0.3155 | LR: 5.00e-05

Epoch 040/1000 | Train Loss: 2.0093 | Test Loss: 2.0003 | Test Acc: 0.3155 | LR: 5.00e-05

[!] Early stopping déclenché après 49 époques.
--- Entraînement Terminé. Meilleure Test Acc: 0.3268 ---

In [29]:
mode = "per_scale"
model_dyn = DynamicAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    patches_counts=patches_counts, 
    mode=mode
).to(DEVICE)

# For LazyLinear
_ = model_dyn(Z_train_concat[:2].to(DEVICE))


history_dyn, best_model_dyn = train_and_evaluate_attention(
    model=model_dyn,
    train_loader=train_loader,
    test_loader=test_loader,
    epochs=1000,
    lr=1e-4,
    weight_decay=1e-6,
    scheduler_patience=15,
    early_stopping_patience=40,
    device=DEVICE,
    verbose=True
)

best_acc_dyn = max(history_dyn['test_acc'])
df_results.loc[mode, "Test Accuracy"] = round(best_acc_dyn, 3)

Epoch 001/1000 | Train Loss: 2.4681 | Test Loss: 2.3717 | Test Acc: 0.2109 | LR: 1.00e-04

Epoch 010/1000 | Train Loss: 1.8847 | Test Loss: 1.8706 | Test Acc: 0.4051 | LR: 1.00e-04

Epoch 020/1000 | Train Loss: 1.7168 | Test Loss: 1.7110 | Test Acc: 0.4599 | LR: 1.00e-04

Epoch 030/1000 | Train Loss: 1.6071 | Test Loss: 1.6054 | Test Acc: 0.4915 | LR: 1.00e-04

Epoch 040/1000 | Train Loss: 1.5244 | Test Loss: 1.5295 | Test Acc: 0.5178 | LR: 1.00e-04

Epoch 050/1000 | Train Loss: 1.4611 | Test Loss: 1.4717 | Test Acc: 0.5389 | LR: 1.00e-04

Epoch 060/1000 | Train Loss: 1.4072 | Test Loss: 1.4266 | Test Acc: 0.5503 | LR: 1.00e-04

Epoch 070/1000 | Train Loss: 1.3613 | Test Loss: 1.3908 | Test Acc: 0.5596 | LR: 1.00e-04

Epoch 080/1000 | Train Loss: 1.3275 | Test Loss: 1.3616 | Test Acc: 0.5710 | LR: 1.00e-04

Epoch 090/1000 | Train Loss: 1.2962 | Test Loss: 1.3381 | Test Acc: 0.5750 | LR: 1.00e-04

Epoch 100/1000 | Train Loss: 1.2703 | Test Loss: 1.3183 | Test Acc: 0.5787 | LR: 1.00e-04

Epoch 110/1000 | Train Loss: 1.2480 | Test Loss: 1.3020 | Test Acc: 0.5827 | LR: 1.00e-04

Epoch 120/1000 | Train Loss: 1.2299 | Test Loss: 1.2883 | Test Acc: 0.5839 | LR: 1.00e-04

Epoch 130/1000 | Train Loss: 1.2035 | Test Loss: 1.2768 | Test Acc: 0.5872 | LR: 1.00e-04

Epoch 140/1000 | Train Loss: 1.1910 | Test Loss: 1.2670 | Test Acc: 0.5912 | LR: 1.00e-04

Epoch 150/1000 | Train Loss: 1.1748 | Test Loss: 1.2588 | Test Acc: 0.5896 | LR: 1.00e-04

Epoch 160/1000 | Train Loss: 1.1572 | Test Loss: 1.2512 | Test Acc: 0.5896 | LR: 1.00e-04

Epoch 170/1000 | Train Loss: 1.1389 | Test Loss: 1.2448 | Test Acc: 0.5916 | LR: 1.00e-04

Epoch 180/1000 | Train Loss: 1.1264 | Test Loss: 1.2391 | Test Acc: 0.5941 | LR: 1.00e-04

Epoch 190/1000 | Train Loss: 1.1152 | Test Loss: 1.2342 | Test Acc: 0.5953 | LR: 1.00e-04

Epoch 200/1000 | Train Loss: 1.1049 | Test Loss: 1.2302 | Test Acc: 0.5961 | LR: 1.00e-04

Epoch 210/1000 | Train Loss: 1.0906 | Test Loss: 1.2262 | Test Acc: 0.5961 | LR: 5.00e-05

Epoch 220/1000 | Train Loss: 1.0854 | Test Loss: 1.2245 | Test Acc: 0.5973 | LR: 5.00e-05

Epoch 230/1000 | Train Loss: 1.0806 | Test Loss: 1.2231 | Test Acc: 0.5961 | LR: 2.50e-05

[!] Early stopping déclenché après 233 époques.
--- Entraînement Terminé. Meilleure Test Acc: 0.5973 ---

In [30]:
mode = "per_variable"
model_dyn = DynamicAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    patches_counts=patches_counts, 
    mode=mode
).to(DEVICE)

# For LazyLinear
_ = model_dyn(Z_train_concat[:2].to(DEVICE))


history_dyn, best_model_dyn = train_and_evaluate_attention(
    model=model_dyn,
    train_loader=train_loader,
    test_loader=test_loader,
    epochs=1000,
    lr=1e-4,
    weight_decay=1e-6,
    scheduler_patience=15,
    early_stopping_patience=40,
    device=DEVICE,
    verbose=True
)

best_acc_dyn = max(history_dyn['test_acc'])
df_results.loc[mode, "Test Accuracy"] = round(best_acc_dyn, 3)

Epoch 001/1000 | Train Loss: 2.5083 | Test Loss: 2.3824 | Test Acc: 0.3037 | LR: 1.00e-04

Epoch 010/1000 | Train Loss: 1.8837 | Test Loss: 1.8722 | Test Acc: 0.3832 | LR: 1.00e-04

Epoch 020/1000 | Train Loss: 1.6710 | Test Loss: 1.6750 | Test Acc: 0.4886 | LR: 1.00e-04

Epoch 030/1000 | Train Loss: 1.5320 | Test Loss: 1.5469 | Test Acc: 0.5219 | LR: 1.00e-04

Epoch 040/1000 | Train Loss: 1.4301 | Test Loss: 1.4615 | Test Acc: 0.5357 | LR: 1.00e-04

Epoch 050/1000 | Train Loss: 1.3578 | Test Loss: 1.4012 | Test Acc: 0.5479 | LR: 1.00e-04

Epoch 060/1000 | Train Loss: 1.2969 | Test Loss: 1.3561 | Test Acc: 0.5608 | LR: 1.00e-04

Epoch 070/1000 | Train Loss: 1.2476 | Test Loss: 1.3210 | Test Acc: 0.5730 | LR: 1.00e-04

Epoch 080/1000 | Train Loss: 1.2045 | Test Loss: 1.2931 | Test Acc: 0.5811 | LR: 1.00e-04

Epoch 090/1000 | Train Loss: 1.1668 | Test Loss: 1.2702 | Test Acc: 0.5888 | LR: 1.00e-04

Epoch 100/1000 | Train Loss: 1.1324 | Test Loss: 1.2510 | Test Acc: 0.5961 | LR: 1.00e-04

Epoch 110/1000 | Train Loss: 1.1001 | Test Loss: 1.2347 | Test Acc: 0.6006 | LR: 1.00e-04

Epoch 120/1000 | Train Loss: 1.0754 | Test Loss: 1.2215 | Test Acc: 0.6014 | LR: 1.00e-04

Epoch 130/1000 | Train Loss: 1.0491 | Test Loss: 1.2099 | Test Acc: 0.6071 | LR: 1.00e-04

Epoch 140/1000 | Train Loss: 1.0252 | Test Loss: 1.2000 | Test Acc: 0.6087 | LR: 1.00e-04

Epoch 150/1000 | Train Loss: 1.0010 | Test Loss: 1.1920 | Test Acc: 0.6123 | LR: 1.00e-04

Epoch 160/1000 | Train Loss: 0.9811 | Test Loss: 1.1846 | Test Acc: 0.6119 | LR: 1.00e-04

Epoch 170/1000 | Train Loss: 0.9571 | Test Loss: 1.1782 | Test Acc: 0.6115 | LR: 1.00e-04

Epoch 180/1000 | Train Loss: 0.9435 | Test Loss: 1.1745 | Test Acc: 0.6107 | LR: 5.00e-05

Epoch 190/1000 | Train Loss: 0.9362 | Test Loss: 1.1721 | Test Acc: 0.6115 | LR: 2.50e-05

[!] Early stopping déclenché après 197 époques.
--- Entraînement Terminé. Meilleure Test Acc: 0.6152 ---

In [31]:
mode = "per_both"
model_dyn = DynamicAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    patches_counts=patches_counts, 
    mode=mode
).to(DEVICE)

# For LazyLinear
_ = model_dyn(Z_train_concat[:2].to(DEVICE))


history_dyn, best_model_dyn = train_and_evaluate_attention(
    model=model_dyn,
    train_loader=train_loader,
    test_loader=test_loader,
    epochs=1000,
    lr=1e-4,
    weight_decay=1e-6,
    scheduler_patience=15,
    early_stopping_patience=40,
    device=DEVICE,
    verbose=True
)

best_acc_dyn = max(history_dyn['test_acc'])
df_results.loc[mode, "Test Accuracy"] = round(best_acc_dyn, 3)

Epoch 001/1000 | Train Loss: 2.4188 | Test Loss: 2.0671 | Test Acc: 0.3244 | LR: 1.00e-04

Epoch 010/1000 | Train Loss: 1.3550 | Test Loss: 1.3898 | Test Acc: 0.5612 | LR: 1.00e-04

Epoch 020/1000 | Train Loss: 1.1291 | Test Loss: 1.2353 | Test Acc: 0.6139 | LR: 1.00e-04

Epoch 030/1000 | Train Loss: 1.0011 | Test Loss: 1.1667 | Test Acc: 0.6354 | LR: 1.00e-04

Epoch 040/1000 | Train Loss: 0.9049 | Test Loss: 1.1274 | Test Acc: 0.6411 | LR: 1.00e-04

Epoch 050/1000 | Train Loss: 0.8289 | Test Loss: 1.1024 | Test Acc: 0.6419 | LR: 1.00e-04

Epoch 060/1000 | Train Loss: 0.7637 | Test Loss: 1.0869 | Test Acc: 0.6423 | LR: 1.00e-04

Epoch 070/1000 | Train Loss: 0.7098 | Test Loss: 1.0765 | Test Acc: 0.6436 | LR: 5.00e-05

Epoch 080/1000 | Train Loss: 0.6844 | Test Loss: 1.0724 | Test Acc: 0.6440 | LR: 5.00e-05

Epoch 090/1000 | Train Loss: 0.6653 | Test Loss: 1.0704 | Test Acc: 0.6464 | LR: 2.50e-05

[!] Early stopping déclenché après 91 époques.
--- Entraînement Terminé. Meilleure Test Acc: 0.6468 ---

In [32]:
display(df_results)

               Test Accuracy
Attention mode
global                 0.327
per_scale              0.597
per_variable           0.615
per_both               0.647

In [ ]:
import torch
import torch.nn as nn

class SingleScaleAttentionClassifier(nn.Module):
    def __init__(self, num_vars, num_classes, in_features=384, mode="shared_context"):
        """
        mode: 
          - "shared_context": 1 seul vecteur contexte pour les 6 variables.
          - "independent_context": 6 vecteurs contextes distincts (1 par variable).
        """
        super().__init__()
        self.num_vars = num_vars
        self.mode = mode

        if mode == "shared_context":
            # Un seul vecteur de taille F (384)
            self.context = nn.Parameter(torch.randn(in_features) * 0.1)
            
        elif mode == "independent_context":
            # Une matrice de taille (V, F) -> 6 vecteurs de taille 384
            self.context = nn.Parameter(torch.randn(num_vars, in_features) * 0.1)
            

        self.dropout = nn.Dropout(0.3)
        
        linear_in = num_vars * in_features
        self.linear = nn.Linear(linear_in, num_classes)
        

    def forward(self, x):
        # x est le tenseur d'une seule échelle (ex: patch_size=16)
        # x shape: (Batch, Séquence Totale, Features)
        B = x.shape[0]
        S = x.shape[1]
        F = x.shape[-1]
        
        P = S // self.num_vars

        x_reshaped = x.view(B, self.num_vars, P, F)
        
        # 2. Calcul des Scores d'Attention
        if self.mode == "shared_context":
            # Produit scalaire de tous les patchs avec le MÊME vecteur contexte
            # x_reshaped: (B, V, P, F) | context: (F)
            scores = torch.matmul(x_reshaped, self.context) # Résultat: (B, V, P)
            
        elif self.mode == "independent_context":

            context_view = self.context.view(1, self.num_vars, 1, F)
            scores = (x_reshaped * context_view).sum(dim=-1) # Résultat: (B, V, P)
            
        weights = torch.softmax(scores, dim=2).unsqueeze(-1) # shape: (B, V, P, 1)
        
        pooled_vars = (weights * x_reshaped).sum(dim=2) # shape: (B, V, F)
        
        pooled = pooled_vars.view(B, -1) # shape: (B, V * F)
        
        return self.linear(self.dropout(pooled))

In [ ]:
PATCH_CHOISI = 8

Z_train_16 = Z_train_patch[PATCH_CHOISI].to(DEVICE)
Z_test_16 = Z_test_patch[PATCH_CHOISI].to(DEVICE)

BATCH_SIZE = 256
train_dataset = TensorDataset(Z_train_16, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

test_dataset = TensorDataset(Z_test_16, y_test_tensor)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

model_shared = SingleScaleAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    mode="shared_context"
).to(DEVICE)

history_shared, _ = train_and_evaluate_attention(
    model=model_shared, train_loader=train_loader, test_loader=test_loader,
    epochs=2000, lr=1e-4, weight_decay=0.0005, early_stopping_patience=300, device=DEVICE, scheduler_patience=20
)


model_indep = SingleScaleAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    mode="independent_context"
).to(DEVICE)

history_indep, _ = train_and_evaluate_attention(
    model=model_indep, train_loader=train_loader, test_loader=test_loader,
    epochs=2000, lr=1e-4, weight_decay=0.0005, early_stopping_patience=300, device=DEVICE, scheduler_patience=20
)

✅ Modèle SingleScaleAttention [SHARED_CONTEXT] créé !
   ➔ Couche Linéaire : Entrée (2304) -> Sortie (14)
   ➔ Paramètres de la tête : 32,270

🚀 Entraînement : Shared Context

Epoch 001/2000 | Train Loss: 2.6483 | Test Loss: 2.4879 | Test Acc: 0.2847 | LR: 1.00e-04

Epoch 010/2000 | Train Loss: 1.9010 | Test Loss: 1.8901 | Test Acc: 0.3929 | LR: 1.00e-04

Epoch 020/2000 | Train Loss: 1.7216 | Test Loss: 1.7244 | Test Acc: 0.4578 | LR: 1.00e-04

Epoch 030/2000 | Train Loss: 1.6059 | Test Loss: 1.6161 | Test Acc: 0.4931 | LR: 1.00e-04

Epoch 040/2000 | Train Loss: 1.5115 | Test Loss: 1.5389 | Test Acc: 0.5195 | LR: 1.00e-04

Epoch 050/2000 | Train Loss: 1.4482 | Test Loss: 1.4816 | Test Acc: 0.5381 | LR: 1.00e-04

Epoch 060/2000 | Train Loss: 1.4011 | Test Loss: 1.4372 | Test Acc: 0.5466 | LR: 1.00e-04

Epoch 070/2000 | Train Loss: 1.3474 | Test Loss: 1.4028 | Test Acc: 0.5547 | LR: 1.00e-04

Epoch 080/2000 | Train Loss: 1.3137 | Test Loss: 1.3754 | Test Acc: 0.5620 | LR: 1.00e-04

Epoch 090/2000 | Train Loss: 1.2796 | Test Loss: 1.3520 | Test Acc: 0.5673 | LR: 1.00e-04

Epoch 100/2000 | Train Loss: 1.2509 | Test Loss: 1.3327 | Test Acc: 0.5730 | LR: 1.00e-04

Epoch 110/2000 | Train Loss: 1.2242 | Test Loss: 1.3162 | Test Acc: 0.5779 | LR: 1.00e-04

Epoch 120/2000 | Train Loss: 1.2065 | Test Loss: 1.3024 | Test Acc: 0.5803 | LR: 1.00e-04

Epoch 130/2000 | Train Loss: 1.1818 | Test Loss: 1.2904 | Test Acc: 0.5843 | LR: 1.00e-04

Epoch 140/2000 | Train Loss: 1.1650 | Test Loss: 1.2801 | Test Acc: 0.5819 | LR: 1.00e-04

Epoch 150/2000 | Train Loss: 1.1461 | Test Loss: 1.2709 | Test Acc: 0.5856 | LR: 1.00e-04

Epoch 160/2000 | Train Loss: 1.1308 | Test Loss: 1.2628 | Test Acc: 0.5888 | LR: 1.00e-04

Epoch 170/2000 | Train Loss: 1.1080 | Test Loss: 1.2562 | Test Acc: 0.5888 | LR: 1.00e-04

Epoch 180/2000 | Train Loss: 1.0958 | Test Loss: 1.2493 | Test Acc: 0.5892 | LR: 1.00e-04

Epoch 190/2000 | Train Loss: 1.0785 | Test Loss: 1.2438 | Test Acc: 0.5900 | LR: 1.00e-04

Epoch 200/2000 | Train Loss: 1.0646 | Test Loss: 1.2393 | Test Acc: 0.5908 | LR: 1.00e-04

Epoch 210/2000 | Train Loss: 1.0564 | Test Loss: 1.2357 | Test Acc: 0.5896 | LR: 7.00e-05

Epoch 220/2000 | Train Loss: 1.0444 | Test Loss: 1.2334 | Test Acc: 0.5884 | LR: 7.00e-05

Epoch 230/2000 | Train Loss: 1.0415 | Test Loss: 1.2306 | Test Acc: 0.5904 | LR: 4.90e-05

Epoch 240/2000 | Train Loss: 1.0243 | Test Loss: 1.2291 | Test Acc: 0.5925 | LR: 4.90e-05

Epoch 250/2000 | Train Loss: 1.0217 | Test Loss: 1.2273 | Test Acc: 0.5945 | LR: 4.90e-05

Epoch 260/2000 | Train Loss: 1.0197 | Test Loss: 1.2261 | Test Acc: 0.5937 | LR: 4.90e-05

Epoch 270/2000 | Train Loss: 1.0085 | Test Loss: 1.2247 | Test Acc: 0.5949 | LR: 3.43e-05

Epoch 280/2000 | Train Loss: 1.0053 | Test Loss: 1.2240 | Test Acc: 0.5949 | LR: 3.43e-05

Epoch 290/2000 | Train Loss: 1.0037 | Test Loss: 1.2228 | Test Acc: 0.5957 | LR: 3.43e-05

Epoch 300/2000 | Train Loss: 1.0018 | Test Loss: 1.2221 | Test Acc: 0.5965 | LR: 3.43e-05

Epoch 310/2000 | Train Loss: 1.0032 | Test Loss: 1.2212 | Test Acc: 0.5973 | LR: 3.43e-05

Epoch 320/2000 | Train Loss: 0.9973 | Test Loss: 1.2204 | Test Acc: 0.5969 | LR: 3.43e-05

Epoch 330/2000 | Train Loss: 0.9926 | Test Loss: 1.2197 | Test Acc: 0.5977 | LR: 3.43e-05

Epoch 340/2000 | Train Loss: 0.9964 | Test Loss: 1.2190 | Test Acc: 0.5969 | LR: 3.43e-05

Epoch 350/2000 | Train Loss: 0.9841 | Test Loss: 1.2183 | Test Acc: 0.5973 | LR: 3.43e-05

Epoch 360/2000 | Train Loss: 0.9890 | Test Loss: 1.2176 | Test Acc: 0.5973 | LR: 3.43e-05

Epoch 370/2000 | Train Loss: 0.9759 | Test Loss: 1.2170 | Test Acc: 0.5981 | LR: 3.43e-05

Epoch 380/2000 | Train Loss: 0.9806 | Test Loss: 1.2167 | Test Acc: 0.5977 | LR: 3.43e-05

Epoch 390/2000 | Train Loss: 0.9670 | Test Loss: 1.2163 | Test Acc: 0.5965 | LR: 3.43e-05

Epoch 400/2000 | Train Loss: 0.9790 | Test Loss: 1.2159 | Test Acc: 0.5977 | LR: 2.40e-05

Epoch 410/2000 | Train Loss: 0.9658 | Test Loss: 1.2155 | Test Acc: 0.5969 | LR: 2.40e-05

Epoch 420/2000 | Train Loss: 0.9617 | Test Loss: 1.2153 | Test Acc: 0.5965 | LR: 1.68e-05

Epoch 430/2000 | Train Loss: 0.9583 | Test Loss: 1.2149 | Test Acc: 0.5969 | LR: 1.68e-05

Epoch 440/2000 | Train Loss: 0.9583 | Test Loss: 1.2146 | Test Acc: 0.5973 | LR: 1.18e-05

Epoch 450/2000 | Train Loss: 0.9589 | Test Loss: 1.2144 | Test Acc: 0.5977 | LR: 1.18e-05

Epoch 460/2000 | Train Loss: 0.9542 | Test Loss: 1.2142 | Test Acc: 0.5977 | LR: 8.24e-06

Epoch 470/2000 | Train Loss: 0.9590 | Test Loss: 1.2141 | Test Acc: 0.5977 | LR: 8.24e-06

Epoch 480/2000 | Train Loss: 0.9505 | Test Loss: 1.2140 | Test Acc: 0.5985 | LR: 5.76e-06

Epoch 490/2000 | Train Loss: 0.9515 | Test Loss: 1.2140 | Test Acc: 0.5973 | LR: 5.76e-06

Epoch 500/2000 | Train Loss: 0.9587 | Test Loss: 1.2139 | Test Acc: 0.5981 | LR: 4.04e-06

Epoch 510/2000 | Train Loss: 0.9573 | Test Loss: 1.2138 | Test Acc: 0.5981 | LR: 4.04e-06

Epoch 520/2000 | Train Loss: 0.9579 | Test Loss: 1.2138 | Test Acc: 0.5973 | LR: 2.82e-06

Epoch 530/2000 | Train Loss: 0.9588 | Test Loss: 1.2137 | Test Acc: 0.5977 | LR: 2.82e-06

Epoch 540/2000 | Train Loss: 0.9628 | Test Loss: 1.2137 | Test Acc: 0.5981 | LR: 2.82e-06

Epoch 550/2000 | Train Loss: 0.9538 | Test Loss: 1.2136 | Test Acc: 0.5977 | LR: 1.98e-06

Epoch 560/2000 | Train Loss: 0.9596 | Test Loss: 1.2137 | Test Acc: 0.5985 | LR: 1.98e-06

Epoch 570/2000 | Train Loss: 0.9514 | Test Loss: 1.2136 | Test Acc: 0.5981 | LR: 1.38e-06

Epoch 580/2000 | Train Loss: 0.9591 | Test Loss: 1.2136 | Test Acc: 0.5977 | LR: 1.38e-06

Epoch 590/2000 | Train Loss: 0.9588 | Test Loss: 1.2136 | Test Acc: 0.5977 | LR: 9.69e-07

Epoch 600/2000 | Train Loss: 0.9545 | Test Loss: 1.2135 | Test Acc: 0.5981 | LR: 9.69e-07

Epoch 610/2000 | Train Loss: 0.9509 | Test Loss: 1.2135 | Test Acc: 0.5981 | LR: 6.78e-07

Epoch 620/2000 | Train Loss: 0.9595 | Test Loss: 1.2135 | Test Acc: 0.5981 | LR: 6.78e-07

Epoch 630/2000 | Train Loss: 0.9514 | Test Loss: 1.2135 | Test Acc: 0.5981 | LR: 4.75e-07

Epoch 640/2000 | Train Loss: 0.9479 | Test Loss: 1.2135 | Test Acc: 0.5981 | LR: 4.75e-07

Epoch 650/2000 | Train Loss: 0.9466 | Test Loss: 1.2135 | Test Acc: 0.5981 | LR: 3.32e-07

Epoch 660/2000 | Train Loss: 0.9605 | Test Loss: 1.2135 | Test Acc: 0.5981 | LR: 3.32e-07

Epoch 670/2000 | Train Loss: 0.9490 | Test Loss: 1.2135 | Test Acc: 0.5981 | LR: 2.33e-07

[!] Early stopping déclenché après 673 époques.
--- Entraînement Terminé. Meilleure Test Acc: 0.5994 ---
✅ Modèle SingleScaleAttention [INDEPENDENT_CONTEXT] créé !
   ➔ Couche Linéaire : Entrée (2304) -> Sortie (14)
   ➔ Paramètres de la tête : 32,270

🚀 Entraînement : Independent Context

Epoch 001/2000 | Train Loss: 2.6898 | Test Loss: 2.5206 | Test Acc: 0.1399 | LR: 1.00e-04

Epoch 010/2000 | Train Loss: 1.8809 | Test Loss: 1.8673 | Test Acc: 0.4019 | LR: 1.00e-04

Epoch 020/2000 | Train Loss: 1.6997 | Test Loss: 1.6998 | Test Acc: 0.4716 | LR: 1.00e-04

Epoch 030/2000 | Train Loss: 1.5797 | Test Loss: 1.5911 | Test Acc: 0.5041 | LR: 1.00e-04

Epoch 040/2000 | Train Loss: 1.4905 | Test Loss: 1.5138 | Test Acc: 0.5239 | LR: 1.00e-04

Epoch 050/2000 | Train Loss: 1.4253 | Test Loss: 1.4562 | Test Acc: 0.5401 | LR: 1.00e-04

Epoch 060/2000 | Train Loss: 1.3663 | Test Loss: 1.4124 | Test Acc: 0.5474 | LR: 1.00e-04

Epoch 070/2000 | Train Loss: 1.3250 | Test Loss: 1.3778 | Test Acc: 0.5580 | LR: 1.00e-04

Epoch 080/2000 | Train Loss: 1.2881 | Test Loss: 1.3503 | Test Acc: 0.5645 | LR: 1.00e-04

Epoch 090/2000 | Train Loss: 1.2483 | Test Loss: 1.3278 | Test Acc: 0.5730 | LR: 1.00e-04

Epoch 100/2000 | Train Loss: 1.2208 | Test Loss: 1.3091 | Test Acc: 0.5766 | LR: 1.00e-04

Epoch 110/2000 | Train Loss: 1.1889 | Test Loss: 1.2930 | Test Acc: 0.5815 | LR: 1.00e-04

Epoch 120/2000 | Train Loss: 1.1708 | Test Loss: 1.2801 | Test Acc: 0.5868 | LR: 1.00e-04

Epoch 130/2000 | Train Loss: 1.1582 | Test Loss: 1.2687 | Test Acc: 0.5892 | LR: 1.00e-04

Epoch 140/2000 | Train Loss: 1.1380 | Test Loss: 1.2588 | Test Acc: 0.5908 | LR: 1.00e-04

Epoch 150/2000 | Train Loss: 1.1086 | Test Loss: 1.2505 | Test Acc: 0.5896 | LR: 1.00e-04

Epoch 160/2000 | Train Loss: 1.0989 | Test Loss: 1.2428 | Test Acc: 0.5925 | LR: 1.00e-04

Epoch 170/2000 | Train Loss: 1.0744 | Test Loss: 1.2359 | Test Acc: 0.5949 | LR: 1.00e-04

Epoch 180/2000 | Train Loss: 1.0618 | Test Loss: 1.2309 | Test Acc: 0.5973 | LR: 1.00e-04

Epoch 190/2000 | Train Loss: 1.0539 | Test Loss: 1.2256 | Test Acc: 0.5961 | LR: 1.00e-04

Epoch 200/2000 | Train Loss: 1.0439 | Test Loss: 1.2212 | Test Acc: 0.5981 | LR: 1.00e-04

Epoch 210/2000 | Train Loss: 1.0195 | Test Loss: 1.2172 | Test Acc: 0.5981 | LR: 7.00e-05

Epoch 220/2000 | Train Loss: 1.0184 | Test Loss: 1.2148 | Test Acc: 0.5977 | LR: 7.00e-05

Epoch 230/2000 | Train Loss: 1.0073 | Test Loss: 1.2120 | Test Acc: 0.5994 | LR: 7.00e-05

Epoch 240/2000 | Train Loss: 1.0025 | Test Loss: 1.2101 | Test Acc: 0.6010 | LR: 4.90e-05

Epoch 250/2000 | Train Loss: 0.9972 | Test Loss: 1.2094 | Test Acc: 0.5998 | LR: 4.90e-05

Epoch 260/2000 | Train Loss: 0.9945 | Test Loss: 1.2074 | Test Acc: 0.5989 | LR: 4.90e-05

Epoch 270/2000 | Train Loss: 0.9885 | Test Loss: 1.2068 | Test Acc: 0.6006 | LR: 3.43e-05

Epoch 280/2000 | Train Loss: 0.9867 | Test Loss: 1.2057 | Test Acc: 0.6002 | LR: 3.43e-05

Epoch 290/2000 | Train Loss: 0.9746 | Test Loss: 1.2051 | Test Acc: 0.5998 | LR: 2.40e-05

Epoch 300/2000 | Train Loss: 0.9735 | Test Loss: 1.2044 | Test Acc: 0.6006 | LR: 2.40e-05

Epoch 310/2000 | Train Loss: 0.9765 | Test Loss: 1.2041 | Test Acc: 0.6014 | LR: 1.68e-05

Epoch 320/2000 | Train Loss: 0.9739 | Test Loss: 1.2036 | Test Acc: 0.6026 | LR: 1.68e-05

Epoch 330/2000 | Train Loss: 0.9628 | Test Loss: 1.2032 | Test Acc: 0.6022 | LR: 1.68e-05

Epoch 340/2000 | Train Loss: 0.9712 | Test Loss: 1.2029 | Test Acc: 0.6022 | LR: 1.18e-05

Epoch 350/2000 | Train Loss: 0.9609 | Test Loss: 1.2026 | Test Acc: 0.6034 | LR: 1.18e-05

Epoch 360/2000 | Train Loss: 0.9673 | Test Loss: 1.2025 | Test Acc: 0.6030 | LR: 1.18e-05

Epoch 370/2000 | Train Loss: 0.9691 | Test Loss: 1.2022 | Test Acc: 0.6030 | LR: 1.18e-05

Epoch 380/2000 | Train Loss: 0.9705 | Test Loss: 1.2019 | Test Acc: 0.6034 | LR: 8.24e-06

Epoch 390/2000 | Train Loss: 0.9671 | Test Loss: 1.2017 | Test Acc: 0.6038 | LR: 8.24e-06

Epoch 400/2000 | Train Loss: 0.9638 | Test Loss: 1.2015 | Test Acc: 0.6034 | LR: 5.76e-06

Epoch 410/2000 | Train Loss: 0.9658 | Test Loss: 1.2014 | Test Acc: 0.6042 | LR: 5.76e-06

Epoch 420/2000 | Train Loss: 0.9579 | Test Loss: 1.2013 | Test Acc: 0.6034 | LR: 5.76e-06

Epoch 430/2000 | Train Loss: 0.9673 | Test Loss: 1.2012 | Test Acc: 0.6034 | LR: 5.76e-06

Epoch 440/2000 | Train Loss: 0.9666 | Test Loss: 1.2010 | Test Acc: 0.6038 | LR: 4.04e-06

Epoch 450/2000 | Train Loss: 0.9598 | Test Loss: 1.2010 | Test Acc: 0.6038 | LR: 4.04e-06

Epoch 460/2000 | Train Loss: 0.9535 | Test Loss: 1.2009 | Test Acc: 0.6034 | LR: 2.82e-06

Epoch 470/2000 | Train Loss: 0.9605 | Test Loss: 1.2009 | Test Acc: 0.6038 | LR: 2.82e-06

Epoch 480/2000 | Train Loss: 0.9589 | Test Loss: 1.2008 | Test Acc: 0.6038 | LR: 1.98e-06

Epoch 490/2000 | Train Loss: 0.9587 | Test Loss: 1.2008 | Test Acc: 0.6042 | LR: 1.98e-06

Epoch 500/2000 | Train Loss: 0.9577 | Test Loss: 1.2007 | Test Acc: 0.6046 | LR: 1.98e-06

Epoch 510/2000 | Train Loss: 0.9659 | Test Loss: 1.2007 | Test Acc: 0.6046 | LR: 1.38e-06

Epoch 520/2000 | Train Loss: 0.9663 | Test Loss: 1.2007 | Test Acc: 0.6046 | LR: 1.38e-06

Epoch 530/2000 | Train Loss: 0.9563 | Test Loss: 1.2007 | Test Acc: 0.6046 | LR: 9.69e-07

Epoch 540/2000 | Train Loss: 0.9640 | Test Loss: 1.2006 | Test Acc: 0.6046 | LR: 9.69e-07

Epoch 550/2000 | Train Loss: 0.9606 | Test Loss: 1.2006 | Test Acc: 0.6046 | LR: 6.78e-07

Epoch 560/2000 | Train Loss: 0.9606 | Test Loss: 1.2006 | Test Acc: 0.6046 | LR: 6.78e-07

Epoch 570/2000 | Train Loss: 0.9603 | Test Loss: 1.2006 | Test Acc: 0.6046 | LR: 4.75e-07

Epoch 580/2000 | Train Loss: 0.9522 | Test Loss: 1.2006 | Test Acc: 0.6046 | LR: 4.75e-07

Epoch 590/2000 | Train Loss: 0.9635 | Test Loss: 1.2006 | Test Acc: 0.6046 | LR: 3.32e-07

Epoch 600/2000 | Train Loss: 0.9610 | Test Loss: 1.2006 | Test Acc: 0.6046 | LR: 3.32e-07

Epoch 610/2000 | Train Loss: 0.9556 | Test Loss: 1.2006 | Test Acc: 0.6046 | LR: 2.33e-07

Epoch 620/2000 | Train Loss: 0.9559 | Test Loss: 1.2006 | Test Acc: 0.6046 | LR: 2.33e-07

Epoch 630/2000 | Train Loss: 0.9638 | Test Loss: 1.2006 | Test Acc: 0.6046 | LR: 1.63e-07

Epoch 640/2000 | Train Loss: 0.9545 | Test Loss: 1.2006 | Test Acc: 0.6046 | LR: 1.63e-07

Epoch 650/2000 | Train Loss: 0.9640 | Test Loss: 1.2006 | Test Acc: 0.6046 | LR: 1.14e-07

Epoch 660/2000 | Train Loss: 0.9635 | Test Loss: 1.2005 | Test Acc: 0.6046 | LR: 1.14e-07

Epoch 670/2000 | Train Loss: 0.9642 | Test Loss: 1.2005 | Test Acc: 0.6046 | LR: 7.98e-08

Epoch 680/2000 | Train Loss: 0.9581 | Test Loss: 1.2005 | Test Acc: 0.6046 | LR: 7.98e-08

Epoch 690/2000 | Train Loss: 0.9581 | Test Loss: 1.2005 | Test Acc: 0.6046 | LR: 5.59e-08

Epoch 700/2000 | Train Loss: 0.9573 | Test Loss: 1.2005 | Test Acc: 0.6046 | LR: 5.59e-08

Epoch 710/2000 | Train Loss: 0.9699 | Test Loss: 1.2005 | Test Acc: 0.6046 | LR: 5.59e-08

[!] Early stopping déclenché après 717 époques.
--- Entraînement Terminé. Meilleure Test Acc: 0.6046 ---

In [ ]:
import torch
import torch.nn as nn

class SingleScaleMultiHeadClassifier(nn.Module):
    def __init__(self, num_vars, num_classes, in_features=384, num_heads=4, mode="shared_context"):
        """
        mode: 
          - "shared_context": 1 seul token [CLS] (Query) partagé pour lire les 6 variables.
          - "independent_context": 6 tokens [CLS] distincts (1 spécialiste par variable).
        """
        super().__init__()
        self.num_vars = num_vars
        self.mode = mode
        
        if mode == "shared_context":
            self.cls_token = nn.Parameter(torch.randn(1, 1, in_features) * 0.02)
            
        elif mode == "independent_context":
            self.cls_token = nn.Parameter(torch.randn(num_vars, 1, in_features) * 0.02)

            
        self.mha = nn.MultiheadAttention(
            embed_dim=in_features,
            num_heads=num_heads,
            dropout=0.1,
            batch_first=True 
        )
            
        self.dropout = nn.Dropout(0.3)

        linear_in = num_vars * in_features
        self.linear = nn.Linear(linear_in, num_classes)


    def forward(self, x):
        B = x.shape[0]
        S = x.shape[1]
        F = x.shape[-1]

        P = S // self.num_vars

        x_reshaped = x.view(B, self.num_vars, P, F)
        

        kv = x_reshaped.view(B * self.num_vars, P, F)
        
        if self.mode == "shared_context":
            q = self.cls_token.expand(B * self.num_vars, -1, -1)
            
        elif self.mode == "independent_context":
            q_expanded = self.cls_token.unsqueeze(0).expand(B, -1, -1, -1)
            q = q_expanded.reshape(B * self.num_vars, 1, F)
            

        attn_output, attn_weights = self.mha(query=q, key=kv, value=kv)
        

        pooled_flat = attn_output.squeeze(1) # shape: (B * V, F)
        
        pooled_vars = pooled_flat.view(B, self.num_vars, F) # shape: (B, V, F)
        
        pooled = pooled_vars.view(B, -1) # shape: (B, V * F)
        

        return self.linear(self.dropout(pooled))

In [ ]:
PATCH_CHOISI = 16

Z_train_16 = Z_train_patch[PATCH_CHOISI].to(DEVICE)
Z_test_16 = Z_test_patch[PATCH_CHOISI].to(DEVICE)

BATCH_SIZE = 256
train_dataset = TensorDataset(Z_train_16, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

test_dataset = TensorDataset(Z_test_16, y_test_tensor)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

model_mha = SingleScaleMultiHeadClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    num_heads=384, # 4 têtes d'attention
    mode="shared_context"
).to(DEVICE)

history_mha, best_mha = train_and_evaluate_attention(
    model=model_mha, 
    train_loader=train_loader, 
    test_loader=test_loader,
    epochs=1000, 
    lr=1e-4,              # LR un peu plus grand pour l'attention
    weight_decay=0.000005,    # Forte régularisation (vs Ridge)
    early_stopping_patience=100,
    scheduler_patience=30,
    device=DEVICE
)

✅ Modèle SingleScale Multi-Head Attention [SHARED_CONTEXT] créé !
   ➔ Couche Linéaire : Entrée (2304) -> Sortie (14)
   ➔ Paramètres de la tête : 32,270

🚀 Entraînement : Multi-Head Attention (Independent)

Epoch 001/1000 [Train]:   0%|          | 0/10 [00:00<?, ?it/s]

Epoch 001/1000 | Train Loss: 2.3189 | Test Loss: 2.0869 | Test Acc: 0.3175 | LR: 1.00e-04

Epoch 010/1000 | Train Loss: 1.5145 | Test Loss: 1.5172 | Test Acc: 0.5036 | LR: 1.00e-04

Epoch 020/1000 | Train Loss: 1.2453 | Test Loss: 1.2913 | Test Acc: 0.5807 | LR: 1.00e-04

Epoch 030/1000 | Train Loss: 1.1116 | Test Loss: 1.1993 | Test Acc: 0.6115 | LR: 1.00e-04

Epoch 040/1000 | Train Loss: 1.0029 | Test Loss: 1.1526 | Test Acc: 0.6241 | LR: 1.00e-04

Epoch 050/1000 | Train Loss: 0.9084 | Test Loss: 1.1266 | Test Acc: 0.6265 | LR: 1.00e-04

Epoch 060/1000 | Train Loss: 0.8031 | Test Loss: 1.1175 | Test Acc: 0.6330 | LR: 1.00e-04

Epoch 070/1000 | Train Loss: 0.6855 | Test Loss: 1.1236 | Test Acc: 0.6302 | LR: 1.00e-04

Epoch 080/1000 | Train Loss: 0.5606 | Test Loss: 1.1452 | Test Acc: 0.6298 | LR: 1.00e-04

Epoch 090/1000 | Train Loss: 0.4467 | Test Loss: 1.1835 | Test Acc: 0.6212 | LR: 1.00e-04

Epoch 100/1000 | Train Loss: 0.3440 | Test Loss: 1.2242 | Test Acc: 0.6204 | LR: 7.00e-05

Epoch 110/1000 | Train Loss: 0.2723 | Test Loss: 1.2698 | Test Acc: 0.6164 | LR: 7.00e-05

Epoch 120/1000 | Train Loss: 0.2054 | Test Loss: 1.3179 | Test Acc: 0.6160 | LR: 7.00e-05

Epoch 130/1000 | Train Loss: 0.1611 | Test Loss: 1.3668 | Test Acc: 0.6152 | LR: 4.90e-05

Epoch 140/1000 | Train Loss: 0.1321 | Test Loss: 1.4038 | Test Acc: 0.6127 | LR: 4.90e-05

Epoch 150/1000 | Train Loss: 0.1003 | Test Loss: 1.4435 | Test Acc: 0.6115 | LR: 4.90e-05

Epoch 160/1000 | Train Loss: 0.0884 | Test Loss: 1.4813 | Test Acc: 0.6127 | LR: 3.43e-05

[!] Early stopping déclenché après 162 époques.
--- Entraînement Terminé. Meilleure Test Acc: 0.6358 ---

In [ ]:
import torch
import torch.nn as nn

class HierarchicalAttentionClassifier(nn.Module):
    def __init__(self, num_vars, num_classes, in_features=384, patch_mode="independent_context"):
        super().__init__()
        self.num_vars = num_vars
        self.patch_mode = patch_mode

        if patch_mode == "shared_context":
            self.patch_context = nn.Parameter(torch.randn(in_features) * 0.1)
        elif patch_mode == "independent_context":
            self.patch_context = nn.Parameter(torch.randn(num_vars, in_features) * 0.1)

            

        self.var_context = nn.Parameter(torch.randn(in_features) * 0.1)
        
        self.dropout = nn.Dropout(0.3)
        

        self.linear = nn.Linear(in_features, num_classes)
        


    def forward(self, x):
        B = x.shape[0]
        S = x.shape[1]
        F = x.shape[-1]
        
        P = S // self.num_vars
        x_reshaped = x.view(B, self.num_vars, P, F)
        
        if self.patch_mode == "shared_context":
            patch_scores = torch.matmul(x_reshaped, self.patch_context) # (B, V, P)
        elif self.patch_mode == "independent_context":
            context_view = self.patch_context.view(1, self.num_vars, 1, F)
            patch_scores = (x_reshaped * context_view).sum(dim=-1) # (B, V, P)
            
        patch_weights = torch.softmax(patch_scores, dim=2).unsqueeze(-1) # (B, V, P, 1)

        var_reprs = (patch_weights * x_reshaped).sum(dim=2) # shape: (B, V, F)
        

        var_scores = torch.matmul(var_reprs, self.var_context)
        

        var_weights = torch.softmax(var_scores, dim=1).unsqueeze(-1)

        global_repr = (var_weights * var_reprs).sum(dim=1) # shape: (B, F)

        return self.linear(self.dropout(global_repr))

In [ ]:
PATCH_CHOISI = 16

Z_train_16 = Z_train_patch[PATCH_CHOISI].to(DEVICE)
Z_test_16 = Z_test_patch[PATCH_CHOISI].to(DEVICE)

BATCH_SIZE = 256
train_loader = DataLoader(TensorDataset(Z_train_16, y_train_tensor), batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(TensorDataset(Z_test_16, y_test_tensor), batch_size=BATCH_SIZE, shuffle=False)

model_hierarchical = HierarchicalAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    patch_mode="independent_context" 
).to(DEVICE)

history_hierarchical, best_hierarchical = train_and_evaluate_attention(
    model=model_hierarchical, 
    train_loader=train_loader, 
    test_loader=test_loader,
    epochs=1000, 
    lr=1e-3,
    weight_decay=0.0000000000000005,
    early_stopping_patience=100,
    scheduler_patience=30,
    device=DEVICE
)

✅ Modèle Hierarchical Attention (Patch: INDEPENDENT_CONTEXT) créé !
   ➔ Couche Linéaire : Entrée (384) -> Sortie (14)
   ➔ Paramètres de la tête : 5,390

🚀 Entraînement : Hierarchical Attention (Patch -> Variables)

Epoch 001/1000 | Train Loss: 2.4749 | Test Loss: 2.2701 | Test Acc: 0.3508 | LR: 1.00e-03

Epoch 010/1000 | Train Loss: 1.7028 | Test Loss: 1.6611 | Test Acc: 0.4676 | LR: 1.00e-03

Epoch 020/1000 | Train Loss: 1.5129 | Test Loss: 1.4937 | Test Acc: 0.5211 | LR: 1.00e-03

Epoch 030/1000 | Train Loss: 1.4137 | Test Loss: 1.4149 | Test Acc: 0.5426 | LR: 1.00e-03

Epoch 040/1000 | Train Loss: 1.3447 | Test Loss: 1.3722 | Test Acc: 0.5539 | LR: 1.00e-03

Epoch 050/1000 | Train Loss: 1.2824 | Test Loss: 1.3486 | Test Acc: 0.5669 | LR: 1.00e-03

Epoch 060/1000 | Train Loss: 1.2466 | Test Loss: 1.3340 | Test Acc: 0.5750 | LR: 1.00e-03

Epoch 070/1000 | Train Loss: 1.2112 | Test Loss: 1.3256 | Test Acc: 0.5754 | LR: 1.00e-03

Epoch 080/1000 | Train Loss: 1.1876 | Test Loss: 1.3202 | Test Acc: 0.5766 | LR: 1.00e-03

Epoch 090/1000 | Train Loss: 1.1731 | Test Loss: 1.3187 | Test Acc: 0.5734 | LR: 1.00e-03

Epoch 100/1000 | Train Loss: 1.1372 | Test Loss: 1.3197 | Test Acc: 0.5706 | LR: 7.00e-04

Epoch 110/1000 | Train Loss: 1.1211 | Test Loss: 1.3224 | Test Acc: 0.5697 | LR: 7.00e-04

Epoch 120/1000 | Train Loss: 1.1015 | Test Loss: 1.3222 | Test Acc: 0.5697 | LR: 7.00e-04

Epoch 130/1000 | Train Loss: 1.0941 | Test Loss: 1.3255 | Test Acc: 0.5681 | LR: 4.90e-04

Epoch 140/1000 | Train Loss: 1.0836 | Test Loss: 1.3272 | Test Acc: 0.5689 | LR: 4.90e-04

Epoch 150/1000 | Train Loss: 1.0757 | Test Loss: 1.3298 | Test Acc: 0.5714 | LR: 4.90e-04

Epoch 160/1000 | Train Loss: 1.0631 | Test Loss: 1.3311 | Test Acc: 0.5706 | LR: 3.43e-04

[!] Early stopping déclenché après 163 époques.
--- Entraînement Terminé. Meilleure Test Acc: 0.5775 ---

In [ ]:
class HierarchicalMultiHeadClassifier(nn.Module):
    def __init__(self, num_vars, num_classes, in_features=384, num_heads=4, patch_mode="independent_context"):
        super().__init__()
        self.num_vars = num_vars
        self.patch_mode = patch_mode
        

        if patch_mode == "shared_context":
            self.patch_cls = nn.Parameter(torch.randn(1, 1, in_features) * 0.02)
        elif patch_mode == "independent_context":
            self.patch_cls = nn.Parameter(torch.randn(num_vars, 1, in_features) * 0.02)


        self.patch_mha = nn.MultiheadAttention(
            embed_dim=in_features, num_heads=num_heads, dropout=0.1, batch_first=True
        )


        self.var_cls = nn.Parameter(torch.randn(1, 1, in_features) * 0.02)

        self.var_mha = nn.MultiheadAttention(
            embed_dim=in_features, num_heads=num_heads, dropout=0.1, batch_first=True
        )

        self.dropout = nn.Dropout(0.1)

        self.linear = nn.Linear(in_features, num_classes)


    def forward(self, x):
        B = x.shape[0]
        S = x.shape[1]
        F = x.shape[-1]
        
        P = S // self.num_vars
        
        x_reshaped = x.view(B, self.num_vars, P, F)
        kv_patch = x_reshaped.view(B * self.num_vars, P, F) # (B*V, P, F)
        
        if self.patch_mode == "shared_context":
            q_patch = self.patch_cls.expand(B * self.num_vars, -1, -1)
        elif self.patch_mode == "independent_context":
            q_expanded = self.patch_cls.unsqueeze(0).expand(B, -1, -1, -1)
            q_patch = q_expanded.reshape(B * self.num_vars, 1, F)
            
        patch_attn_out, _ = self.patch_mha(query=q_patch, key=kv_patch, value=kv_patch)

        var_reprs = patch_attn_out.squeeze(1).view(B, self.num_vars, F) # (B, V, F)
        

        kv_var = var_reprs # (B, V, F)
        

        q_var = self.var_cls.expand(B, -1, -1) # (B, 1, F)

        var_attn_out, _ = self.var_mha(query=q_var, key=kv_var, value=kv_var)

        global_repr = var_attn_out.squeeze(1) # (B, F)

        return self.linear(self.dropout(global_repr))

In [ ]:
PATCH_CHOISI = 16

Z_train_16 = Z_train_patch[PATCH_CHOISI].to(DEVICE)
Z_test_16 = Z_test_patch[PATCH_CHOISI].to(DEVICE)

BATCH_SIZE = 256
train_loader = DataLoader(TensorDataset(Z_train_16, y_train_tensor), batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(TensorDataset(Z_test_16, y_test_tensor), batch_size=BATCH_SIZE, shuffle=False)

model_hierarchical_mha = HierarchicalMultiHeadClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    num_heads=384,
    patch_mode="independent_context" 
).to(DEVICE)

history_h_mha, best_h_mha = train_and_evaluate_attention(
    model=model_hierarchical_mha, 
    train_loader=train_loader, 
    test_loader=test_loader,
    epochs=1000, 
    lr=1e-4,
    weight_decay=0.000005,
    early_stopping_patience=100,
    scheduler_patience=30,
    device=DEVICE
)

✅ Modèle Hierarchical Multi-Head (Patch Mode: INDEPENDENT_CONTEXT) créé !
   ➔ Couche Linéaire : Entrée (384) -> Sortie (14)
   ➔ Paramètres de la tête : 5,390

🚀 Entraînement : Hierarchical MULTI-HEAD Attention

Epoch 001/1000 [Train]:   0%|          | 0/10 [00:00<?, ?it/s]

Epoch 001/1000 | Train Loss: 2.4727 | Test Loss: 2.2479 | Test Acc: 0.3155 | LR: 1.00e-04

Epoch 010/1000 | Train Loss: 1.6166 | Test Loss: 1.6079 | Test Acc: 0.4643 | LR: 1.00e-04

Epoch 020/1000 | Train Loss: 1.4102 | Test Loss: 1.3955 | Test Acc: 0.5434 | LR: 1.00e-04

Epoch 030/1000 | Train Loss: 1.3049 | Test Loss: 1.3017 | Test Acc: 0.5681 | LR: 1.00e-04

Epoch 040/1000 | Train Loss: 1.2115 | Test Loss: 1.2503 | Test Acc: 0.5770 | LR: 1.00e-04

Epoch 050/1000 | Train Loss: 1.1180 | Test Loss: 1.2196 | Test Acc: 0.5880 | LR: 1.00e-04

Epoch 060/1000 | Train Loss: 1.0241 | Test Loss: 1.2020 | Test Acc: 0.5916 | LR: 1.00e-04

Epoch 070/1000 | Train Loss: 0.9224 | Test Loss: 1.1956 | Test Acc: 0.5981 | LR: 1.00e-04

Epoch 080/1000 | Train Loss: 0.8121 | Test Loss: 1.2112 | Test Acc: 0.6010 | LR: 1.00e-04

Epoch 090/1000 | Train Loss: 0.7120 | Test Loss: 1.2611 | Test Acc: 0.5969 | LR: 1.00e-04

Epoch 100/1000 | Train Loss: 0.5692 | Test Loss: 1.3495 | Test Acc: 0.5900 | LR: 7.00e-05

Epoch 110/1000 | Train Loss: 0.4763 | Test Loss: 1.4493 | Test Acc: 0.5929 | LR: 7.00e-05

Epoch 120/1000 | Train Loss: 0.3816 | Test Loss: 1.5951 | Test Acc: 0.5783 | LR: 7.00e-05

Epoch 130/1000 | Train Loss: 0.2825 | Test Loss: 1.7948 | Test Acc: 0.5624 | LR: 4.90e-05

Epoch 140/1000 | Train Loss: 0.2311 | Test Loss: 1.9178 | Test Acc: 0.5637 | LR: 4.90e-05

Epoch 150/1000 | Train Loss: 0.1790 | Test Loss: 2.0785 | Test Acc: 0.5523 | LR: 4.90e-05

Epoch 160/1000 | Train Loss: 0.1405 | Test Loss: 2.2487 | Test Acc: 0.5543 | LR: 4.90e-05

[!] Early stopping déclenché après 168 époques.
--- Entraînement Terminé. Meilleure Test Acc: 0.6095 ---

TODO :
- target_dim?
- result diff de maxime car moi moi pytorch pour reglog