"""onyxia@vscode-python-gpu-336003-0:~/work$ cd DLforTimeSeries/
onyxia@vscode-python-gpu-336003-0:~/work/DLforTimeSeries$ cd moirai-classification/
onyxia@vscode-python-gpu-336003-0:~/work/DLforTimeSeries/moirai-classification$ uv sync
Resolved 146 packages in 1ms
Audited 141 packages in 1ms
onyxia@vscode-python-gpu-336003-0:~/work/DLforTimeSeries/moirai-classification$ uv run main.py"""
#puis chemin vers 3.11

In [ ]:

import numpy as np

from tslearn.datasets import UCR_UEA_datasets
import torch
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from sklearn.linear_model import LogisticRegression
from torch.utils.data import TensorDataset, DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from uni2ts.model.moirai import MoiraiModule
import torch.nn as nn
import torch.optim as optim
from sklearn.linear_model import RidgeClassifierCV

from encoder import MoiraiEncoder

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Data

Import

In [2]:
device = "cuda"
ds = UCR_UEA_datasets()
X_train, y_train, X_test, y_test = ds.load_dataset("LSST")

n_classes = len(set(y_train))
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

Prepare data

In [3]:
def preprocess_data(
    data: np.ndarray,
    *,
    device: str | torch.device = "cpu",
    dtype: torch.dtype = torch.float32,
):
    """
    data: np.ndarray of shape (N, T, V) = (n_individual, time, variate)
    Assumes NO missing values and NO padding in the raw data.
    """

    if not isinstance(data, np.ndarray):
        raise TypeError("data must be a numpy.ndarray")
    if data.ndim != 3:
        raise ValueError(f"Expected shape (N,T,V), got {data.shape}")

    N, T, V = data.shape

    # (N,T,V)
    past_target = torch.as_tensor(data, dtype=dtype, device=device)

    # observed mask: (N,T,V) all True no missing values
    past_observed_target = torch.ones((N, T, V), dtype=torch.bool, device=device)

    # padding mask: (N,T) all if no padding
    past_is_pad = torch.zeros((N, T), dtype=torch.bool, device=device)

    return past_target, past_observed_target, past_is_pad

In [4]:
X_train_target_tensor, X_train_is_target_observed, X_train_is_target_padded = (
    preprocess_data(X_train, device=device)
)

X_test_target_tensor, X_test_is_target_observed, X_test_is_target_padded = (
    preprocess_data(X_test, device=device)
)


print(X_train_target_tensor.shape)
print(X_train_is_target_observed.shape)
print(X_train_is_target_padded.shape)

torch.Size([2459, 36, 6])
torch.Size([2459, 36, 6])
torch.Size([2459, 36])

Creat Z_train and Z_test for each patch size

In [5]:
# Paramètres à tester
patch_sizes = [8, 16, 32, 64]

SIZE = "small"
device = "cuda"

Z_train_patch = {}
Z_test_patch = {}
for patch in patch_sizes:
    
    # 1. Définir les paramètres et l'encodeur pour la taille de patch actuelle
    MODEL_PARAMS = {
        "patch_size": patch,
        "num_samples": 100,
        "target_dim": 1,
        "feat_dynamic_real_dim": 0,
        "past_feat_dynamic_real_dim": 0,
    }
    
    encoder = MoiraiEncoder(
        module=MoiraiModule.from_pretrained(f"Salesforce/moirai-1.1-R-{SIZE}"),
        prediction_length=0,
        context_length=36,
        **MODEL_PARAMS,
    )
    encoder.eval()
    encoder.to(device)
    
    # 2. Extraire les embeddings (Z_train et Z_test)
    with torch.no_grad():
        Z_train = encoder(
            past_target=X_train_target_tensor,
            past_observed_target=X_train_is_target_observed,
            past_is_pad=X_train_is_target_padded,
        )
        Z_test = encoder(
            past_target=X_test_target_tensor,
            past_observed_target=X_test_is_target_observed,
            past_is_pad=X_test_is_target_padded,
        )
        
    Z_train_patch[patch] = Z_train
    Z_test_patch[patch] = Z_test

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [6]:

print(f"{'Patch Size':<12} | {'Train Shape':<25} | {'Test Shape':<25}")
for patch in patch_sizes:
    train_tensor = Z_train_patch[patch]
    test_tensor = Z_test_patch[patch]
    print(f"{patch:<12} | {str(list(train_tensor.shape)):<25} | {str(list(test_tensor.shape)):<25}")

Patch Size   | Train Shape               | Test Shape
8            | [2459, 30, 384]           | [2466, 30, 384]
16           | [2459, 18, 384]           | [2466, 18, 384]
32           | [2459, 12, 384]           | [2466, 12, 384]
64           | [2459, 6, 384]            | [2466, 6, 384]

In [7]:
encoder.module

MoiraiModule(
  (mask_encoding): Embedding(1, 384)
  (scaler): PackedStdScaler()
  (in_proj): MultiInSizeLinear(in_features_ls=[8, 16, 32, 64, 128], out_features=384, bias=True, dtype=torch.float32)
  (encoder): TransformerEncoder(
    (layers): ModuleList(
      (0-5): 6 x TransformerEncoderLayer(
        (self_attn): GroupedQueryAttention(
          (var_attn_bias): BinaryAttentionBias(
            (emb): Embedding(2, 6)
          )
          (time_qk_proj): QueryKeyProjection(
            (query_proj): RotaryProjection()
            (key_proj): RotaryProjection()
          )
          (q_proj): Linear(in_features=384, out_features=384, bias=False)
          (k_proj): Linear(in_features=384, out_features=384, bias=False)
          (v_proj): Linear(in_features=384, out_features=384, bias=False)
          (q_norm): RMSNorm(normalized_shape=(64,), eps=1e-05, weight=True)
          (k_norm): RMSNorm(normalized_shape=(64,), eps=1e-05, weight=True)
          (out_proj): Linear(in_features=384, out_features=384, bias=False)
        )
        (ffn): GatedLinearUnitFeedForward(
          (fc1): Linear(in_features=384, out_features=1024, bias=False)
          (fc2): Linear(in_features=1024, out_features=384, bias=False)
          (dropout1): Dropout(p=0.0, inplace=False)
          (dropout2): Dropout(p=0.0, inplace=False)
          (fc_gate): Linear(in_features=384, out_features=1024, bias=False)
        )
        (norm1): RMSNorm(normalized_shape=(384,), eps=1e-05, weight=True)
        (norm2): RMSNorm(normalized_shape=(384,), eps=1e-05, weight=True)
        (dropout): Dropout(p=0.0, inplace=False)
      )
    )
    (norm): RMSNorm(normalized_shape=(384,), eps=1e-05, weight=True)
  )
  (param_proj): DistrParamProj(
    (proj): ModuleDict(
      (weights_logits): MultiOutSizeLinear(in_features=384, out_features_ls=(32, 64, 128, 256, 512), bias=True, dtype=torch.float32)
      (components): ModuleList(
        (0): ModuleDict(
          (df): MultiOutSizeLinear(in_features=384, out_features_ls=(8, 16, 32, 64, 128), bias=True, dtype=torch.float32)
          (loc): MultiOutSizeLinear(in_features=384, out_features_ls=(8, 16, 32, 64, 128), bias=True, dtype=torch.float32)
          (scale): MultiOutSizeLinear(in_features=384, out_features_ls=(8, 16, 32, 64, 128), bias=True, dtype=torch.float32)
        )
        (1): ModuleDict(
          (loc): MultiOutSizeLinear(in_features=384, out_features_ls=(8, 16, 32, 64, 128), bias=True, dtype=torch.float32)
        )
        (2): ModuleDict(
          (total_count): MultiOutSizeLinear(in_features=384, out_features_ls=(8, 16, 32, 64, 128), bias=True, dtype=torch.float32)
          (logits): MultiOutSizeLinear(in_features=384, out_features_ls=(8, 16, 32, 64, 128), bias=True, dtype=torch.float32)
        )
        (3): ModuleDict(
          (loc): MultiOutSizeLinear(in_features=384, out_features_ls=(8, 16, 32, 64, 128), bias=True, dtype=torch.float32)
          (scale): MultiOutSizeLinear(in_features=384, out_features_ls=(8, 16, 32, 64, 128), bias=True, dtype=torch.float32)
        )
      )
    )
  )
)

# Basic pooling with logistic regression

## Single patch pooling

We started by applying simple pooling techniques (max, min, or mean) and comparing their performance across various patch sizes. Specifically, we evaluated whether to apply this pooling globally across all patches, locally within a single series, or across corresponding patches from all series.

### Training

Define one function for every type of pooling

In [11]:
y_train_tensor = torch.tensor(y_train, dtype=torch.long, device=device)
y_test_tensor = torch.tensor(y_test, dtype=torch.long, device=device)

num_classes = len(torch.unique(y_train_tensor))
NUM_VARS = 6

def apply_pooling_pt(Z_tensor, method, num_vars=NUM_VARS):
    N, S, F = Z_tensor.shape
    P = S // num_vars # Calcul automatique du nombre de patches par variable
    
    # On reshape le tenseur pour séparer les Variables et les Patches
    # Forme résultante : (Batch, Variables, Patches, Features)
    Z_reshaped = Z_tensor.view(N, num_vars, P, F)
    
    # Basique et Global
    if method == "flatten":
        return Z_tensor.reshape(N, -1)
        
    elif method == "global_mean":
        return Z_tensor.mean(dim=1)
        
    elif method == "global_max":
        return Z_tensor.max(dim=1).values
        
    elif method == "global_min":
        return Z_tensor.min(dim=1).values
    
    elif method == "global_mean_max_min":
        return torch.cat([
            Z_tensor.mean(dim=1),
            Z_tensor.max(dim=1).values,
            Z_tensor.min(dim=1).values
        ], dim=1)

    # Pooling sur les Patches (on garde les variables distinctes) ---
    # Réduction sur la dimension 2 (Patches). Résultat : (N, num_vars, F), puis on aplatit
    elif method == "mean_over_patches":
        return Z_reshaped.mean(dim=2).reshape(N, -1)
        
    elif method == "max_over_patches":
        return Z_reshaped.max(dim=2).values.reshape(N, -1)
        
    elif method == "min_over_patches":
        return Z_reshaped.min(dim=2).values.reshape(N, -1)
        
    elif method == "mean_max_min_over_patches":
        p_mean = Z_reshaped.mean(dim=2).reshape(N, -1)
        p_max  = Z_reshaped.max(dim=2).values.reshape(N, -1)
        p_min  = Z_reshaped.min(dim=2).values.reshape(N, -1)
        return torch.cat([p_mean, p_max, p_min], dim=1)

    # Pooling sur les Variables (on synchronise les patches entre variables) ---
    # Réduction sur la dimension 1 (Variables). Résultat : (N, P, F), puis on aplatit
    elif method == "mean_over_variables":
        return Z_reshaped.mean(dim=1).reshape(N, -1)
        
    elif method == "max_over_variables":
        return Z_reshaped.max(dim=1).values.reshape(N, -1)
        
    elif method == "min_over_variables":
        return Z_reshaped.min(dim=1).values.reshape(N, -1)
        
    elif method == "mean_max_min_over_variables":
        v_mean = Z_reshaped.mean(dim=1).reshape(N, -1)
        v_max  = Z_reshaped.max(dim=1).values.reshape(N, -1)
        v_min  = Z_reshaped.min(dim=1).values.reshape(N, -1)
        return torch.cat([v_mean, v_max, v_min], dim=1)

    else:
        raise ValueError(f"Method {method} unknow")

Our machine have GPU so we do a Logistic Regression  with pytorch to be faster

In [10]:
class LogisticRegressionPT(nn.Module):
    def __init__(self, input_dim, num_classes):
        super(LogisticRegressionPT, self).__init__()
        self.linear = nn.Linear(input_dim, num_classes)
        
    def forward(self, x):
        return self.linear(x)

We creat a dataframe to stock the results and we fill it

In [10]:
pooling_methods = [
    "flatten", 
    "global_mean", "global_max", "global_min", "global_mean_max_min",
    "mean_over_patches", "max_over_patches", "min_over_patches", "mean_max_min_over_patches",
    "mean_over_variables", "max_over_variables", "min_over_variables", "mean_max_min_over_variables"
]

alphas_to_test = [0.1,1,10,30,100,300,1000,10000]

df_results = pd.DataFrame(index=pooling_methods, columns=patch_sizes)
df_results.index.name = "Pooling \\ Patch"

for patch in patch_sizes:
    Z_train = Z_train_patch[patch].to(device)
    Z_test = Z_test_patch[patch].to(device)
    
    for pool in pooling_methods:
        # Appliquer le pooling avec la nouvelle logique
        X_train_pool_tensor = apply_pooling_pt(Z_train, pool)
        X_test_pool_tensor = apply_pooling_pt(Z_test, pool)


        # Convertir en NumPy pour Scikit-Learn (on repasse sur CPU)
        X_train_pool = X_train_pool_tensor.cpu().numpy()
        X_test_pool = X_test_pool_tensor.cpu().numpy()

        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train_pool)
        X_test_scaled = scaler.transform(X_test_pool)
        
        # Entraînement avec Scikit-Learn
        # max_iter=1000 pour éviter les warnings de non-convergence
        clf = RidgeClassifierCV(alphas=alphas_to_test, cv = 3)#LogisticRegression(random_state=42, C = 1, max_iter=200)
        clf.fit(X_train_pool, y_train) # Note: on utilise directement y_train (numpy), pas y_train_tensor
        # Évaluation
        y_pred = clf.predict(X_test_pool)
        acc = accuracy_score(y_test, y_pred)
        print(pool)
        print(clf.alpha_)
            
        
        """
        
        input_dim = X_train_pool.shape[1]
        
        # Initialiser le modèle
        model = LogisticRegressionPT(input_dim, num_classes).to(device)
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(model.parameters(), lr=0.01)
        epochs = 200
        model.train()
        for epoch in range(epochs):
            optimizer.zero_grad()
            outputs = model(X_train_pool)
            loss = criterion(outputs, y_train_tensor)
            loss.backward()
            optimizer.step()
            
        # Évaluation
        model.eval()
        with torch.no_grad():
            test_outputs = model(X_test_pool)
            _, predicted = torch.max(test_outputs.data, 1)
            
            correct = (predicted == y_test_tensor).sum().item()
            total = y_test_tensor.size(0)
            acc = correct / total

        """    
        # Remplissage discret du DataFrame
        df_results.loc[pool, patch] = round(acc, 3)

flatten
1000.0
global_mean
1.0
global_max
1.0
global_min
10.0
global_mean_max_min
100.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.8896e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

mean_over_patches
30.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.72297e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.43347e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.27428e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

max_over_patches
300.0
min_over_patches
100.0
mean_max_min_over_patches
300.0
mean_over_variables
30.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=2.90876e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.24296e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.21607e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

max_over_variables
100.0
min_over_variables
300.0
mean_max_min_over_variables
300.0
flatten
1000.0
global_mean
1.0
global_max
30.0
global_min
300.0
global_mean_max_min
100.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.53523e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.68705e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.88582e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

mean_over_patches
300.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.5269e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=2.94444e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.71709e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

max_over_patches
300.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.66922e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.41388e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=5.65156e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

min_over_patches
300.0
mean_max_min_over_patches
1000.0
mean_over_variables
30.0
max_over_variables
300.0
min_over_variables
300.0
mean_max_min_over_variables
300.0
flatten
300.0
global_mean
1.0
global_max
1.0
global_min
10.0
global_mean_max_min
30.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.5813e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.3826e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.92183e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

mean_over_patches
100.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=2.29584e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=2.43649e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.11505e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

max_over_patches
100.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.33442e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.59925e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=4.68899e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

min_over_patches
300.0
mean_max_min_over_patches
300.0
mean_over_variables
30.0
max_over_variables
100.0
min_over_variables
30.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=2.68963e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=2.87604e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.83351e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

mean_max_min_over_variables
300.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.0732e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.1347e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.14779e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

flatten
100.0
global_mean
10.0
global_max
1.0
global_min
10.0
global_mean_max_min
10.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.0732e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.1347e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.14779e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

mean_over_patches
100.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.0732e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.1347e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.14779e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

max_over_patches
100.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.0732e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.1347e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=1.14779e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

min_over_patches
100.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.61689e-09): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.92965e-09): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.63316e-09): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.48775e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.90303e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.72492e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

mean_max_min_over_patches
300.0
mean_over_variables
10.0
max_over_variables
1.0
min_over_variables
10.0
mean_max_min_over_variables
10.0

### Results

In [11]:
# Affichage propre du DataFrame
df_results = df_results.astype(float)
display(df_results)  # Remplace par print(df_results) si display n'est pas supporté

# Recherche de la meilleure combinaison
best_acc = df_results.max().max()
best_pool, best_patch = df_results.stack().idxmax()


print(f"MEILLEURE COMBINAISON : Patch = {best_patch} | Pooling = '{best_pool}'")
print(f"Précision maximale : {best_acc:.3f}")

                                8      16     32     64
Pooling \ Patch
flatten                      0.579  0.587  0.595  0.604
global_mean                  0.582  0.586  0.571  0.571
global_max                   0.533  0.528  0.530  0.562
global_min                   0.526  0.513  0.525  0.564
global_mean_max_min          0.556  0.563  0.555  0.566
mean_over_patches            0.599  0.581  0.584  0.604
max_over_patches             0.575  0.578  0.572  0.604
min_over_patches             0.579  0.582  0.571  0.604
mean_max_min_over_patches    0.599  0.588  0.576  0.604
mean_over_variables          0.567  0.578  0.577  0.571
max_over_variables           0.551  0.545  0.549  0.562
min_over_variables           0.537  0.554  0.558  0.564
mean_max_min_over_variables  0.576  0.581  0.573  0.566

MEILLEURE COMBINAISON : Patch = 64 | Pooling = 'flatten'
Précision maximale : 0.604

We observe that smaller patch sizes of 8 yield better results by capturing more granular information, and that minimizing cross-variable aggregation by pooling over patches rather than series produces the highest accuracy.

## Multi Patch pooling

### Training

In [ ]:
import numpy as np

# On crée un DataFrame avec une seule colonne pour les résultats combinés
df_multiscale_results = pd.DataFrame(index=pooling_methods, columns=["All_Patches_Combined"])
df_multiscale_results.index.name = "Pooling Method"

for pool in pooling_methods:
    X_train_multi = []
    X_test_multi = []
    
    # On boucle sur chaque taille de patch pour extraire et pooler les features
    for patch in patch_sizes:
        Z_train = Z_train_patch[patch].to(device)
        Z_test = Z_test_patch[patch].to(device)
        
        # Appliquer le pooling et passer en NumPy
        X_train_pool = apply_pooling_pt(Z_train, pool).cpu().numpy()
        X_test_pool = apply_pooling_pt(Z_test, pool).cpu().numpy()
        
        X_train_multi.append(X_train_pool)
        X_test_multi.append(X_test_pool)
        
    # ETAPE CLÉ : Concaténer toutes les features sur l'axe des variables (axis=1)
    # Si chaque patch donne un vecteur de taille F, on aura un vecteur de taille F * 4
    X_train_combined = np.concatenate(X_train_multi, axis=1)
    X_test_combined = np.concatenate(X_test_multi, axis=1)

    print(pool)
    print(clf.alpha_)
    
    # Entraînement avec Scikit-Learn sur les features combinées
    clf = RidgeClassifierCV(alphas=alphas_to_test, cv = 3)#LogisticRegression(max_iter=1000, random_state=42)
    clf.fit(X_train_combined, y_train)
    
    # Évaluation
    y_pred = clf.predict(X_test_combined)
    acc = accuracy_score(y_test, y_pred)
        
    # Remplissage du DataFrame
    df_multiscale_results.loc[pool, "All_Patches_Combined"] = round(acc, 3)

flatten
10.0
global_mean
1000.0
global_max
10.0
global_min
100.0
global_mean_max_min
100.0
mean_over_patches
1000.0
max_over_patches
300.0
min_over_patches
1000.0
mean_max_min_over_patches
1000.0

/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.46086e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.91297e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)
/home/onyxia/work/DLforTimeSeries/moirai-classification/.venv/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:265: LinAlgWarning: Ill-conditioned matrix (rcond=3.58398e-08): result may not be accurate.
  dual_coef = linalg.solve(K, y, assume_a="pos", overwrite_a=False)

mean_over_variables
1000.0
max_over_variables
100.0
min_over_variables
100.0
mean_max_min_over_variables
300.0

### Results

In [13]:
display(df_multiscale_results.astype(float))

best_acc_multi = df_multiscale_results.max().max()
best_pool_multi = df_multiscale_results.idxmax()[0]
print(f"MEILLEURE COMBINAISON MULTI-ÉCHELLE : Pooling = '{best_pool_multi}'")
print(f"Précision maximale : {best_acc_multi:.2f}")

                             All_Patches_Combined
Pooling Method
flatten                                      0.61
global_mean                                  0.61
global_max                                   0.58
global_min                                   0.58
global_mean_max_min                          0.59
mean_over_patches                            0.63
max_over_patches                             0.62
min_over_patches                             0.62
mean_max_min_over_patches                    0.63
mean_over_variables                          0.60
max_over_variables                           0.58
min_over_variables                           0.58
mean_max_min_over_variables                  0.60

MEILLEURE COMBINAISON MULTI-ÉCHELLE : Pooling = 'mean_over_patches'
Précision maximale : 0.63

/tmp/ipykernel_2512/1661945645.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  best_pool_multi = df_multiscale_results.idxmax()[0]

# Advanced Pooling

## Generalized Mean (GeM) Pooling (Dont work yet)

Unlike standard methods (like mean or max), Generalized Mean (GeM) Pooling introduces a trainable parameter $p$ that the neural network learns during backpropagation. 
The formula is: 
$$f = \left(\frac{1}{N} \sum |x_i|^p\right)^\frac{1}{p}$$

To find the best approach, we will test GeM pooling across different dimensions dynamically during training:
- **Global**: Pooling over the entire sequence at once.
- **Over Patches**: Keeping variables separate and pooling their respective patches.
- **Over Variables**: Synchronizing patches and pooling across the different series.

For more details, you can refer to the original paper: [Fine-tuning CNN Image Retrieval with No Human Annotation (Radenović et al.)](https://arxiv.org/abs/1711.02512).

In [14]:
class GeMPooling(nn.Module):
    def __init__(self, p=3.0, eps=1e-6):
        super(GeMPooling, self).__init__()
        # The parameter p is learnable by the optimizer
        self.p = nn.Parameter(torch.ones(1) * p)
        self.eps = eps

    def forward(self, x, dim):
        # Clamp values to avoid NaN errors with fractional powers
        x = x.clamp(min=self.eps)
        return x.pow(self.p).mean(dim=dim).pow(1.0 / self.p)


class DynamicGeMClassifierPT(nn.Module):
    def __init__(self, num_vars, num_classes):
        super(DynamicGeMClassifierPT, self).__init__()
        self.num_vars = num_vars
        self.gem = GeMPooling(p=3.0)
        
        # LazyLinear automatically infers the input size during the first forward pass.
        # This allows us to dynamically change the pooling dimension without crashing!
        self.linear = nn.LazyLinear(num_classes)
        
    def forward(self, z, pool_dim):
        N, S, F = z.shape
        
        if pool_dim == "global":
            # Pool over the entire sequence dimension (dim=1)
            pooled = self.gem(z, dim=1)
            
        else:
            P = S // self.num_vars
            # Reshape: (Batch, Variables, Patches, Features)
            z_reshaped = z.view(N, self.num_vars, P, F)
            
            if pool_dim == "patches":
                # Pool over the Patches dimension (dim=2)
                pooled = self.gem(z_reshaped, dim=2)
            elif pool_dim == "variables":
                # Pool over the Variables dimension (dim=1)
                pooled = self.gem(z_reshaped, dim=1)
            else:
                raise ValueError("pool_dim must be 'global', 'patches', or 'variables'")
        
        # Flatten for the linear layer
        pooled_flat = pooled.view(N, -1)
        return self.linear(pooled_flat)

### Dynamic Training and Evaluation

We will now train the GeM model by iterating over both the `patch_sizes` and the `pooling_dimensions`. We will also monitor what value of $p$ the network naturally converged to for each configuration.

In [15]:
pooling_dimensions = ["global", "patches", "variables"]
df_gem_results = pd.DataFrame(index=pooling_dimensions, columns=patch_sizes)
df_gem_results.index.name = "GeM Pooling Dimension"

for patch in patch_sizes:
    Z_train = Z_train_patch[patch].to(device)
    Z_test = Z_test_patch[patch].to(device)
    
    for pool_dim in pooling_dimensions:
        # Instantiate the model
        model = DynamicGeMClassifierPT(num_vars=NUM_VARS, num_classes=num_classes).to(device)
        
        # IMPORTANT: We must perform a "dummy" forward pass with a tiny batch
        # to initialize the LazyLinear weights before creating the optimizer.
        _ = model(Z_train[:2], pool_dim=pool_dim)
        
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(model.parameters(), lr=0.01)
        
        epochs = 500
        model.train()
        for epoch in range(epochs):
            optimizer.zero_grad()
            # We explicitly tell the model which dimension to pool over
            outputs = model(Z_train, pool_dim=pool_dim) 
            loss = criterion(outputs, y_train_tensor)
            loss.backward()
            optimizer.step()
            
        # Evaluation
        model.eval()
        with torch.no_grad():
            test_outputs = model(Z_test, pool_dim=pool_dim)
            _, predicted = torch.max(test_outputs.data, 1)
            
            correct = (predicted == y_test_tensor).sum().item()
            total = y_test_tensor.size(0)
            acc = correct / total
            
            # Retrieve the learned p value
            learned_p = model.gem.p.item()
            
        df_gem_results.loc[pool_dim, patch] = round(acc, 2)
        print(f"Patch: {patch:<4} | Dim: {pool_dim:<10} | Test Acc: {acc:.2f} | Learned p: {learned_p:.2f}")


display(df_gem_results.astype(float))

Patch: 8    | Dim: global     | Test Acc: 0.56 | Learned p: 6.49
Patch: 8    | Dim: patches    | Test Acc: 0.60 | Learned p: 5.58
Patch: 8    | Dim: variables  | Test Acc: 0.53 | Learned p: 5.71
Patch: 16   | Dim: global     | Test Acc: 0.54 | Learned p: 6.25
Patch: 16   | Dim: patches    | Test Acc: 0.57 | Learned p: 5.29
Patch: 16   | Dim: variables  | Test Acc: 0.51 | Learned p: 6.30
Patch: 32   | Dim: global     | Test Acc: 0.51 | Learned p: 6.47
Patch: 32   | Dim: patches    | Test Acc: 0.55 | Learned p: 5.50
Patch: 32   | Dim: variables  | Test Acc: 0.51 | Learned p: 6.81
Patch: 64   | Dim: global     | Test Acc: 0.54 | Learned p: 6.67
Patch: 64   | Dim: patches    | Test Acc: 0.58 | Learned p: 3.08
Patch: 64   | Dim: variables  | Test Acc: 0.54 | Learned p: 6.76

                         8     16    32    64
GeM Pooling Dimension
global                 0.56  0.54  0.51  0.54
patches                0.60  0.57  0.55  0.58
variables              0.53  0.51  0.51  0.54

## Attention Pooling

In [ ]:
class DynamicAttentionClassifier(nn.Module):
    def __init__(self, num_vars, num_classes, patches_counts, in_features=384, mode="global"):
        """
        patches_counts : liste du nombre de patchs par échelle (ex: [30, 18, 12, 6])
        mode : "global" (1), "per_scale" (4), "per_variable" (6), ou "per_both" (24)
        """
        super().__init__()
        self.num_vars = num_vars
        self.patches_counts = patches_counts
        self.num_scales = len(patches_counts)
        self.mode = mode
        
        if mode == "global":
            self.context = nn.Parameter(torch.randn(in_features) * 0.1)
            
        elif mode == "per_scale":
            self.context = nn.Parameter(torch.randn(self.num_scales, in_features) * 0.1)
            
        elif mode == "per_variable":
            self.context = nn.Parameter(torch.randn(self.num_vars, in_features) * 0.1)
            
        elif mode == "per_both":
            self.context = nn.Parameter(torch.randn(self.num_scales, self.num_vars, in_features) * 0.1)
            
            
        self.dropout = nn.Dropout(0.1)
        self.linear = nn.LazyLinear(num_classes)
        
    def forward(self, x):
        B = x.shape[0]
        F = x.shape[-1]
        
        split_sizes = [p * self.num_vars for p in self.patches_counts]
        x_splits = torch.split(x, split_sizes, dim=1)
        
        reshaped_splits = []
        for i, p in enumerate(self.patches_counts):
            reshaped_splits.append(x_splits[i].view(B, self.num_vars, p, F))
            
        if self.mode == "global":
            scores = torch.matmul(x, self.context)
            weights = torch.softmax(scores, dim=1).unsqueeze(-1)
            pooled = (weights * x).sum(dim=1)
            
        elif self.mode == "per_scale":
            pooled_list = []
            for i, xi in enumerate(reshaped_splits):
                xi_flat = xi.view(B, -1, F)
                scores = torch.matmul(xi_flat, self.context[i])
                weights = torch.softmax(scores, dim=1).unsqueeze(-1)
                pooled_list.append((weights * xi_flat).sum(dim=1))
            
            pooled = torch.cat(pooled_list, dim=1)
            
        elif self.mode == "per_variable":
            x_vars = torch.cat(reshaped_splits, dim=2)
            
            scores = (x_vars * self.context.view(1, self.num_vars, 1, F)).sum(dim=-1)
            weights = torch.softmax(scores, dim=2).unsqueeze(-1)
            pooled_vars = (weights * x_vars).sum(dim=2)
            pooled = pooled_vars.view(B, -1)
            
        elif self.mode == "per_both":
            pooled_list = []
            for i, xi in enumerate(reshaped_splits):
                scores = (xi * self.context[i].view(1, self.num_vars, 1, F)).sum(dim=-1)
                weights = torch.softmax(scores, dim=2).unsqueeze(-1)
                pooled_vars = (weights * xi).sum(dim=2)
                pooled_list.append(pooled_vars)
                
            pooled_all = torch.stack(pooled_list, dim=1)
            pooled = pooled_all.view(B, -1)
            
        return self.linear(self.dropout(pooled))

In [18]:
patch_sizes = [8, 16, 32, 64]
NUM_VARS = 6

patches_counts = [Z_train_patch[p].shape[1] // NUM_VARS for p in patch_sizes]
print(f"Nomber of patch for each scale : {patches_counts}")

Z_train_concat = torch.cat([Z_train_patch[p].to(device) for p in patch_sizes], dim=1)
Z_test_concat  = torch.cat([Z_test_patch[p].to(device) for p in patch_sizes], dim=1)

print(f"Shape Z_train: {Z_train_concat.shape}")

Nomber of patch for each scale : [5, 3, 2, 1]
Shape Z_train: torch.Size([2459, 66, 384])

In [19]:
BATCH_SIZE = 64
EPOCHS = 1000
LEARNING_RATE = 0.0001
EVAL_EVERY_N_EPOCHS = 10
PRINT_LOSS_EVERY = 5 
attention_modes = ['global', 'per_scale', 'per_variable', 'per_both']
df_results = pd.DataFrame(index=attention_modes, columns=["Test Accuracy"])
df_results.index.name = "Attention mode"

train_dataset = TensorDataset(Z_train_concat, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

mode = "global"

model = DynamicAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    patches_counts=patches_counts, 
    mode=mode
).to(device)

_ = model(Z_train_concat[:2]) # Dummy pass for LazyLinear

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss()

for epoch in range(EPOCHS):
    model.train()
    running_loss = 0.0
    
    for batch_z, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_z)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item() * batch_z.size(0)
        
    epoch_loss = running_loss / len(train_loader.dataset)
    

    if (epoch + 1) == 1 or (epoch + 1) % PRINT_LOSS_EVERY == 0:
        print(f"Epoch [{epoch+1:3d}/{EPOCHS}] | Train Loss : {epoch_loss:.4f}", end="")
        
        if (epoch + 1) % EVAL_EVERY_N_EPOCHS == 0:
            model.eval()
            with torch.no_grad():
                test_outputs = model(Z_test_concat)
                _, predicted = torch.max(test_outputs.data, 1)
                acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
            print(f" | Test Acc : {acc:.4f}")
        else:
            print() 
            
model.eval()
with torch.no_grad():
    test_outputs = model(Z_test_concat)
    _, predicted = torch.max(test_outputs.data, 1)
    final_acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
    
df_results.loc[mode, "Test Accuracy"] = round(final_acc, 3)

Epoch [  1/1000] | Train Loss : 2.5732
Epoch [  5/1000] | Train Loss : 2.2269
Epoch [ 10/1000] | Train Loss : 2.0220 | Test Acc : 0.3277
Epoch [ 15/1000] | Train Loss : 1.9158
Epoch [ 20/1000] | Train Loss : 1.8305 | Test Acc : 0.4205
Epoch [ 25/1000] | Train Loss : 1.7574
Epoch [ 30/1000] | Train Loss : 1.7009 | Test Acc : 0.4615
Epoch [ 35/1000] | Train Loss : 1.6577
Epoch [ 40/1000] | Train Loss : 1.6227 | Test Acc : 0.4911
Epoch [ 45/1000] | Train Loss : 1.5930
Epoch [ 50/1000] | Train Loss : 1.5653 | Test Acc : 0.5085
Epoch [ 55/1000] | Train Loss : 1.5364
Epoch [ 60/1000] | Train Loss : 1.5186 | Test Acc : 0.5207
Epoch [ 65/1000] | Train Loss : 1.5015
Epoch [ 70/1000] | Train Loss : 1.4811 | Test Acc : 0.5304
Epoch [ 75/1000] | Train Loss : 1.4629
Epoch [ 80/1000] | Train Loss : 1.4538 | Test Acc : 0.5381
Epoch [ 85/1000] | Train Loss : 1.4439
Epoch [ 90/1000] | Train Loss : 1.4248 | Test Acc : 0.5430
Epoch [ 95/1000] | Train Loss : 1.4187
Epoch [100/1000] | Train Loss : 1.4060 | Test Acc : 0.5470
Epoch [105/1000] | Train Loss : 1.3967
Epoch [110/1000] | Train Loss : 1.3919 | Test Acc : 0.5515
Epoch [115/1000] | Train Loss : 1.3751
Epoch [120/1000] | Train Loss : 1.3707 | Test Acc : 0.5539
Epoch [125/1000] | Train Loss : 1.3699
Epoch [130/1000] | Train Loss : 1.3519 | Test Acc : 0.5552
Epoch [135/1000] | Train Loss : 1.3464
Epoch [140/1000] | Train Loss : 1.3426 | Test Acc : 0.5596
Epoch [145/1000] | Train Loss : 1.3346
Epoch [150/1000] | Train Loss : 1.3272 | Test Acc : 0.5637
Epoch [155/1000] | Train Loss : 1.3255
Epoch [160/1000] | Train Loss : 1.3126 | Test Acc : 0.5673
Epoch [165/1000] | Train Loss : 1.3149
Epoch [170/1000] | Train Loss : 1.3061 | Test Acc : 0.5677
Epoch [175/1000] | Train Loss : 1.3045
Epoch [180/1000] | Train Loss : 1.2959 | Test Acc : 0.5689
Epoch [185/1000] | Train Loss : 1.2917
Epoch [190/1000] | Train Loss : 1.2906 | Test Acc : 0.5710
Epoch [195/1000] | Train Loss : 1.2845
Epoch [200/1000] | Train Loss : 1.2861 | Test Acc : 0.5722
Epoch [205/1000] | Train Loss : 1.2746
Epoch [210/1000] | Train Loss : 1.2697 | Test Acc : 0.5726
Epoch [215/1000] | Train Loss : 1.2715
Epoch [220/1000] | Train Loss : 1.2637 | Test Acc : 0.5742
Epoch [225/1000] | Train Loss : 1.2602
Epoch [230/1000] | Train Loss : 1.2496 | Test Acc : 0.5775
Epoch [235/1000] | Train Loss : 1.2525
Epoch [240/1000] | Train Loss : 1.2501 | Test Acc : 0.5783
Epoch [245/1000] | Train Loss : 1.2454
Epoch [250/1000] | Train Loss : 1.2399 | Test Acc : 0.5807
Epoch [255/1000] | Train Loss : 1.2398
Epoch [260/1000] | Train Loss : 1.2350 | Test Acc : 0.5811
Epoch [265/1000] | Train Loss : 1.2343
Epoch [270/1000] | Train Loss : 1.2293 | Test Acc : 0.5811
Epoch [275/1000] | Train Loss : 1.2260
Epoch [280/1000] | Train Loss : 1.2210 | Test Acc : 0.5823
Epoch [285/1000] | Train Loss : 1.2202
Epoch [290/1000] | Train Loss : 1.2162 | Test Acc : 0.5831
Epoch [295/1000] | Train Loss : 1.2131
Epoch [300/1000] | Train Loss : 1.2104 | Test Acc : 0.5848
Epoch [305/1000] | Train Loss : 1.2110
Epoch [310/1000] | Train Loss : 1.2128 | Test Acc : 0.5843
Epoch [315/1000] | Train Loss : 1.2102
Epoch [320/1000] | Train Loss : 1.2019 | Test Acc : 0.5835
Epoch [325/1000] | Train Loss : 1.2001
Epoch [330/1000] | Train Loss : 1.2016 | Test Acc : 0.5843
Epoch [335/1000] | Train Loss : 1.1917
Epoch [340/1000] | Train Loss : 1.1983 | Test Acc : 0.5852
Epoch [345/1000] | Train Loss : 1.1957
Epoch [350/1000] | Train Loss : 1.1886 | Test Acc : 0.5864
Epoch [355/1000] | Train Loss : 1.1901
Epoch [360/1000] | Train Loss : 1.1794 | Test Acc : 0.5868
Epoch [365/1000] | Train Loss : 1.1879
Epoch [370/1000] | Train Loss : 1.1867 | Test Acc : 0.5872
Epoch [375/1000] | Train Loss : 1.1760
Epoch [380/1000] | Train Loss : 1.1837 | Test Acc : 0.5884
Epoch [385/1000] | Train Loss : 1.1797
Epoch [390/1000] | Train Loss : 1.1750 | Test Acc : 0.5868
Epoch [395/1000] | Train Loss : 1.1730
Epoch [400/1000] | Train Loss : 1.1734 | Test Acc : 0.5884
Epoch [405/1000] | Train Loss : 1.1782
Epoch [410/1000] | Train Loss : 1.1706 | Test Acc : 0.5880
Epoch [415/1000] | Train Loss : 1.1679
Epoch [420/1000] | Train Loss : 1.1676 | Test Acc : 0.5884
Epoch [425/1000] | Train Loss : 1.1639
Epoch [430/1000] | Train Loss : 1.1601 | Test Acc : 0.5872
Epoch [435/1000] | Train Loss : 1.1611
Epoch [440/1000] | Train Loss : 1.1568 | Test Acc : 0.5880
Epoch [445/1000] | Train Loss : 1.1586
Epoch [450/1000] | Train Loss : 1.1538 | Test Acc : 0.5884
Epoch [455/1000] | Train Loss : 1.1527
Epoch [460/1000] | Train Loss : 1.1502 | Test Acc : 0.5884
Epoch [465/1000] | Train Loss : 1.1568
Epoch [470/1000] | Train Loss : 1.1416 | Test Acc : 0.5880
Epoch [475/1000] | Train Loss : 1.1444
Epoch [480/1000] | Train Loss : 1.1476 | Test Acc : 0.5884
Epoch [485/1000] | Train Loss : 1.1436
Epoch [490/1000] | Train Loss : 1.1434 | Test Acc : 0.5888
Epoch [495/1000] | Train Loss : 1.1411
Epoch [500/1000] | Train Loss : 1.1397 | Test Acc : 0.5888
Epoch [505/1000] | Train Loss : 1.1455
Epoch [510/1000] | Train Loss : 1.1366 | Test Acc : 0.5888
Epoch [515/1000] | Train Loss : 1.1376
Epoch [520/1000] | Train Loss : 1.1381 | Test Acc : 0.5904
Epoch [525/1000] | Train Loss : 1.1294
Epoch [530/1000] | Train Loss : 1.1297 | Test Acc : 0.5904
Epoch [535/1000] | Train Loss : 1.1259
Epoch [540/1000] | Train Loss : 1.1285 | Test Acc : 0.5916
Epoch [545/1000] | Train Loss : 1.1238
Epoch [550/1000] | Train Loss : 1.1252 | Test Acc : 0.5916
Epoch [555/1000] | Train Loss : 1.1226
Epoch [560/1000] | Train Loss : 1.1265 | Test Acc : 0.5929
Epoch [565/1000] | Train Loss : 1.1212
Epoch [570/1000] | Train Loss : 1.1239 | Test Acc : 0.5933
Epoch [575/1000] | Train Loss : 1.1213
Epoch [580/1000] | Train Loss : 1.1201 | Test Acc : 0.5933
Epoch [585/1000] | Train Loss : 1.1157
Epoch [590/1000] | Train Loss : 1.1130 | Test Acc : 0.5945
Epoch [595/1000] | Train Loss : 1.1199
Epoch [600/1000] | Train Loss : 1.1113 | Test Acc : 0.5937
Epoch [605/1000] | Train Loss : 1.1161
Epoch [610/1000] | Train Loss : 1.1167 | Test Acc : 0.5953
Epoch [615/1000] | Train Loss : 1.1116
Epoch [620/1000] | Train Loss : 1.1035 | Test Acc : 0.5933
Epoch [625/1000] | Train Loss : 1.1089
Epoch [630/1000] | Train Loss : 1.1115 | Test Acc : 0.5945
Epoch [635/1000] | Train Loss : 1.1066
Epoch [640/1000] | Train Loss : 1.1072 | Test Acc : 0.5941
Epoch [645/1000] | Train Loss : 1.1093
Epoch [650/1000] | Train Loss : 1.0993 | Test Acc : 0.5941
Epoch [655/1000] | Train Loss : 1.1004
Epoch [660/1000] | Train Loss : 1.1002 | Test Acc : 0.5941
Epoch [665/1000] | Train Loss : 1.1016
Epoch [670/1000] | Train Loss : 1.0974 | Test Acc : 0.5937
Epoch [675/1000] | Train Loss : 1.1011
Epoch [680/1000] | Train Loss : 1.0994 | Test Acc : 0.5937
Epoch [685/1000] | Train Loss : 1.0984
Epoch [690/1000] | Train Loss : 1.0943 | Test Acc : 0.5941
Epoch [695/1000] | Train Loss : 1.0976
Epoch [700/1000] | Train Loss : 1.0888 | Test Acc : 0.5933
Epoch [705/1000] | Train Loss : 1.0861
Epoch [710/1000] | Train Loss : 1.0850 | Test Acc : 0.5941
Epoch [715/1000] | Train Loss : 1.0916
Epoch [720/1000] | Train Loss : 1.0807 | Test Acc : 0.5937
Epoch [725/1000] | Train Loss : 1.0796
Epoch [730/1000] | Train Loss : 1.0948 | Test Acc : 0.5929
Epoch [735/1000] | Train Loss : 1.0856
Epoch [740/1000] | Train Loss : 1.0884 | Test Acc : 0.5953
Epoch [745/1000] | Train Loss : 1.0846
Epoch [750/1000] | Train Loss : 1.0868 | Test Acc : 0.5945
Epoch [755/1000] | Train Loss : 1.0855
Epoch [760/1000] | Train Loss : 1.0789 | Test Acc : 0.5929
Epoch [765/1000] | Train Loss : 1.0821
Epoch [770/1000] | Train Loss : 1.0796 | Test Acc : 0.5916
Epoch [775/1000] | Train Loss : 1.0751
Epoch [780/1000] | Train Loss : 1.0761 | Test Acc : 0.5945
Epoch [785/1000] | Train Loss : 1.0805
Epoch [790/1000] | Train Loss : 1.0741 | Test Acc : 0.5937
Epoch [795/1000] | Train Loss : 1.0741
Epoch [800/1000] | Train Loss : 1.0694 | Test Acc : 0.5933
Epoch [805/1000] | Train Loss : 1.0725
Epoch [810/1000] | Train Loss : 1.0758 | Test Acc : 0.5921
Epoch [815/1000] | Train Loss : 1.0677
Epoch [820/1000] | Train Loss : 1.0705 | Test Acc : 0.5933
Epoch [825/1000] | Train Loss : 1.0682
Epoch [830/1000] | Train Loss : 1.0662 | Test Acc : 0.5925
Epoch [835/1000] | Train Loss : 1.0640
Epoch [840/1000] | Train Loss : 1.0662 | Test Acc : 0.5921
Epoch [845/1000] | Train Loss : 1.0663
Epoch [850/1000] | Train Loss : 1.0702 | Test Acc : 0.5912
Epoch [855/1000] | Train Loss : 1.0706
Epoch [860/1000] | Train Loss : 1.0677 | Test Acc : 0.5912
Epoch [865/1000] | Train Loss : 1.0691
Epoch [870/1000] | Train Loss : 1.0595 | Test Acc : 0.5916
Epoch [875/1000] | Train Loss : 1.0651
Epoch [880/1000] | Train Loss : 1.0642 | Test Acc : 0.5908
Epoch [885/1000] | Train Loss : 1.0568
Epoch [890/1000] | Train Loss : 1.0636 | Test Acc : 0.5912
Epoch [895/1000] | Train Loss : 1.0627
Epoch [900/1000] | Train Loss : 1.0581 | Test Acc : 0.5912
Epoch [905/1000] | Train Loss : 1.0561
Epoch [910/1000] | Train Loss : 1.0547 | Test Acc : 0.5908
Epoch [915/1000] | Train Loss : 1.0589
Epoch [920/1000] | Train Loss : 1.0478 | Test Acc : 0.5908
Epoch [925/1000] | Train Loss : 1.0513
Epoch [930/1000] | Train Loss : 1.0519 | Test Acc : 0.5912
Epoch [935/1000] | Train Loss : 1.0476
Epoch [940/1000] | Train Loss : 1.0532 | Test Acc : 0.5916
Epoch [945/1000] | Train Loss : 1.0560
Epoch [950/1000] | Train Loss : 1.0509 | Test Acc : 0.5912
Epoch [955/1000] | Train Loss : 1.0504
Epoch [960/1000] | Train Loss : 1.0503 | Test Acc : 0.5925
Epoch [965/1000] | Train Loss : 1.0538
Epoch [970/1000] | Train Loss : 1.0505 | Test Acc : 0.5925
Epoch [975/1000] | Train Loss : 1.0484
Epoch [980/1000] | Train Loss : 1.0488 | Test Acc : 0.5912
Epoch [985/1000] | Train Loss : 1.0494
Epoch [990/1000] | Train Loss : 1.0503 | Test Acc : 0.5904
Epoch [995/1000] | Train Loss : 1.0421
Epoch [1000/1000] | Train Loss : 1.0449 | Test Acc : 0.5916

In [20]:
mode = "per_scale"

model = DynamicAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    patches_counts=patches_counts, 
    mode=mode
).to(device)

_ = model(Z_train_concat[:2]) # Dummy pass for LazyLinear

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss()

for epoch in range(EPOCHS):
    model.train()
    running_loss = 0.0
    
    for batch_z, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_z)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item() * batch_z.size(0)
        
    epoch_loss = running_loss / len(train_loader.dataset)
    

    if (epoch + 1) == 1 or (epoch + 1) % PRINT_LOSS_EVERY == 0:
        print(f"Epoch [{epoch+1:3d}/{EPOCHS}] | Train Loss : {epoch_loss:.4f}", end="")
        
        if (epoch + 1) % EVAL_EVERY_N_EPOCHS == 0:
            model.eval()
            with torch.no_grad():
                test_outputs = model(Z_test_concat)
                _, predicted = torch.max(test_outputs.data, 1)
                acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
            print(f" | Test Acc : {acc:.4f}")
        else:
            print() 
            
model.eval()
with torch.no_grad():
    test_outputs = model(Z_test_concat)
    _, predicted = torch.max(test_outputs.data, 1)
    final_acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
    
df_results.loc[mode, "Test Accuracy"] = round(final_acc, 3)

Epoch [  1/1000] | Train Loss : 2.4546
Epoch [  5/1000] | Train Loss : 1.8087
Epoch [ 10/1000] | Train Loss : 1.6112 | Test Acc : 0.5024
Epoch [ 15/1000] | Train Loss : 1.4951
Epoch [ 20/1000] | Train Loss : 1.4152 | Test Acc : 0.5539
Epoch [ 25/1000] | Train Loss : 1.3630
Epoch [ 30/1000] | Train Loss : 1.3198 | Test Acc : 0.5746
Epoch [ 35/1000] | Train Loss : 1.2825
Epoch [ 40/1000] | Train Loss : 1.2541 | Test Acc : 0.5835
Epoch [ 45/1000] | Train Loss : 1.2284
Epoch [ 50/1000] | Train Loss : 1.2058 | Test Acc : 0.5908
Epoch [ 55/1000] | Train Loss : 1.1881
Epoch [ 60/1000] | Train Loss : 1.1654 | Test Acc : 0.5929
Epoch [ 65/1000] | Train Loss : 1.1436
Epoch [ 70/1000] | Train Loss : 1.1357 | Test Acc : 0.5957
Epoch [ 75/1000] | Train Loss : 1.1182
Epoch [ 80/1000] | Train Loss : 1.1063 | Test Acc : 0.5985
Epoch [ 85/1000] | Train Loss : 1.0902
Epoch [ 90/1000] | Train Loss : 1.0761 | Test Acc : 0.5969
Epoch [ 95/1000] | Train Loss : 1.0624
Epoch [100/1000] | Train Loss : 1.0518 | Test Acc : 0.5949
Epoch [105/1000] | Train Loss : 1.0400
Epoch [110/1000] | Train Loss : 1.0334 | Test Acc : 0.5937
Epoch [115/1000] | Train Loss : 1.0180
Epoch [120/1000] | Train Loss : 1.0128 | Test Acc : 0.5941
Epoch [125/1000] | Train Loss : 1.0032
Epoch [130/1000] | Train Loss : 0.9901 | Test Acc : 0.5937
Epoch [135/1000] | Train Loss : 0.9807
Epoch [140/1000] | Train Loss : 0.9729 | Test Acc : 0.5945
Epoch [145/1000] | Train Loss : 0.9652
Epoch [150/1000] | Train Loss : 0.9560 | Test Acc : 0.5945
Epoch [155/1000] | Train Loss : 0.9515
Epoch [160/1000] | Train Loss : 0.9418 | Test Acc : 0.5965
Epoch [165/1000] | Train Loss : 0.9324
Epoch [170/1000] | Train Loss : 0.9216 | Test Acc : 0.5945
Epoch [175/1000] | Train Loss : 0.9244
Epoch [180/1000] | Train Loss : 0.9082 | Test Acc : 0.5945
Epoch [185/1000] | Train Loss : 0.9068
Epoch [190/1000] | Train Loss : 0.9019 | Test Acc : 0.5925
Epoch [195/1000] | Train Loss : 0.8913
Epoch [200/1000] | Train Loss : 0.8841 | Test Acc : 0.5945
Epoch [205/1000] | Train Loss : 0.8771
Epoch [210/1000] | Train Loss : 0.8687 | Test Acc : 0.5957
Epoch [215/1000] | Train Loss : 0.8716
Epoch [220/1000] | Train Loss : 0.8669 | Test Acc : 0.5969
Epoch [225/1000] | Train Loss : 0.8595
Epoch [230/1000] | Train Loss : 0.8482 | Test Acc : 0.5969
Epoch [235/1000] | Train Loss : 0.8468
Epoch [240/1000] | Train Loss : 0.8341 | Test Acc : 0.5981
Epoch [245/1000] | Train Loss : 0.8342
Epoch [250/1000] | Train Loss : 0.8217 | Test Acc : 0.5953
Epoch [255/1000] | Train Loss : 0.8221
Epoch [260/1000] | Train Loss : 0.8216 | Test Acc : 0.5949
Epoch [265/1000] | Train Loss : 0.8069
Epoch [270/1000] | Train Loss : 0.7985 | Test Acc : 0.5961
Epoch [275/1000] | Train Loss : 0.7948
Epoch [280/1000] | Train Loss : 0.7973 | Test Acc : 0.5941
Epoch [285/1000] | Train Loss : 0.7898
Epoch [290/1000] | Train Loss : 0.7854 | Test Acc : 0.5937
Epoch [295/1000] | Train Loss : 0.7858
Epoch [300/1000] | Train Loss : 0.7825 | Test Acc : 0.5921
Epoch [305/1000] | Train Loss : 0.7729
Epoch [310/1000] | Train Loss : 0.7643 | Test Acc : 0.5921
Epoch [315/1000] | Train Loss : 0.7666
Epoch [320/1000] | Train Loss : 0.7680 | Test Acc : 0.5900
Epoch [325/1000] | Train Loss : 0.7580
Epoch [330/1000] | Train Loss : 0.7476 | Test Acc : 0.5904
Epoch [335/1000] | Train Loss : 0.7538
Epoch [340/1000] | Train Loss : 0.7453 | Test Acc : 0.5921
Epoch [345/1000] | Train Loss : 0.7381
Epoch [350/1000] | Train Loss : 0.7340 | Test Acc : 0.5912
Epoch [355/1000] | Train Loss : 0.7259
Epoch [360/1000] | Train Loss : 0.7352 | Test Acc : 0.5900
Epoch [365/1000] | Train Loss : 0.7225
Epoch [370/1000] | Train Loss : 0.7200 | Test Acc : 0.5904
Epoch [375/1000] | Train Loss : 0.7186
Epoch [380/1000] | Train Loss : 0.7151 | Test Acc : 0.5908
Epoch [385/1000] | Train Loss : 0.7050
Epoch [390/1000] | Train Loss : 0.7083 | Test Acc : 0.5908
Epoch [395/1000] | Train Loss : 0.7134
Epoch [400/1000] | Train Loss : 0.7052 | Test Acc : 0.5912
Epoch [405/1000] | Train Loss : 0.6905
Epoch [410/1000] | Train Loss : 0.6957 | Test Acc : 0.5876
Epoch [415/1000] | Train Loss : 0.6862
Epoch [420/1000] | Train Loss : 0.6873 | Test Acc : 0.5880
Epoch [425/1000] | Train Loss : 0.6755
Epoch [430/1000] | Train Loss : 0.6768 | Test Acc : 0.5888
Epoch [435/1000] | Train Loss : 0.6842
Epoch [440/1000] | Train Loss : 0.6793 | Test Acc : 0.5864
Epoch [445/1000] | Train Loss : 0.6677
Epoch [450/1000] | Train Loss : 0.6700 | Test Acc : 0.5856
Epoch [455/1000] | Train Loss : 0.6636
Epoch [460/1000] | Train Loss : 0.6600 | Test Acc : 0.5843
Epoch [465/1000] | Train Loss : 0.6515
Epoch [470/1000] | Train Loss : 0.6581 | Test Acc : 0.5848
Epoch [475/1000] | Train Loss : 0.6603
Epoch [480/1000] | Train Loss : 0.6529 | Test Acc : 0.5839
Epoch [485/1000] | Train Loss : 0.6394
Epoch [490/1000] | Train Loss : 0.6484 | Test Acc : 0.5819
Epoch [495/1000] | Train Loss : 0.6387
Epoch [500/1000] | Train Loss : 0.6375 | Test Acc : 0.5827
Epoch [505/1000] | Train Loss : 0.6409
Epoch [510/1000] | Train Loss : 0.6372 | Test Acc : 0.5803
Epoch [515/1000] | Train Loss : 0.6302
Epoch [520/1000] | Train Loss : 0.6292 | Test Acc : 0.5783
Epoch [525/1000] | Train Loss : 0.6212
Epoch [530/1000] | Train Loss : 0.6298 | Test Acc : 0.5795
Epoch [535/1000] | Train Loss : 0.6168
Epoch [540/1000] | Train Loss : 0.6237 | Test Acc : 0.5787
Epoch [545/1000] | Train Loss : 0.6169
Epoch [550/1000] | Train Loss : 0.6139 | Test Acc : 0.5779
Epoch [555/1000] | Train Loss : 0.6201
Epoch [560/1000] | Train Loss : 0.6112 | Test Acc : 0.5791
Epoch [565/1000] | Train Loss : 0.6058
Epoch [570/1000] | Train Loss : 0.6051 | Test Acc : 0.5783
Epoch [575/1000] | Train Loss : 0.6060
Epoch [580/1000] | Train Loss : 0.6046 | Test Acc : 0.5775
Epoch [585/1000] | Train Loss : 0.5950
Epoch [590/1000] | Train Loss : 0.6008 | Test Acc : 0.5734
Epoch [595/1000] | Train Loss : 0.5887
Epoch [600/1000] | Train Loss : 0.6032 | Test Acc : 0.5758
Epoch [605/1000] | Train Loss : 0.5882
Epoch [610/1000] | Train Loss : 0.5863 | Test Acc : 0.5742
Epoch [615/1000] | Train Loss : 0.5859
Epoch [620/1000] | Train Loss : 0.5816 | Test Acc : 0.5754
Epoch [625/1000] | Train Loss : 0.5804
Epoch [630/1000] | Train Loss : 0.5840 | Test Acc : 0.5730
Epoch [635/1000] | Train Loss : 0.5763
Epoch [640/1000] | Train Loss : 0.5799 | Test Acc : 0.5714
Epoch [645/1000] | Train Loss : 0.5831
Epoch [650/1000] | Train Loss : 0.5729 | Test Acc : 0.5706
Epoch [655/1000] | Train Loss : 0.5725
Epoch [660/1000] | Train Loss : 0.5669 | Test Acc : 0.5665
Epoch [665/1000] | Train Loss : 0.5691
Epoch [670/1000] | Train Loss : 0.5638 | Test Acc : 0.5681
Epoch [675/1000] | Train Loss : 0.5585
Epoch [680/1000] | Train Loss : 0.5661 | Test Acc : 0.5669
Epoch [685/1000] | Train Loss : 0.5579
Epoch [690/1000] | Train Loss : 0.5523 | Test Acc : 0.5649
Epoch [695/1000] | Train Loss : 0.5518
Epoch [700/1000] | Train Loss : 0.5573 | Test Acc : 0.5669
Epoch [705/1000] | Train Loss : 0.5475
Epoch [710/1000] | Train Loss : 0.5473 | Test Acc : 0.5657
Epoch [715/1000] | Train Loss : 0.5440
Epoch [720/1000] | Train Loss : 0.5516 | Test Acc : 0.5633
Epoch [725/1000] | Train Loss : 0.5421
Epoch [730/1000] | Train Loss : 0.5444 | Test Acc : 0.5596
Epoch [735/1000] | Train Loss : 0.5410
Epoch [740/1000] | Train Loss : 0.5333 | Test Acc : 0.5588
Epoch [745/1000] | Train Loss : 0.5403
Epoch [750/1000] | Train Loss : 0.5347 | Test Acc : 0.5588
Epoch [755/1000] | Train Loss : 0.5382
Epoch [760/1000] | Train Loss : 0.5289 | Test Acc : 0.5592
Epoch [765/1000] | Train Loss : 0.5350
Epoch [770/1000] | Train Loss : 0.5212 | Test Acc : 0.5584
Epoch [775/1000] | Train Loss : 0.5266
Epoch [780/1000] | Train Loss : 0.5228 | Test Acc : 0.5572
Epoch [785/1000] | Train Loss : 0.5231
Epoch [790/1000] | Train Loss : 0.5159 | Test Acc : 0.5580
Epoch [795/1000] | Train Loss : 0.5199
Epoch [800/1000] | Train Loss : 0.5248 | Test Acc : 0.5588
Epoch [805/1000] | Train Loss : 0.5167
Epoch [810/1000] | Train Loss : 0.5126 | Test Acc : 0.5580
Epoch [815/1000] | Train Loss : 0.5180
Epoch [820/1000] | Train Loss : 0.5179 | Test Acc : 0.5572
Epoch [825/1000] | Train Loss : 0.5168
Epoch [830/1000] | Train Loss : 0.5119 | Test Acc : 0.5592
Epoch [835/1000] | Train Loss : 0.4931
Epoch [840/1000] | Train Loss : 0.5038 | Test Acc : 0.5576
Epoch [845/1000] | Train Loss : 0.5072
Epoch [850/1000] | Train Loss : 0.5035 | Test Acc : 0.5620
Epoch [855/1000] | Train Loss : 0.5021
Epoch [860/1000] | Train Loss : 0.5020 | Test Acc : 0.5608
Epoch [865/1000] | Train Loss : 0.5034
Epoch [870/1000] | Train Loss : 0.4999 | Test Acc : 0.5588
Epoch [875/1000] | Train Loss : 0.4966
Epoch [880/1000] | Train Loss : 0.5101 | Test Acc : 0.5576
Epoch [885/1000] | Train Loss : 0.4911
Epoch [890/1000] | Train Loss : 0.4946 | Test Acc : 0.5568
Epoch [895/1000] | Train Loss : 0.4898
Epoch [900/1000] | Train Loss : 0.4894 | Test Acc : 0.5584
Epoch [905/1000] | Train Loss : 0.4818
Epoch [910/1000] | Train Loss : 0.4815 | Test Acc : 0.5600
Epoch [915/1000] | Train Loss : 0.4940
Epoch [920/1000] | Train Loss : 0.4909 | Test Acc : 0.5564
Epoch [925/1000] | Train Loss : 0.4791
Epoch [930/1000] | Train Loss : 0.4746 | Test Acc : 0.5560
Epoch [935/1000] | Train Loss : 0.4787
Epoch [940/1000] | Train Loss : 0.4835 | Test Acc : 0.5576
Epoch [945/1000] | Train Loss : 0.4815
Epoch [950/1000] | Train Loss : 0.4714 | Test Acc : 0.5572
Epoch [955/1000] | Train Loss : 0.4742
Epoch [960/1000] | Train Loss : 0.4757 | Test Acc : 0.5588
Epoch [965/1000] | Train Loss : 0.4658
Epoch [970/1000] | Train Loss : 0.4601 | Test Acc : 0.5560
Epoch [975/1000] | Train Loss : 0.4662
Epoch [980/1000] | Train Loss : 0.4717 | Test Acc : 0.5576
Epoch [985/1000] | Train Loss : 0.4729
Epoch [990/1000] | Train Loss : 0.4790 | Test Acc : 0.5572
Epoch [995/1000] | Train Loss : 0.4682
Epoch [1000/1000] | Train Loss : 0.4683 | Test Acc : 0.5552

In [21]:
mode = "per_variable"

model = DynamicAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    patches_counts=patches_counts, 
    mode=mode
).to(device)

_ = model(Z_train_concat[:2]) # Dummy pass for LazyLinear

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss()

for epoch in range(EPOCHS):
    model.train()
    running_loss = 0.0
    
    for batch_z, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_z)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item() * batch_z.size(0)
        
    epoch_loss = running_loss / len(train_loader.dataset)
    

    if (epoch + 1) == 1 or (epoch + 1) % PRINT_LOSS_EVERY == 0:
        print(f"Epoch [{epoch+1:3d}/{EPOCHS}] | Train Loss : {epoch_loss:.4f}", end="")
        
        if (epoch + 1) % EVAL_EVERY_N_EPOCHS == 0:
            model.eval()
            with torch.no_grad():
                test_outputs = model(Z_test_concat)
                _, predicted = torch.max(test_outputs.data, 1)
                acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
            print(f" | Test Acc : {acc:.4f}")
        else:
            print() 
            
model.eval()
with torch.no_grad():
    test_outputs = model(Z_test_concat)
    _, predicted = torch.max(test_outputs.data, 1)
    final_acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
    
df_results.loc[mode, "Test Accuracy"] = round(final_acc, 3)

Epoch [  1/1000] | Train Loss : 2.4016
Epoch [  5/1000] | Train Loss : 1.8149
Epoch [ 10/1000] | Train Loss : 1.5742 | Test Acc : 0.5134
Epoch [ 15/1000] | Train Loss : 1.4266
Epoch [ 20/1000] | Train Loss : 1.3243 | Test Acc : 0.5608
Epoch [ 25/1000] | Train Loss : 1.2464
Epoch [ 30/1000] | Train Loss : 1.1873 | Test Acc : 0.5864
Epoch [ 35/1000] | Train Loss : 1.1397
Epoch [ 40/1000] | Train Loss : 1.1004 | Test Acc : 0.5985
Epoch [ 45/1000] | Train Loss : 1.0611
Epoch [ 50/1000] | Train Loss : 1.0281 | Test Acc : 0.6099
Epoch [ 55/1000] | Train Loss : 0.9992
Epoch [ 60/1000] | Train Loss : 0.9723 | Test Acc : 0.6107
Epoch [ 65/1000] | Train Loss : 0.9433
Epoch [ 70/1000] | Train Loss : 0.9211 | Test Acc : 0.6119
Epoch [ 75/1000] | Train Loss : 0.9024
Epoch [ 80/1000] | Train Loss : 0.8755 | Test Acc : 0.6131
Epoch [ 85/1000] | Train Loss : 0.8564
Epoch [ 90/1000] | Train Loss : 0.8326 | Test Acc : 0.6156
Epoch [ 95/1000] | Train Loss : 0.8220
Epoch [100/1000] | Train Loss : 0.8044 | Test Acc : 0.6176
Epoch [105/1000] | Train Loss : 0.7864
Epoch [110/1000] | Train Loss : 0.7727 | Test Acc : 0.6127
Epoch [115/1000] | Train Loss : 0.7549
Epoch [120/1000] | Train Loss : 0.7345 | Test Acc : 0.6139
Epoch [125/1000] | Train Loss : 0.7306
Epoch [130/1000] | Train Loss : 0.7155 | Test Acc : 0.6148
Epoch [135/1000] | Train Loss : 0.7022
Epoch [140/1000] | Train Loss : 0.6915 | Test Acc : 0.6115
Epoch [145/1000] | Train Loss : 0.6783
Epoch [150/1000] | Train Loss : 0.6690 | Test Acc : 0.6103
Epoch [155/1000] | Train Loss : 0.6602
Epoch [160/1000] | Train Loss : 0.6536 | Test Acc : 0.6099
Epoch [165/1000] | Train Loss : 0.6347
Epoch [170/1000] | Train Loss : 0.6294 | Test Acc : 0.6087
Epoch [175/1000] | Train Loss : 0.6195
Epoch [180/1000] | Train Loss : 0.6032 | Test Acc : 0.6083
Epoch [185/1000] | Train Loss : 0.5963
Epoch [190/1000] | Train Loss : 0.5893 | Test Acc : 0.6062
Epoch [195/1000] | Train Loss : 0.5770
Epoch [200/1000] | Train Loss : 0.5720 | Test Acc : 0.6018
Epoch [205/1000] | Train Loss : 0.5628
Epoch [210/1000] | Train Loss : 0.5648 | Test Acc : 0.6038
Epoch [215/1000] | Train Loss : 0.5474
Epoch [220/1000] | Train Loss : 0.5319 | Test Acc : 0.6034
Epoch [225/1000] | Train Loss : 0.5310
Epoch [230/1000] | Train Loss : 0.5217 | Test Acc : 0.5985
Epoch [235/1000] | Train Loss : 0.5153
Epoch [240/1000] | Train Loss : 0.5126 | Test Acc : 0.5977
Epoch [245/1000] | Train Loss : 0.4998
Epoch [250/1000] | Train Loss : 0.4948 | Test Acc : 0.5965
Epoch [255/1000] | Train Loss : 0.4855
Epoch [260/1000] | Train Loss : 0.4735 | Test Acc : 0.5961
Epoch [265/1000] | Train Loss : 0.4768
Epoch [270/1000] | Train Loss : 0.4586 | Test Acc : 0.5953
Epoch [275/1000] | Train Loss : 0.4688
Epoch [280/1000] | Train Loss : 0.4541 | Test Acc : 0.5949
Epoch [285/1000] | Train Loss : 0.4461
Epoch [290/1000] | Train Loss : 0.4467 | Test Acc : 0.5912
Epoch [295/1000] | Train Loss : 0.4451
Epoch [300/1000] | Train Loss : 0.4355 | Test Acc : 0.5912
Epoch [305/1000] | Train Loss : 0.4272
Epoch [310/1000] | Train Loss : 0.4232 | Test Acc : 0.5896
Epoch [315/1000] | Train Loss : 0.4170
Epoch [320/1000] | Train Loss : 0.4139 | Test Acc : 0.5880
Epoch [325/1000] | Train Loss : 0.4091
Epoch [330/1000] | Train Loss : 0.4024 | Test Acc : 0.5884
Epoch [335/1000] | Train Loss : 0.4016
Epoch [340/1000] | Train Loss : 0.3913 | Test Acc : 0.5848
Epoch [345/1000] | Train Loss : 0.3905
Epoch [350/1000] | Train Loss : 0.3789 | Test Acc : 0.5848
Epoch [355/1000] | Train Loss : 0.3792
Epoch [360/1000] | Train Loss : 0.3786 | Test Acc : 0.5835
Epoch [365/1000] | Train Loss : 0.3690
Epoch [370/1000] | Train Loss : 0.3623 | Test Acc : 0.5835
Epoch [375/1000] | Train Loss : 0.3640
Epoch [380/1000] | Train Loss : 0.3628 | Test Acc : 0.5831
Epoch [385/1000] | Train Loss : 0.3549
Epoch [390/1000] | Train Loss : 0.3499 | Test Acc : 0.5819
Epoch [395/1000] | Train Loss : 0.3476
Epoch [400/1000] | Train Loss : 0.3401 | Test Acc : 0.5803
Epoch [405/1000] | Train Loss : 0.3401
Epoch [410/1000] | Train Loss : 0.3401 | Test Acc : 0.5787
Epoch [415/1000] | Train Loss : 0.3307
Epoch [420/1000] | Train Loss : 0.3260 | Test Acc : 0.5787
Epoch [425/1000] | Train Loss : 0.3253
Epoch [430/1000] | Train Loss : 0.3252 | Test Acc : 0.5775
Epoch [435/1000] | Train Loss : 0.3131
Epoch [440/1000] | Train Loss : 0.3158 | Test Acc : 0.5779
Epoch [445/1000] | Train Loss : 0.3081
Epoch [450/1000] | Train Loss : 0.3070 | Test Acc : 0.5742
Epoch [455/1000] | Train Loss : 0.3098
Epoch [460/1000] | Train Loss : 0.3026 | Test Acc : 0.5754
Epoch [465/1000] | Train Loss : 0.3024
Epoch [470/1000] | Train Loss : 0.2990 | Test Acc : 0.5718
Epoch [475/1000] | Train Loss : 0.2943
Epoch [480/1000] | Train Loss : 0.2968 | Test Acc : 0.5750
Epoch [485/1000] | Train Loss : 0.2918
Epoch [490/1000] | Train Loss : 0.2886 | Test Acc : 0.5746
Epoch [495/1000] | Train Loss : 0.2887
Epoch [500/1000] | Train Loss : 0.2786 | Test Acc : 0.5758
Epoch [505/1000] | Train Loss : 0.2694
Epoch [510/1000] | Train Loss : 0.2756 | Test Acc : 0.5706
Epoch [515/1000] | Train Loss : 0.2723
Epoch [520/1000] | Train Loss : 0.2674 | Test Acc : 0.5710
Epoch [525/1000] | Train Loss : 0.2722
Epoch [530/1000] | Train Loss : 0.2760 | Test Acc : 0.5697
Epoch [535/1000] | Train Loss : 0.2628
Epoch [540/1000] | Train Loss : 0.2624 | Test Acc : 0.5714
Epoch [545/1000] | Train Loss : 0.2604
Epoch [550/1000] | Train Loss : 0.2514 | Test Acc : 0.5722
Epoch [555/1000] | Train Loss : 0.2519
Epoch [560/1000] | Train Loss : 0.2498 | Test Acc : 0.5730
Epoch [565/1000] | Train Loss : 0.2541
Epoch [570/1000] | Train Loss : 0.2471 | Test Acc : 0.5730
Epoch [575/1000] | Train Loss : 0.2494
Epoch [580/1000] | Train Loss : 0.2431 | Test Acc : 0.5718
Epoch [585/1000] | Train Loss : 0.2418
Epoch [590/1000] | Train Loss : 0.2392 | Test Acc : 0.5734
Epoch [595/1000] | Train Loss : 0.2401
Epoch [600/1000] | Train Loss : 0.2321 | Test Acc : 0.5706
Epoch [605/1000] | Train Loss : 0.2331
Epoch [610/1000] | Train Loss : 0.2359 | Test Acc : 0.5697
Epoch [615/1000] | Train Loss : 0.2268
Epoch [620/1000] | Train Loss : 0.2231 | Test Acc : 0.5702
Epoch [625/1000] | Train Loss : 0.2236
Epoch [630/1000] | Train Loss : 0.2167 | Test Acc : 0.5710
Epoch [635/1000] | Train Loss : 0.2203
Epoch [640/1000] | Train Loss : 0.2184 | Test Acc : 0.5702
Epoch [645/1000] | Train Loss : 0.2187
Epoch [650/1000] | Train Loss : 0.2170 | Test Acc : 0.5693
Epoch [655/1000] | Train Loss : 0.2122
Epoch [660/1000] | Train Loss : 0.2115 | Test Acc : 0.5689
Epoch [665/1000] | Train Loss : 0.2061
Epoch [670/1000] | Train Loss : 0.2066 | Test Acc : 0.5685
Epoch [675/1000] | Train Loss : 0.2080
Epoch [680/1000] | Train Loss : 0.2044 | Test Acc : 0.5657
Epoch [685/1000] | Train Loss : 0.2010
Epoch [690/1000] | Train Loss : 0.2001 | Test Acc : 0.5689
Epoch [695/1000] | Train Loss : 0.2000
Epoch [700/1000] | Train Loss : 0.2014 | Test Acc : 0.5661
Epoch [705/1000] | Train Loss : 0.1975
Epoch [710/1000] | Train Loss : 0.2001 | Test Acc : 0.5661
Epoch [715/1000] | Train Loss : 0.1986
Epoch [720/1000] | Train Loss : 0.1933 | Test Acc : 0.5685
Epoch [725/1000] | Train Loss : 0.1853
Epoch [730/1000] | Train Loss : 0.1892 | Test Acc : 0.5620
Epoch [735/1000] | Train Loss : 0.1920
Epoch [740/1000] | Train Loss : 0.1908 | Test Acc : 0.5637
Epoch [745/1000] | Train Loss : 0.1908
Epoch [750/1000] | Train Loss : 0.1866 | Test Acc : 0.5641
Epoch [755/1000] | Train Loss : 0.1868
Epoch [760/1000] | Train Loss : 0.1767 | Test Acc : 0.5641
Epoch [765/1000] | Train Loss : 0.1807
Epoch [770/1000] | Train Loss : 0.1846 | Test Acc : 0.5649
Epoch [775/1000] | Train Loss : 0.1824
Epoch [780/1000] | Train Loss : 0.1843 | Test Acc : 0.5653
Epoch [785/1000] | Train Loss : 0.1760
Epoch [790/1000] | Train Loss : 0.1738 | Test Acc : 0.5657
Epoch [795/1000] | Train Loss : 0.1699
Epoch [800/1000] | Train Loss : 0.1753 | Test Acc : 0.5641
Epoch [805/1000] | Train Loss : 0.1686
Epoch [810/1000] | Train Loss : 0.1671 | Test Acc : 0.5616
Epoch [815/1000] | Train Loss : 0.1650
Epoch [820/1000] | Train Loss : 0.1665 | Test Acc : 0.5645
Epoch [825/1000] | Train Loss : 0.1695
Epoch [830/1000] | Train Loss : 0.1630 | Test Acc : 0.5661
Epoch [835/1000] | Train Loss : 0.1606
Epoch [840/1000] | Train Loss : 0.1640 | Test Acc : 0.5641
Epoch [845/1000] | Train Loss : 0.1557
Epoch [850/1000] | Train Loss : 0.1569 | Test Acc : 0.5649
Epoch [855/1000] | Train Loss : 0.1594
Epoch [860/1000] | Train Loss : 0.1555 | Test Acc : 0.5641
Epoch [865/1000] | Train Loss : 0.1513
Epoch [870/1000] | Train Loss : 0.1536 | Test Acc : 0.5641
Epoch [875/1000] | Train Loss : 0.1567
Epoch [880/1000] | Train Loss : 0.1514 | Test Acc : 0.5624
Epoch [885/1000] | Train Loss : 0.1573
Epoch [890/1000] | Train Loss : 0.1549 | Test Acc : 0.5629
Epoch [895/1000] | Train Loss : 0.1526
Epoch [900/1000] | Train Loss : 0.1480 | Test Acc : 0.5629
Epoch [905/1000] | Train Loss : 0.1478
Epoch [910/1000] | Train Loss : 0.1554 | Test Acc : 0.5604
Epoch [915/1000] | Train Loss : 0.1438
Epoch [920/1000] | Train Loss : 0.1427 | Test Acc : 0.5612
Epoch [925/1000] | Train Loss : 0.1403
Epoch [930/1000] | Train Loss : 0.1417 | Test Acc : 0.5612
Epoch [935/1000] | Train Loss : 0.1355
Epoch [940/1000] | Train Loss : 0.1415 | Test Acc : 0.5592
Epoch [945/1000] | Train Loss : 0.1454
Epoch [950/1000] | Train Loss : 0.1437 | Test Acc : 0.5592
Epoch [955/1000] | Train Loss : 0.1407
Epoch [960/1000] | Train Loss : 0.1386 | Test Acc : 0.5592
Epoch [965/1000] | Train Loss : 0.1400
Epoch [970/1000] | Train Loss : 0.1390 | Test Acc : 0.5568
Epoch [975/1000] | Train Loss : 0.1337
Epoch [980/1000] | Train Loss : 0.1376 | Test Acc : 0.5580
Epoch [985/1000] | Train Loss : 0.1361
Epoch [990/1000] | Train Loss : 0.1319 | Test Acc : 0.5584
Epoch [995/1000] | Train Loss : 0.1314
Epoch [1000/1000] | Train Loss : 0.1337 | Test Acc : 0.5580

In [22]:
mode = "per_both"

model = DynamicAttentionClassifier(
    num_vars=NUM_VARS, 
    num_classes=num_classes, 
    patches_counts=patches_counts, 
    mode=mode
).to(device)

_ = model(Z_train_concat[:2]) # Dummy pass for LazyLinear

optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss()

for epoch in range(EPOCHS):
    model.train()
    running_loss = 0.0
    
    for batch_z, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_z)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item() * batch_z.size(0)
        
    epoch_loss = running_loss / len(train_loader.dataset)
    

    if (epoch + 1) == 1 or (epoch + 1) % PRINT_LOSS_EVERY == 0:
        print(f"Epoch [{epoch+1:3d}/{EPOCHS}] | Train Loss : {epoch_loss:.4f}", end="")
        
        if (epoch + 1) % EVAL_EVERY_N_EPOCHS == 0:
            model.eval()
            with torch.no_grad():
                test_outputs = model(Z_test_concat)
                _, predicted = torch.max(test_outputs.data, 1)
                acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
            print(f" | Test Acc : {acc:.4f}")
        else:
            print() 
            
model.eval()
with torch.no_grad():
    test_outputs = model(Z_test_concat)
    _, predicted = torch.max(test_outputs.data, 1)
    final_acc = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
    
df_results.loc[mode, "Test Accuracy"] = round(final_acc, 3)

Epoch [  1/1000] | Train Loss : 2.0565
Epoch [  5/1000] | Train Loss : 1.2490
Epoch [ 10/1000] | Train Loss : 1.0207 | Test Acc : 0.6225
Epoch [ 15/1000] | Train Loss : 0.8901
Epoch [ 20/1000] | Train Loss : 0.7820 | Test Acc : 0.6403
Epoch [ 25/1000] | Train Loss : 0.7095
Epoch [ 30/1000] | Train Loss : 0.6394 | Test Acc : 0.6464
Epoch [ 35/1000] | Train Loss : 0.5824
Epoch [ 40/1000] | Train Loss : 0.5296 | Test Acc : 0.6387
Epoch [ 45/1000] | Train Loss : 0.4894
Epoch [ 50/1000] | Train Loss : 0.4488 | Test Acc : 0.6346
Epoch [ 55/1000] | Train Loss : 0.4175
Epoch [ 60/1000] | Train Loss : 0.3866 | Test Acc : 0.6387
Epoch [ 65/1000] | Train Loss : 0.3612
Epoch [ 70/1000] | Train Loss : 0.3359 | Test Acc : 0.6322
Epoch [ 75/1000] | Train Loss : 0.3099
Epoch [ 80/1000] | Train Loss : 0.2878 | Test Acc : 0.6302
Epoch [ 85/1000] | Train Loss : 0.2684
Epoch [ 90/1000] | Train Loss : 0.2525 | Test Acc : 0.6318
Epoch [ 95/1000] | Train Loss : 0.2386
Epoch [100/1000] | Train Loss : 0.2252 | Test Acc : 0.6310
Epoch [105/1000] | Train Loss : 0.2118
Epoch [110/1000] | Train Loss : 0.1968 | Test Acc : 0.6322
Epoch [115/1000] | Train Loss : 0.1849
Epoch [120/1000] | Train Loss : 0.1745 | Test Acc : 0.6257
Epoch [125/1000] | Train Loss : 0.1669
Epoch [130/1000] | Train Loss : 0.1534 | Test Acc : 0.6281
Epoch [135/1000] | Train Loss : 0.1464
Epoch [140/1000] | Train Loss : 0.1371 | Test Acc : 0.6294
Epoch [145/1000] | Train Loss : 0.1305
Epoch [150/1000] | Train Loss : 0.1268 | Test Acc : 0.6294
Epoch [155/1000] | Train Loss : 0.1163
Epoch [160/1000] | Train Loss : 0.1104 | Test Acc : 0.6281
Epoch [165/1000] | Train Loss : 0.1073
Epoch [170/1000] | Train Loss : 0.1000 | Test Acc : 0.6261
Epoch [175/1000] | Train Loss : 0.0946
Epoch [180/1000] | Train Loss : 0.0897 | Test Acc : 0.6298
Epoch [185/1000] | Train Loss : 0.0854
Epoch [190/1000] | Train Loss : 0.0819 | Test Acc : 0.6261
Epoch [195/1000] | Train Loss : 0.0779
Epoch [200/1000] | Train Loss : 0.0730 | Test Acc : 0.6225
Epoch [205/1000] | Train Loss : 0.0699
Epoch [210/1000] | Train Loss : 0.0674 | Test Acc : 0.6212
Epoch [215/1000] | Train Loss : 0.0632
Epoch [220/1000] | Train Loss : 0.0594 | Test Acc : 0.6212
Epoch [225/1000] | Train Loss : 0.0563
Epoch [230/1000] | Train Loss : 0.0559 | Test Acc : 0.6188
Epoch [235/1000] | Train Loss : 0.0550
Epoch [240/1000] | Train Loss : 0.0499 | Test Acc : 0.6273
Epoch [245/1000] | Train Loss : 0.0494
Epoch [250/1000] | Train Loss : 0.0482 | Test Acc : 0.6160
Epoch [255/1000] | Train Loss : 0.0456
Epoch [260/1000] | Train Loss : 0.0441 | Test Acc : 0.6229
Epoch [265/1000] | Train Loss : 0.0425
Epoch [270/1000] | Train Loss : 0.0409 | Test Acc : 0.6204
Epoch [275/1000] | Train Loss : 0.0391
Epoch [280/1000] | Train Loss : 0.0354 | Test Acc : 0.6221
Epoch [285/1000] | Train Loss : 0.0348
Epoch [290/1000] | Train Loss : 0.0329 | Test Acc : 0.6164
Epoch [295/1000] | Train Loss : 0.0339
Epoch [300/1000] | Train Loss : 0.0315 | Test Acc : 0.6156
Epoch [305/1000] | Train Loss : 0.0293
Epoch [310/1000] | Train Loss : 0.0298 | Test Acc : 0.6111
Epoch [315/1000] | Train Loss : 0.0283
Epoch [320/1000] | Train Loss : 0.0272 | Test Acc : 0.6144
Epoch [325/1000] | Train Loss : 0.0263
Epoch [330/1000] | Train Loss : 0.0242 | Test Acc : 0.6119
Epoch [335/1000] | Train Loss : 0.0241
Epoch [340/1000] | Train Loss : 0.0236 | Test Acc : 0.6152
Epoch [345/1000] | Train Loss : 0.0226
Epoch [350/1000] | Train Loss : 0.0222 | Test Acc : 0.6131
Epoch [355/1000] | Train Loss : 0.0218
Epoch [360/1000] | Train Loss : 0.0212 | Test Acc : 0.6135
Epoch [365/1000] | Train Loss : 0.0196
Epoch [370/1000] | Train Loss : 0.0198 | Test Acc : 0.6103
Epoch [375/1000] | Train Loss : 0.0199
Epoch [380/1000] | Train Loss : 0.0182 | Test Acc : 0.6079
Epoch [385/1000] | Train Loss : 0.0179
Epoch [390/1000] | Train Loss : 0.0181 | Test Acc : 0.6083
Epoch [395/1000] | Train Loss : 0.0180
Epoch [400/1000] | Train Loss : 0.0167 | Test Acc : 0.6103
Epoch [405/1000] | Train Loss : 0.0171
Epoch [410/1000] | Train Loss : 0.0165 | Test Acc : 0.6075
Epoch [415/1000] | Train Loss : 0.0148
Epoch [420/1000] | Train Loss : 0.0145 | Test Acc : 0.6083
Epoch [425/1000] | Train Loss : 0.0158
Epoch [430/1000] | Train Loss : 0.0152 | Test Acc : 0.6099
Epoch [435/1000] | Train Loss : 0.0146
Epoch [440/1000] | Train Loss : 0.0135 | Test Acc : 0.6058
Epoch [445/1000] | Train Loss : 0.0136
Epoch [450/1000] | Train Loss : 0.0135 | Test Acc : 0.6034
Epoch [455/1000] | Train Loss : 0.0127
Epoch [460/1000] | Train Loss : 0.0124 | Test Acc : 0.6067
Epoch [465/1000] | Train Loss : 0.0125
Epoch [470/1000] | Train Loss : 0.0128 | Test Acc : 0.6034
Epoch [475/1000] | Train Loss : 0.0127
Epoch [480/1000] | Train Loss : 0.0128 | Test Acc : 0.6018
Epoch [485/1000] | Train Loss : 0.0119
Epoch [490/1000] | Train Loss : 0.0117 | Test Acc : 0.6026
Epoch [495/1000] | Train Loss : 0.0122
Epoch [500/1000] | Train Loss : 0.0117 | Test Acc : 0.6046
Epoch [505/1000] | Train Loss : 0.0110
Epoch [510/1000] | Train Loss : 0.0116 | Test Acc : 0.6018
Epoch [515/1000] | Train Loss : 0.0112
Epoch [520/1000] | Train Loss : 0.0115 | Test Acc : 0.6026
Epoch [525/1000] | Train Loss : 0.0100
Epoch [530/1000] | Train Loss : 0.0110 | Test Acc : 0.6046
Epoch [535/1000] | Train Loss : 0.0108
Epoch [540/1000] | Train Loss : 0.0106 | Test Acc : 0.6022
Epoch [545/1000] | Train Loss : 0.0097
Epoch [550/1000] | Train Loss : 0.0098 | Test Acc : 0.6038
Epoch [555/1000] | Train Loss : 0.0103
Epoch [560/1000] | Train Loss : 0.0101 | Test Acc : 0.6014
Epoch [565/1000] | Train Loss : 0.0097
Epoch [570/1000] | Train Loss : 0.0100 | Test Acc : 0.6046
Epoch [575/1000] | Train Loss : 0.0096
Epoch [580/1000] | Train Loss : 0.0114 | Test Acc : 0.6067
Epoch [585/1000] | Train Loss : 0.0100
Epoch [590/1000] | Train Loss : 0.0104 | Test Acc : 0.6030
Epoch [595/1000] | Train Loss : 0.0090
Epoch [600/1000] | Train Loss : 0.0087 | Test Acc : 0.6002
Epoch [605/1000] | Train Loss : 0.0089
Epoch [610/1000] | Train Loss : 0.0082 | Test Acc : 0.6022
Epoch [615/1000] | Train Loss : 0.0096
Epoch [620/1000] | Train Loss : 0.0087 | Test Acc : 0.6026
Epoch [625/1000] | Train Loss : 0.0087
Epoch [630/1000] | Train Loss : 0.0088 | Test Acc : 0.5994
Epoch [635/1000] | Train Loss : 0.0082
Epoch [640/1000] | Train Loss : 0.0089 | Test Acc : 0.6046
Epoch [645/1000] | Train Loss : 0.0082
Epoch [650/1000] | Train Loss : 0.0084 | Test Acc : 0.6050
Epoch [655/1000] | Train Loss : 0.0086
Epoch [660/1000] | Train Loss : 0.0085 | Test Acc : 0.5969
Epoch [665/1000] | Train Loss : 0.0079
Epoch [670/1000] | Train Loss : 0.0082 | Test Acc : 0.6030
Epoch [675/1000] | Train Loss : 0.0077
Epoch [680/1000] | Train Loss : 0.0076 | Test Acc : 0.6006
Epoch [685/1000] | Train Loss : 0.0084
Epoch [690/1000] | Train Loss : 0.0078 | Test Acc : 0.6054
Epoch [695/1000] | Train Loss : 0.0082
Epoch [700/1000] | Train Loss : 0.0082 | Test Acc : 0.6038
Epoch [705/1000] | Train Loss : 0.0072
Epoch [710/1000] | Train Loss : 0.0081 | Test Acc : 0.5985
Epoch [715/1000] | Train Loss : 0.0085
Epoch [720/1000] | Train Loss : 0.0077 | Test Acc : 0.6030
Epoch [725/1000] | Train Loss : 0.0077
Epoch [730/1000] | Train Loss : 0.0077 | Test Acc : 0.6010
Epoch [735/1000] | Train Loss : 0.0077
Epoch [740/1000] | Train Loss : 0.0080 | Test Acc : 0.5985
Epoch [745/1000] | Train Loss : 0.0085
Epoch [750/1000] | Train Loss : 0.0073 | Test Acc : 0.5998
Epoch [755/1000] | Train Loss : 0.0072
Epoch [760/1000] | Train Loss : 0.0077 | Test Acc : 0.6042
Epoch [765/1000] | Train Loss : 0.0075
Epoch [770/1000] | Train Loss : 0.0073 | Test Acc : 0.5998
Epoch [775/1000] | Train Loss : 0.0078
Epoch [780/1000] | Train Loss : 0.0073 | Test Acc : 0.6034
Epoch [785/1000] | Train Loss : 0.0077
Epoch [790/1000] | Train Loss : 0.0077 | Test Acc : 0.5994
Epoch [795/1000] | Train Loss : 0.0067
Epoch [800/1000] | Train Loss : 0.0072 | Test Acc : 0.6022
Epoch [805/1000] | Train Loss : 0.0076
Epoch [810/1000] | Train Loss : 0.0071 | Test Acc : 0.6006
Epoch [815/1000] | Train Loss : 0.0073
Epoch [820/1000] | Train Loss : 0.0084 | Test Acc : 0.5989
Epoch [825/1000] | Train Loss : 0.0072
Epoch [830/1000] | Train Loss : 0.0075 | Test Acc : 0.6034
Epoch [835/1000] | Train Loss : 0.0076
Epoch [840/1000] | Train Loss : 0.0071 | Test Acc : 0.6026
Epoch [845/1000] | Train Loss : 0.0070
Epoch [850/1000] | Train Loss : 0.0078 | Test Acc : 0.5994
Epoch [855/1000] | Train Loss : 0.0070
Epoch [860/1000] | Train Loss : 0.0072 | Test Acc : 0.6002
Epoch [865/1000] | Train Loss : 0.0071
Epoch [870/1000] | Train Loss : 0.0071 | Test Acc : 0.5985
Epoch [875/1000] | Train Loss : 0.0066
Epoch [880/1000] | Train Loss : 0.0071 | Test Acc : 0.5965
Epoch [885/1000] | Train Loss : 0.0065
Epoch [890/1000] | Train Loss : 0.0067 | Test Acc : 0.5981
Epoch [895/1000] | Train Loss : 0.0063
Epoch [900/1000] | Train Loss : 0.0066 | Test Acc : 0.5994
Epoch [905/1000] | Train Loss : 0.0073
Epoch [910/1000] | Train Loss : 0.0072 | Test Acc : 0.6002
Epoch [915/1000] | Train Loss : 0.0065
Epoch [920/1000] | Train Loss : 0.0066 | Test Acc : 0.6006
Epoch [925/1000] | Train Loss : 0.0068
Epoch [930/1000] | Train Loss : 0.0068 | Test Acc : 0.5981
Epoch [935/1000] | Train Loss : 0.0076
Epoch [940/1000] | Train Loss : 0.0066 | Test Acc : 0.5998
Epoch [945/1000] | Train Loss : 0.0065
Epoch [950/1000] | Train Loss : 0.0062 | Test Acc : 0.5981
Epoch [955/1000] | Train Loss : 0.0074
Epoch [960/1000] | Train Loss : 0.0065 | Test Acc : 0.5989
Epoch [965/1000] | Train Loss : 0.0076
Epoch [970/1000] | Train Loss : 0.0071 | Test Acc : 0.5961
Epoch [975/1000] | Train Loss : 0.0066
Epoch [980/1000] | Train Loss : 0.0067 | Test Acc : 0.5981
Epoch [985/1000] | Train Loss : 0.0071
Epoch [990/1000] | Train Loss : 0.0061 | Test Acc : 0.5985
Epoch [995/1000] | Train Loss : 0.0068
Epoch [1000/1000] | Train Loss : 0.0063 | Test Acc : 0.5994

In [23]:
display(df_results)

               Test Accuracy
Attention mode
global                 0.592
per_scale              0.555
per_variable           0.558
per_both               0.599

TODO :
- target_dim?
- result diff de maxime car moi moi pytorch pour reglog